import { NodeIndicesData } from './node-indices.model';

export const INDICES_DATA: NodeIndicesData = {
  indicesData: {
    headers: [
      {
        cols: [
          {
            label: 'Indices',
            valueField: 'indices',
            classes: 'text-left',
            selected: true,
            severityColorField: true,
            filter: {
              isFilter: true,
              type: 'contains',
            },
            isSort: true,
            urlField: true,
            width: '30%',
          },
          {
            label: '#Docs',
            valueField: 'docs',
            classes: 'text-left',
            selected: true,
            filter: {
              isFilter: true,
              type: 'contains',
            },
            isSort: true,
          },
          {
            label: 'Primary State',
            valueField: 'primaryState',
            classes: 'text-left',
            selected: true,
            filter: {
              isFilter: true,
              type: 'contains',
            },
            isSort: false,
          },
          {
            label: '# Shards',
            valueField: 'shards',
            classes: 'text-left',
            selected: true,
            filter: {
              isFilter: true,
              type: 'contains',
            },
            isSort: true,
          },
          {
            label: '#Replicas',
            valueField: 'replicas',
            classes: 'text-left',
            selected: true,
            filter: {
              isFilter: true,
              type: 'contains',
            },
            isSort: true,
           
          },
          {
            label: 'Status',
            valueField: 'status',
            classes: 'text-left',
            selected: true,
            filter: {
              isFilter: true,
              type: 'custom',
            },
            editableCol: {
              editable: true,
              editType: 'dropdown',
            },
            isSort: true,
           
          },
          {
            label: 'Action',
            valueField: 'action',
            classes: 'text-center',
            selected: true,
            filter: {
              isFilter: true,
              type: 'contains',
            },
            isSort: true,
            iconField: true,
           width: '6%'
          },
        ],
      },
    ],
    data: [
      {
        indices: 'netForest_monitoring-2020-05-23',
        docs: '5',
        primaryState: '23.5kb',
        shards: '5',
        replicas: '0',
        status: 'Open',
        action: 'icons8 icons8-edit-2',
      },
      {
        indices: 'netForest_monitoring-2020-05-3',
        docs: '10',
        primaryState: '231.5kb',
        shards: '52',
        replicas: '4',
        status: 'Close',
        action: 'icons8 icons8-edit-2',
      },
      {
        indices: 'netForest_monitoring-2020-05-23',
        docs: '5',
        primaryState: '23.5kb',
        shards: '5',
        replicas: '0',
        status: 'Open',
        action: 'icons8 icons8-edit-2',
      },
      {
        indices: 'netForest_monitoring-2020-05-3',
        docs: '10',
        primaryState: '231.5kb',
        shards: '52',
        replicas: '4',
        status: 'Close',
        action: 'icons8 icons8-edit-2',
      },
      {
        indices: 'netForest_monitoring-2020-05-23',
        docs: '5',
        primaryState: '23.5kb',
        shards: '5',
        replicas: '0',
        status: 'Open',
        action: 'icons8 icons8-edit-2',
      },
      {
        indices: 'netForest_monitoring-2020-05-3',
        docs: '10',
        primaryState: '231.5kb',
        shards: '52',
        replicas: '4',
        status: 'Close',
        action: 'icons8 icons8-edit-2',
      },
      {
        indices: 'netForest_monitoring-2020-05-23',
        docs: '5',
        primaryState: '23.5kb',
        shards: '5',
        replicas: '0',
        status: 'Open',
        action: 'icons8 icons8-edit-2',
      },
      {
        indices: 'netForest_monitoring-2020-05-3',
        docs: '10',
        primaryState: '231.5kb',
        shards: '52',
        replicas: '4',
        status: 'Close',
        action: 'icons8 icons8-edit-2',
      },
      {
        indices: 'netForest_monitoring-2020-05-23',
        docs: '5',
        primaryState: '23.5kb',
        shards: '5',
        replicas: '0',
        status: 'Open',
        action: 'icons8 icons8-edit-2',
      },
      {
        indices: 'netForest_monitoring-2020-05-3',
        docs: '10',
        primaryState: '231.5kb',
        shards: '52',
        replicas: '4',
        status: 'Close',
        action: 'icons8 icons8-edit-2',
      },
      {
        indices: 'netForest_monitoring-2020-05-23',
        docs: '5',
        primaryState: '23.5kb',
        shards: '5',
        replicas: '0',
        status: 'Open',
        action: 'icons8 icons8-edit-2',
      },
      {
        indices: 'netForest_monitoring-2020-05-3',
        docs: '10',
        primaryState: '231.5kb',
        shards: '52',
        replicas: '4',
        status: 'Close',
        action: 'icons8 icons8-edit-2',
      },
      {
        indices: 'netForest_monitoring-2020-05-23',
        docs: '5',
        primaryState: '23.5kb',
        shards: '5',
        replicas: '0',
        status: 'Open',
        action: 'icons8 icons8-edit-2',
      },
      {
        indices: 'netForest_monitoring-2020-05-3',
        docs: '10',
        primaryState: '231.5kb',
        shards: '52',
        replicas: '4',
        status: 'Close',
        action: 'icons8 icons8-edit-2',
      },
      {
        indices: 'netForest_monitoring-2020-05-23',
        docs: '5',
        primaryState: '23.5kb',
        shards: '5',
        replicas: '0',
        status: 'Open',
        action: 'icons8 icons8-edit-2',
      },
      {
        indices: 'netForest_monitoring-2020-05-3',
        docs: '10',
        primaryState: '231.5kb',
        shards: '52',
        replicas: '4',
        status: 'Close',
        action: 'icons8 icons8-edit-2',
      },

      {
        indices: 'netForest_monitoring-2020-05-23',
        docs: '5',
        primaryState: '23.5kb',
        shards: '5',
        replicas: '0',
        status: 'Open',
        action: 'icons8 icons8-edit-2',
      },
      {
        indices: 'netForest_monitoring-2020-05-3',
        docs: '10',
        primaryState: '231.5kb',
        shards: '52',
        replicas: '4',
        status: 'Close',
        action: 'icons8 icons8-edit-2',
      },
      {
        indices: 'netForest_monitoring-2020-05-23',
        docs: '5',
        primaryState: '23.5kb',
        shards: '5',
        replicas: '0',
        status: 'Open',
        action: 'icons8 icons8-edit-2',
      },
      {
        indices: 'netForest_monitoring-2020-05-3',
        docs: '10',
        primaryState: '231.5kb',
        shards: '52',
        replicas: '4',
        status: 'Close',
        action: 'icons8 icons8-edit-2',
      },
      {
        indices: 'netForest_monitoring-2020-05-23',
        docs: '5',
        primaryState: '23.5kb',
        shards: '5',
        replicas: '0',
        status: 'Open',
        action: 'icons8 icons8-edit-2',
      },
      {
        indices: 'netForest_monitoring-2020-05-3',
        docs: '10',
        primaryState: '231.5kb',
        shards: '52',
        replicas: '4',
        status: 'Close',
        action: 'icons8 icons8-edit-2',
      },
      {
        indices: 'netForest_monitoring-2020-05-23',
        docs: '5',
        primaryState: '23.5kb',
        shards: '5',
        replicas: '0',
        status: 'Open',
        action: 'icons8 icons8-edit-2',
      },
      {
        indices: 'netForest_monitoring-2020-05-3',
        docs: '10',
        primaryState: '231.5kb',
        shards: '52',
        replicas: '4',
        status: 'Close',
        action: 'icons8 icons8-edit-2',
      },
    ],
    paginator: {
      first: 0,
      rows: 10,
      rowsPerPageOptions: [10, 20, 30, 50, 100],
    },
    tableFilter: true,
  },
};
