import { RepeatedCalloutDetailsTable } from './repeated-callout-details.model';

export const REPEATED_CALLOUT_DETAILS_TABLE: RepeatedCalloutDetailsTable = {

  headers: [
    {
      cols: [
        {
          label: 'Arguments',
          valueField: 'methods',
          classes: 'text-left',
          filter: {
            isFilter: true,
            type: 'contains',
          },
          isSort: true,
        },
        {
          label: 'Elapsed Time',
          valueField: 'elapsedTime',
          classes: 'text-left',
          filter: {
            isFilter: true,
            type: 'contains',
          },
          isSort: true,
        },
        {
          label: 'Wall Time',
          valueField: 'wallTime',
          classes: 'text-left',
          filter: {
            isFilter: true,
            type: 'contains',
          },
          isSort: true,
        },
        {
          label: 'Percentage',
          valueField: 'percentage',
          classes: 'text-left',
          filter: {
            isFilter: true,
            type: 'contains',
          },
          isSort: true,
        },
        {
          label: 'CPU Time',
          valueField: 'cpu',
          classes: 'text-left',
          filter: {
            isFilter: true,
            type: 'contains',
          },
          isSort: true,
        },
        {
          label: 'Thread Queue',
          valueField: 'threadQueue',
          classes: 'text-left',
          filter: {
            isFilter: true,
            type: 'contains',
          },
          isSort: true,
        },
        {
          label: 'Self Time',
          valueField: 'selfTime',
          classes: 'text-left',
          filter: {
            isFilter: true,
            type: 'contains',
          },
          isSort: true,
        },
        {
          label: 'Thread ID',
          valueField: 'threadId',
          classes: 'text-left',
          filter: {
            isFilter: true,
            type: 'contains',
          },
          isSort: true,
        },
        {
          label: 'Thread',
          valueField: 'thread',
          classes: 'text-left',
          filter: {
            isFilter: true,
            type: 'contains',
          },
          isSort: true,
        },
        {
          label: 'Arguments1',
          valueField: 'arguments',
          classes: 'text-left',
          filter: {
            isFilter: true,
            type: 'contains',
          },
          isSort: true,
        },
        {
          label: 'Instance',
          valueField: 'instance',
          classes: 'text-left',
          filter: {
            isFilter: true,
            type: 'contains',
          },
          isSort: true,
        },
      ],
    },
  ],
  data: [
    {

      methods: 'CC-W-CA-Fremont-HE1',
      elapsedTime: '76',
      wallTime: '0',
      percentage: '3.241%',
      cpu: '0',
      threadQueue: '2589.191',
      selfTime: '2589.191',
      threadId: '1',
      thread: '1',
      arguments: '4',
      instance: '0',
    },
    {
      methods: 'CC-W-CA-Fremont-HE2',
      elapsedTime: '76',
      wallTime: '0',
      percentage: '3.241%',
      cpu: '0',
      threadQueue: '2589.191',
      selfTime: '2589.191',
      threadId: '1',
      thread: '1',
      arguments: '4',
      instance: '0',
    },
    {
      methods: 'CC-W-CA-Fremont-HE1',
      elapsedTime: '71',
      wallTime: '0',
      percentage: '3.241%',
      cpu: '0',
      threadQueue: '2589.191',
      selfTime: '2589.191',
      threadId: '1',
      thread: '1',
      arguments: '4',
      instance: '0',

    },
    {
      methods: 'CC-W-CA-Fremont-HE1',
      elapsedTime: '73',
      wallTime: '0',
      percentage: '3.241%',
      cpu: '0',
      threadQueue: '2589.191',
      selfTime: '2589.191',
      threadId: '1',
      thread: '1',
      arguments: '2',
      instance: '0',

    },
    {
      methods: 'CC-W-CA-Fremont-HE1',
      elapsedTime: '76',
      wallTime: '0',
      percentage: '3.241%',
      cpu: '0',
      threadQueue: '2589.191',
      selfTime: '2589.191',
      threadId: '1',
      thread: '1',
      arguments: '4',
      instance: '0',

    },
    {
      methods: 'CC-W-CA-Fremont-HE1',
      elapsedTime: '76',
      wallTime: '0',
      percentage: '3.241%',
      cpu: '0',
      threadQueue: '2589.191',
      selfTime: '2589.191',
      threadId: '1',
      thread: '1',
      arguments: '4',
      instance: '0',

    },
    {
      methods: 'CC-W-CA-Fremont-HE1',
      elapsedTime: '76',
      wallTime: '0',
      percentage: '3.241%',
      cpu: '0',
      threadQueue: '2589.191',
      selfTime: '2589.191',
      threadId: '1',
      thread: '1',
      arguments: '4',
      instance: '0',

    },
    {
      methods: 'CC-W-CA-Fremont-HE1',
      elapsedTime: '76',
      wallTime: '0',
      percentage: '3.241%',
      cpu: '0',
      threadQueue: '2589.191',
      selfTime: '2589.191',
      threadId: '1',
      thread: '1',
      arguments: '4',
      instance: '0',

    },
    {
      methods: 'CC-W-CA-Fremont-HE1',
      elapsedTime: '76',
      wallTime: '0',
      percentage: '3.241%',
      cpu: '0',
      threadQueue: '2589.191',
      selfTime: '2589.191',
      threadId: '1',
      thread: '1',
      arguments: '4',
      instance: '0',

    },
  ],
  paginator: {
    first: 1,
    rows: 33,
    rowsPerPageOptions: [10, 25, 50, 100],
  },
  tableFilter: false,
};
