import {
  TransactionFlowmapChart,
  TransactionFlowMapData,
} from './transaction-flowmap.model';

export const TRANSACTION_FLOWMAP_DATA: TransactionFlowMapData = {
  businessJacket: {
    headers: [
      {
        cols: [
          {
            label: 'Business Transaction',
            valueField: 'businessTransaction',
            classes: 'text-left',
          },
          {
            label: 'Start Time',
            valueField: 'startTime',
            classes: 'text-center',
          },
        ],
      },
    ],

    data: [
      {
        businessTransaction: 'Dashboard Service/Req',
        startTime: '07:09(03/24/20)',
      },
      {
        businessTransaction: 'Dashboard Service/Req',
        startTime: '07:09(03/24/20)',
      },
      {
        businessTransaction: 'Dashboard1 Service/Req',
        startTime: '07:09(03/24/20)',
      },
      {
        businessTransaction: 'Dashboard Service/Req',
        startTime: '07:09(03/24/20)',
      },
      {
        businessTransaction: 'Dashboard Service/Req',
        startTime: '07:09(03/24/20)',
      },
      {
        businessTransaction: 'Dashboard Service/Req',
        startTime: '07:09(03/24/20)',
      },
      {
        businessTransaction: 'Dashboard Service/Req',
        startTime: '07:09(03/24/20)',
      },
      {
        businessTransaction: 'Dashboard Service/Req',
        startTime: '07:09(03/24/20)',
      },
      {
        businessTransaction: 'Dashboard Service/Req',
        startTime: '07:09(03/24/20)',
      },
      {
        businessTransaction: 'Dashboard Service/Req',
        startTime: '07:09(03/24/20)',
      },
      {
        businessTransaction: 'Dashboard Service/Req',
        startTime: '07:09(03/24/20)',
      },
      {
        businessTransaction: 'Dashboard Service/Req',
        startTime: '07:09(03/24/20)',
      },
      {
        businessTransaction: 'Dashboard Service/Req',
        startTime: '07:09(03/24/20)',
      },
      {
        businessTransaction: 'Dashboard Service/Req',
        startTime: '07:09(03/24/20)',
      },
      {
        businessTransaction: 'Dashboard Service/Req',
        startTime: '07:09(03/24/20)',
      },
    ],
  },
  nodeInfoData: {
    node: [
      {
        id: '1',
        type: 'cluster',
        // left: 58.5392,
        // top: 6.59954,
        tier: 'tier',
        server: 'server',
        instance: 'instance',
        startTime: '02/05/2020',
        totalDuration: '20/2/20',
        percentage: '20%',
        nodeName: 'Entry',
        calls: 15,
        rspTime: 1700,
        icon: '',
        serverHealthMajorCircum: 100,
        serverHealthCriticalCircum: 60,
      },
      {
        id: '2',
        type: 'nodeIndices',
        // left: 289.246,
        // top: 2.74217,
        tier: 'tier',
        server: 'server',
        instance: 'instance',
        startTime: '02/05/2020',
        totalDuration: '20/2/20',
        percentage: '20%',
        nodeName: 'Cav23',
        calls: 15,
        rspTime: 1700,
        icon: './assets/icons8-png/icons8-java-100.png',
        serverHealthMajorCircum: 0,
        serverHealthCriticalCircum: 10,
      },
      {
        id: '3',
        type: 'nodeIndices',
        // left: 693.116,
        // top: -171.204,
        tier: 'tier',
        server: 'server',
        instance: '25%',
        startTime: '02/05/2020',
        totalDuration: '20/2/20',
        percentage: '20%',
        nodeName: 'Cav23: Instance 1',
        calls: 15,
        rspTime: 1700,
        icon: './assets/icons8-png/icons8-java-100.png',
        serverHealthMajorCircum: 10,
        serverHealthCriticalCircum: 60,
      },
      {
        id: '4',
        type: 'nodeIndices',
        // left: 693.116,
        // top: -171.204,
        tier: 'tier',
        server: 'server',
        instance: '25%',
        startTime: '02/05/2020',
        totalDuration: '20/2/20',
        percentage: '20%',
        nodeName: 'Cav23: Instance 1',
        calls: 15,
        rspTime: 1700,
        icon: './assets/icons8-png/icons8-java-100.png',
        serverHealthMajorCircum: 0,
        serverHealthCriticalCircum: 60,
      },
      {
        id: '5',
        type: 'nodeIndices',
        // left: 693.116,
        // top: -171.204,
        tier: 'tier',
        server: 'server',
        instance: '25%',
        startTime: '02/05/2020',
        totalDuration: '20/2/20',
        percentage: '20%',
        nodeName: 'Cav23: Instance 1',
        calls: 15,
        rspTime: 1700,
        icon: './assets/icons8-png/icons8-java-100.png',
        serverHealthMajorCircum: 20,
        serverHealthCriticalCircum: 60,
      },
      {
        id: '6',
        type: 'nodeIndices',
        // left: 693.116,
        // top: -171.204,
        tier: 'tier',
        server: 'server',
        instance: '25%',
        startTime: '02/05/2020',
        totalDuration: '20/2/20',
        percentage: '20%',
        nodeName: 'Cav23: Instance 1',
        calls: 15,
        rspTime: 1700,
        icon: './assets/icons8-png/icons8-java-100.png',
        serverHealthMajorCircum: 0,
        serverHealthCriticalCircum: 0,
      },
      {
        id: '7',
        type: 'nodeIndices',
        // left: 693.116,
        // top: -171.204,
        tier: 'tier',
        server: 'server',
        instance: '25%',
        startTime: '02/05/2020',
        totalDuration: '20/2/20',
        percentage: '20%',
        nodeName: 'Cav23: Instance 1',
        calls: 15,
        rspTime: 1700,
        icon: './assets/icons8-png/icons8-java-100.png',
        serverHealthMajorCircum: 0,
        serverHealthCriticalCircum: 60,
      },
      {
        id: '8',
        type: 'nodeIndices',
        // left: 693.116,
        // top: -171.204,
        tier: 'tier',
        server: 'server',
        instance: '25%',
        startTime: '02/05/2020',
        totalDuration: '20/2/20',
        percentage: '20%',
        nodeName: 'Cav23: Instance 1',
        calls: 15,
        rspTime: 1700,
        icon: './assets/icons8-png/icons8-java-100.png',
        serverHealthMajorCircum: 100,
        serverHealthCriticalCircum: 60,
      },
      {
        id: '9',
        type: 'nodeIndices',
        // left: 693.116,
        // top: -171.204,
        tier: 'tier',
        server: 'server',
        instance: '25%',
        startTime: '02/05/2020',
        totalDuration: '20/2/20',
        percentage: '20%',
        nodeName: 'Cav23: Instance 1',
        calls: 15,
        rspTime: 1700,
        icon: './assets/icons8-png/icons8-java-100.png',
        serverHealthMajorCircum: 100,
        serverHealthCriticalCircum: 60,
      },
      {
        id: '10',
        type: 'nodeIndices',
        // left: 693.116,
        // top: -171.204,
        tier: 'tier',
        server: 'server',
        instance: '25%',
        startTime: '02/05/2020',
        totalDuration: '20/2/20',
        percentage: '20%',
        nodeName: 'Cav23: Instance 1',
        calls: 15,
        rspTime: 1700,
        icon: './assets/icons8-png/icons8-java-100.png',
        serverHealthMajorCircum: 100,
        serverHealthCriticalCircum: 60,
      },
      {
        id: '11',
        type: 'nodeIndices',
        // left: 693.116,
        // top: -171.204,
        tier: 'tier',
        server: 'server',
        instance: '25%',
        startTime: '02/05/2020',
        totalDuration: '20/2/20',
        percentage: '20%',
        nodeName: 'Cav23: Instance 1',
        calls: 15,
        rspTime: 1700,
        icon: './assets/icons8-png/icons8-java-100.png',
        serverHealthMajorCircum: 100,
        serverHealthCriticalCircum: 60,
      },
      {
        id: '12',
        type: 'nodeIndices',
        // left: 693.116,
        // top: -171.204,
        tier: 'tier',
        server: 'server',
        instance: '25%',
        startTime: '02/05/2020',
        totalDuration: '20/2/20',
        percentage: '20%',
        nodeName: 'Cav23: Instance 1',
        calls: 15,
        rspTime: 1700,
        icon: './assets/icons8-png/icons8-java-100.png',
        serverHealthMajorCircum: 100,
        serverHealthCriticalCircum: 60,
      },
      {
        id: '13',
        type: 'lastLevelNodeIndices',
        tier: 'tier',
        server: 'server',
        instance: '25%',
        startTime: '02/05/2020',
        totalDuration: '20/2/20',
        percentage: '20%',
        nodeName: 'Cav23: Instance 1',
        calls: 15,
        rspTime: 1700,
        icon: './assets/icons8-png/icons8-java-100.png',
        serverHealthMajorCircum: 100,
        serverHealthCriticalCircum: 60,
      },
      {
        id: '14',
        type: 'lastLevelNodeIndices',
        tier: 'tier',
        server: 'server',
        instance: '25%',
        startTime: '02/05/2020',
        totalDuration: '20/2/20',
        percentage: '20%',
        nodeName: 'Cav23: Instance 1',
        calls: 15,
        rspTime: 1700,
        icon: './assets/icons8-png/icons8-java-100.png',
        serverHealthMajorCircum: 100,
        serverHealthCriticalCircum: 60,
      },
    ],
    edge: [
      { source: '1', target: '2', data: { type: 'outputEdgeLabel', index: '1', rspTime: '1700ms', calls: '15', putMyLabelAt: 0.5, } },
      {
        source: '2', target: '3', data: {
          type: 'outputEdgeLabel',
          tier: 'tier',
          server: 'server',
          instance: '25%',
          startTime: '02/05/2020',
          totalDuration: '20/2/20',
          percentage: '20%', index: '1', rspTime: '1700ms', calls: '15', putMyLabelAt: 0.9
        }
      },
      {
        source: '2', target: '4', data: {
          type: 'outputEdgeLabel', tier: 'tier',
          server: 'server',
          instance: '25%',
          startTime: '02/05/2020',
          totalDuration: '20/2/20',
          percentage: '20%', index: '1', rspTime: '1700ms', calls: '15', putMyLabelAt: 0.9
        }
      },
      {
        source: '2', target: '5', data: {
          type: 'outputEdgeLabel', tier: 'tier',
          server: 'server',
          instance: '25%',
          startTime: '02/05/2020',
          totalDuration: '20/2/20',
          percentage: '20%', index: '1', rspTime: '1700ms', calls: '15', putMyLabelAt: 0.8
        }
      },
      {
        source: '2', target: '6', data: {
          type: 'outputEdgeLabel', tier: 'tier',
          server: 'server',
          instance: '25%',
          startTime: '02/05/2020',
          totalDuration: '20/2/20',
          percentage: '20%', index: '1', rspTime: '1700ms', calls: '15', putMyLabelAt: 0.8
        }
      },
      {
        source: '2', target: '7', data: {
          type: 'outputEdgeLabel', tier: 'tier',
          server: 'server',
          instance: '25%',
          startTime: '02/05/2020',
          totalDuration: '20/2/20',
          bt:'bjdsfsdfdsfdsf',
          error:'jnjnkn',
          percentage: '20%', index: '1', rspTime: '1700ms', calls: '15', putMyLabelAt: 0.8
        }
      },
      {
        source: '2', target: '8', data: {
          type: 'outputEdgeLabel', tier: 'tier',
          server: 'server',
          instance: '25%',
          startTime: '02/05/2020',
          totalDuration: '20/2/20',
          percentage: '20%', index: '1', rspTime: '1700ms', calls: '15', putMyLabelAt: 0.8
        }
      },
      {
        source: '2', target: '9', data: {
          type: 'outputEdgeLabel', tier: 'tier',
          server: 'server',
          instance: '25%',
          startTime: '02/05/2020',
          totalDuration: '20/2/20',
          percentage: '20%', index: '1', rspTime: '1700ms', calls: '15', putMyLabelAt: 0.8
        }
      },
      { source: '2', target: '10', data: { type: 'outputEdgeLabel', index: '1', rspTime: '1700ms', calls: '15', putMyLabelAt: 0.8 } },
      { source: '2', target: '11', data: { type: 'outputEdgeLabel', index: '1', rspTime: '1700ms', calls: '15', putMyLabelAt: 0.8 } },
      { source: '2', target: '12', data: { type: 'outputEdgeLabel', index: '1', rspTime: '1700ms', calls: '15', putMyLabelAt: 0.9 } },
      { source: '12', target: '12', data: { type: 'outputEdgeLabel', index: '1', rspTime: '1700ms', calls: '15', putMyLabelAt: 0.9 } },
      { source: '3', target: '13', data: { type: 'outputEdgeLabel', index: '1', rspTime: '1700ms', calls: '15', putMyLabelAt: 0.5 } },
      { source: '4', target: '14', data: { type: 'outputEdgeLabel', index: '1', rspTime: '1700ms', calls: '15', putMyLabelAt: 0.5 } },
    ],
  }
};

export const TRANSACTION_FLOWMAP_CHART: TransactionFlowmapChart = {
  charts: [
    {
      title: 'All Requests/sec',
      highchart: {
        chart: {
          type: 'column',
          height: '180px',
        },
        title: {
          align: 'left',
          text:
            '<span style="font-size: 14px;float:left">Total Predicted Order vs Actual Order</span>',
        },
        xAxis: {
          categories: ['Jan', 'Feb', 'Mar', 'Apr'],
          labels: {
            enabled: false,
          },
          crosshair: true,
        },
        yAxis: {
          min: 0,
          title: {
            text: '',
          },
          labels: {
            enabled: false,
          },
        },
        tooltip: {
          headerFormat:
            '<span style="font-size:10px">{point.key}</span><table>',
          pointFormat:
            '<tr><td style="color:{series.color};padding:0">{series.name}: </td>' +
            '<td style="padding:0"><b>{point.y:.1f} mm</b></td></tr>',
          footerFormat: '</table>',
          shared: true,
          useHTML: true,
        },
        plotOptions: {
          column: {
            pointPadding: 0.2,
            borderWidth: 0,
          },
        },
        legend: {
          layout: 'vertical',
          align: 'right',
          enabled: true,
          verticalAlign: 'top',
          x: 0,
          y: 0,
          itemMarginBottom: 5,
          symbolRadius: 0,
          symbolHeight: 15,
          symbolWidth: 15,
        },
        series: [
          {
            name: 'Tokyo',
            data: [49.9, 71.5, 106.4, 129.2],
          },
          {
            name: 'New York',
            data: [83.6, 78.8, 98.5, 93.4],
          },
        ] as Highcharts.SeriesOptionsType[],
      },
    },
    {
      title: 'All Requests/sec',
      highchart: {
        chart: {
          type: 'spline',
          height: '200px',
        },

        title: {
          text: null,
        },

        xAxis: {
          categories: ['00.05', '00.10.', '00.15', '00.20', '0.25'],
        },
        yAxis: {
          title: {
            text: '',
          },
        },
        plotOptions: {
          line: {
            dataLabels: {
              enabled: false,
            },
            enableMouseTracking: false,
          },
        },
        series: [
          {
            name: '',
            data: [17.0, 10.5, 18.4, 9.3, 16.9, 10.4, 17.5],
          },
          {
            name: '',
            data: [15.0, 8.5, 16.4, 7.3, 14.9, 8.4, 15.5],
          },
          {
            name: '',
            data: [13.0, 6.5, 14.4, 5.3, 12.9, 6.4, 13.5],
          },
          {
            name: '',
            data: [11.0, 4.5, 12.4, 3.3, 10.9, 4.4, 11.5],
          },
          {
            name: '',
            data: [9.0, 2.5, 10.4, 1.3, 8.9, 2.4, 9.5],
          },
        ] as Highcharts.SeriesOptionsType[],
      },
    },
    {
      title: 'All Requests/sec',
      highchart: {
        chart: {
          height: '250px',
        },
        title: {
          text: null,
        },
        legend: {
          enabled: true,
          align: 'right',
          verticalAlign: 'middle',
          x: 0,
          y: 0,
          layout: 'vertical',
          itemStyle: {
            width: 70,
            color: '#333333',
            fontFamily: 'Product Sans',
            fontSize: '11px',
          },
        },
        xAxis: {
          allowDecimals: false,
          accessibility: {
            rangeDescription: 'Range: 1940 to 2017.',
          },
        },
        yAxis: {
          title: {
            text: 'Average Wait Time(ms)',
          },
        },
        tooltip: {
          pointFormat:
            '{series.name} had stockpiled <b>{point.y:,.0f}</b><br/>warheads in {point.x}',
        },
        plotOptions: {
          series: {
            pointStart: 1940,
            marker: {
              enabled: false,
              symbol: 'circle',
              radius: 2,
              states: {
                hover: {
                  enabled: true,
                },
              },
            },
          },
        },
        series: [
          {
            name: 'USA',
            type: 'area',
            data: [
              null,
              null,
              null,
              null,
              null,
              6,
              11,
              32,
              110,
              235,
              369,
              640,
              1005,
              1436,
              2063,
              3057,
              4618,
              6444,
              9822,
              15468,
              20434,
              24126,
              27387,
              29459,
              31056,
              31982,
              32040,
              31233,
              29224,
              27342,
              26662,
              26956,
              27912,
              28999,
              28965,
              27826,
              25579,
              25722,
              24826,
              24605,
              24304,
              23464,
              23708,
              24099,
              24357,
              24237,
              24401,
              24344,
              23586,
              22380,
              21004,
              17287,
              14747,
              13076,
              12555,
              12144,
              11009,
              10950,
              10871,
              10824,
              10577,
              10527,
              10475,
              10421,
              10358,
              10295,
              10104,
              9914,
              9620,
              9326,
              5113,
              5113,
              4954,
              4804,
              4761,
              4717,
              4368,
              4018,
            ],
          },
          {
            name: 'USSR/Russia',
            type: 'area',
            data: [
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              5,
              25,
              50,
              120,
              150,
              200,
              426,
              660,
              869,
              1060,
              1605,
              2471,
              3322,
              4238,
              5221,
              6129,
              7089,
              8339,
              9399,
              10538,
              11643,
              13092,
              14478,
              15915,
              17385,
              19055,
              21205,
              23044,
              25393,
              27935,
              30062,
              32049,
              33952,
              35804,
              37431,
              39197,
              45000,
              43000,
              41000,
              39000,
              37000,
              35000,
              33000,
              31000,
              29000,
              27000,
              25000,
              24000,
              23000,
              22000,
              21000,
              20000,
              19000,
              18000,
              18000,
              17000,
              16000,
              15537,
              14162,
              12787,
              12600,
              11400,
              5500,
              4512,
              4502,
              4502,
              4500,
              4500,
            ],
          },
        ] as Highcharts.SeriesOptionsType[],
      },
    },
    {
      title: 'All Requests/sec',
      highchart: {
        chart: {
          type: 'column',
          height: '180px',
        },
        title: {
          align: 'left',
          text:
            '<span style="font-size: 14px;float:left">Total Predicted Order vs Actual Order</span>',
        },
        xAxis: {
          categories: ['Jan', 'Feb', 'Mar', 'Apr'],
          labels: {
            enabled: false,
          },
          crosshair: true,
        },
        yAxis: {
          min: 0,
          title: {
            text: '',
          },
          labels: {
            enabled: false,
          },
        },
        tooltip: {
          enabled:false,
          headerFormat:
            '<span style="font-size:10px">{point.key}</span><table>',
          pointFormat:
            '<tr><td style="color:{series.color};padding:0">{series.name}: </td>' +
            '<td style="padding:0"><b>{point.y:.1f} mm</b></td></tr>',
          footerFormat: '</table>',
          shared: true,
          useHTML: true,
        },
        plotOptions: {
          column: {
            pointPadding: 0.2,
            borderWidth: 0,
          },
        },
        legend: {
          layout: 'vertical',
          align: 'right',
          enabled: true,
          verticalAlign: 'top',
          x: 0,
          y: 0,
          itemMarginBottom: 5,
          symbolRadius: 0,
          symbolHeight: 15,
          symbolWidth: 15,
        },
        series: [
          {
            name: 'Tokyo',
            data: [49.9, 71.5, 106.4, 129.2],
          },
          {
            name: 'New York',
            data: [83.6, 78.8, 98.5, 93.4],
          },
        ] as Highcharts.SeriesOptionsType[],
      },
    },
    {
      title: 'All Requests/sec',
      highchart: {
        chart: {
          type: 'spline',
          height: '200px',
        },

        title: {
          text: null,
        },

        xAxis: {
          categories: ['00.05', '00.10.', '00.15', '00.20', '0.25'],
        },
        yAxis: {
          title: {
            text: '',
          },
        },
        plotOptions: {
          line: {
            dataLabels: {
              enabled: false,
            },
            enableMouseTracking: false,
          },
        },
        series: [
          {
            name: '',
            data: [17.0, 10.5, 18.4, 9.3, 16.9, 10.4, 17.5],
          },
          {
            name: '',
            data: [15.0, 8.5, 16.4, 7.3, 14.9, 8.4, 15.5],
          },
          {
            name: '',
            data: [13.0, 6.5, 14.4, 5.3, 12.9, 6.4, 13.5],
          },
          {
            name: '',
            data: [11.0, 4.5, 12.4, 3.3, 10.9, 4.4, 11.5],
          },
          {
            name: '',
            data: [9.0, 2.5, 10.4, 1.3, 8.9, 2.4, 9.5],
          },
        ] as Highcharts.SeriesOptionsType[],
      },
    },
    {
      title: 'All Requests/sec',
      highchart: {
        chart: {
          height: '250px',
        },
        title: {
          text: null,
        },
        legend: {
          enabled: true,
          align: 'right',
          verticalAlign: 'middle',
          x: 0,
          y: 0,
          layout: 'vertical',
          itemStyle: {
            width: 70,
            color: '#333333',
            fontFamily: 'Product Sans',
            fontSize: '11px',
          },
        },
        xAxis: {
          allowDecimals: false,
          accessibility: {
            rangeDescription: 'Range: 1940 to 2017.',
          },
        },
        yAxis: {
          title: {
            text: 'Average Wait Time(ms)',
          },
        },
        tooltip: {
          pointFormat:
            '{series.name} had stockpiled <b>{point.y:,.0f}</b><br/>warheads in {point.x}',
        },
        plotOptions: {
          series: {
            pointStart: 1940,
            marker: {
              enabled: false,
              symbol: 'circle',
              radius: 2,
              states: {
                hover: {
                  enabled: true,
                },
              },
            },
          },
        },
        series: [
          {
            name: 'USA',
            type: 'area',
            data: [
              null,
              null,
              null,
              null,
              null,
              6,
              11,
              32,
              110,
              235,
              369,
              640,
              1005,
              1436,
              2063,
              3057,
              4618,
              6444,
              9822,
              15468,
              20434,
              24126,
              27387,
              29459,
              31056,
              31982,
              32040,
              31233,
              29224,
              27342,
              26662,
              26956,
              27912,
              28999,
              28965,
              27826,
              25579,
              25722,
              24826,
              24605,
              24304,
              23464,
              23708,
              24099,
              24357,
              24237,
              24401,
              24344,
              23586,
              22380,
              21004,
              17287,
              14747,
              13076,
              12555,
              12144,
              11009,
              10950,
              10871,
              10824,
              10577,
              10527,
              10475,
              10421,
              10358,
              10295,
              10104,
              9914,
              9620,
              9326,
              5113,
              5113,
              4954,
              4804,
              4761,
              4717,
              4368,
              4018,
            ],
          },
          {
            name: 'USSR/Russia',
            type: 'area',
            data: [
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              5,
              25,
              50,
              120,
              150,
              200,
              426,
              660,
              869,
              1060,
              1605,
              2471,
              3322,
              4238,
              5221,
              6129,
              7089,
              8339,
              9399,
              10538,
              11643,
              13092,
              14478,
              15915,
              17385,
              19055,
              21205,
              23044,
              25393,
              27935,
              30062,
              32049,
              33952,
              35804,
              37431,
              39197,
              45000,
              43000,
              41000,
              39000,
              37000,
              35000,
              33000,
              31000,
              29000,
              27000,
              25000,
              24000,
              23000,
              22000,
              21000,
              20000,
              19000,
              18000,
              18000,
              17000,
              16000,
              15537,
              14162,
              12787,
              12600,
              11400,
              5500,
              4512,
              4502,
              4502,
              4500,
              4500,
            ],
          },
        ] as Highcharts.SeriesOptionsType[],
      },
    },
  ],
};
