import { postgressStatsTable, VisualChart } from "./postgress-stats.model";


export const POSTGRESS_STATS_TABLE: postgressStatsTable = {
    statsBasedOnDatabase: {
        paginator: {
            first: 1,
            rows: 10,
            rowsPerPageOptions: [10, 25, 50, 100],
        },

        headers: [
            {
                cols: [
                    {
                        label: 'Database Name',
                        valueField: 'databaseName',
                        classes: 'text-left',
                        selected: true,
                        filter: {
                            isFilter: true,
                            type: 'contains',
                        },
                        isSort: true,
                    },
                    {
                        label: 'Used',
                        valueField: 'used',
                        classes: 'text-left',
                        selected: true,
                        filter: {
                            isFilter: true,
                            type: 'contains',
                        },
                        isSort: true,
                    },
                    {
                        label: 'Active',
                        valueField: 'active',
                        classes: 'text-left',
                        selected: true,
                        filter: {
                            isFilter: true,
                            type: 'contains',
                        },
                        isSort: true,
                    },
                    {
                        label: 'Idle',
                        valueField: 'idle',
                        classes: 'text-left',
                        selected: true,
                        filter: {
                            isFilter: true,
                            type: 'contains',
                        },
                        isSort: true,
                    },
                    {
                        label: 'Idle in Transaction',
                        valueField: 'idleInTransaction',
                        classes: 'text-left',
                        selected: true,
                        filter: {
                            isFilter: true,
                            type: 'contains',
                        },
                        isSort: true,
                    },
                    {
                        label: 'Idle in Transaction (Aborted)',
                        valueField: 'idleInAborted',
                        classes: 'text-left',
                        selected: true,
                        filter: {
                            isFilter: true,
                            type: 'contains',
                        },
                        isSort: true,
                    },
                    {
                        label: 'Fastpath Function Call',
                        valueField: 'fastpathFuntion',
                        classes: 'text-left',
                        selected: true,
                        filter: {
                            isFilter: true,
                            type: 'contains',
                        },
                        isSort: true,
                    },
                    {
                        label: 'Disabled',
                        valueField: 'disabled',
                        classes: 'text-left',
                        selected: true,
                        filter: {
                            isFilter: true,
                            type: 'contains',
                        },
                        isSort: true,
                    },
                    {
                        label: 'Blank',
                        valueField: 'blank',
                        classes: 'text-left',
                        selected: true,
                        filter: {
                            isFilter: true,
                            type: 'contains',
                        },
                        isSort: true,
                    },
                ],
            },
        ],
        data: [
            {
                databaseName: 'access_control_NC',
                used: '1',
                active: '0',
                idle: '1',
                idleInTransaction: '0',
                idleInAborted: '0',
                fastpathFuntion: '0',
                disabled: '0',
                blank: '0',
            },
            {
                databaseName: 'test',
                used: '170',
                active: '2',
                idle: '168',
                idleInTransaction: '0',
                idleInAborted: '0',
                fastpathFuntion: '0',
                disabled: '0',
                blank: '0',
            },
            {
                databaseName: 'access_control',
                used: '3',
                active: '0',
                idle: '2',
                idleInTransaction: '1',
                idleInAborted: '0',
                fastpathFuntion: '0',
                disabled: '0',
                blank: '0',
            },
            {
                databaseName: 'access_control_Netvision',
                used: '3',
                active: '0',
                idle: '0',
                idleInTransaction: '3',
                idleInAborted: '0',
                fastpathFuntion: '0',
                disabled: '0',
                blank: '0',
            },
            {
                databaseName: 'access_control_NC',
                used: '1',
                active: '0',
                idle: '1',
                idleInTransaction: '0',
                idleInAborted: '0',
                fastpathFuntion: '0',
                disabled: '0',
                blank: '0',
            },
            {
                databaseName: 'postgress',
                used: '12',
                active: '0',
                idle: '12',
                idleInTransaction: '0',
                idleInAborted: '0',
                fastpathFuntion: '0',
                disabled: '0',
                blank: '0',
            },
            {
                databaseName: 'access_control_NC',
                used: '1',
                active: '0',
                idle: '1',
                idleInTransaction: '0',
                idleInAborted: '0',
                fastpathFuntion: '0',
                disabled: '0',
                blank: '0',
            },
            {
                databaseName: 'access_control_NC',
                used: '1',
                active: '0',
                idle: '1',
                idleInTransaction: '0',
                idleInAborted: '0',
                fastpathFuntion: '0',
                disabled: '0',
                blank: '0',
            },
            {
                databaseName: 'access_control_NC',
                used: '1',
                active: '0',
                idle: '1',
                idleInTransaction: '0',
                idleInAborted: '0',
                fastpathFuntion: '0',
                disabled: '0',
                blank: '0',
            },
            {
                databaseName: 'access_control_NC',
                used: '1',
                active: '0',
                idle: '1',
                idleInTransaction: '0',
                idleInAborted: '0',
                fastpathFuntion: '0',
                disabled: '0',
                blank: '0',
            },
            {
                databaseName: 'access_control_NC',
                used: '1',
                active: '0',
                idle: '1',
                idleInTransaction: '0',
                idleInAborted: '0',
                fastpathFuntion: '0',
                disabled: '0',
                blank: '0',
            },
            {
                databaseName: 'access_control_NC',
                used: '1',
                active: '0',
                idle: '1',
                idleInTransaction: '0',
                idleInAborted: '0',
                fastpathFuntion: '0',
                disabled: '0',
                blank: '0',
            },
            {
                databaseName: 'access_control_NC',
                used: '1',
                active: '0',
                idle: '1',
                idleInTransaction: '0',
                idleInAborted: '0',
                fastpathFuntion: '0',
                disabled: '0',
                blank: '0',
            },
            {
                databaseName: 'access_control_NC',
                used: '1',
                active: '0',
                idle: '1',
                idleInTransaction: '0',
                idleInAborted: '0',
                fastpathFuntion: '0',
                disabled: '0',
                blank: '0',
            },
            {
                databaseName: 'access_control_NC',
                used: '1',
                active: '0',
                idle: '1',
                idleInTransaction: '0',
                idleInAborted: '0',
                fastpathFuntion: '0',
                disabled: '0',
                blank: '0',
            },
            {
                databaseName: 'access_control_NC',
                used: '1',
                active: '0',
                idle: '1',
                idleInTransaction: '0',
                idleInAborted: '0',
                fastpathFuntion: '0',
                disabled: '0',
                blank: '0',
            },
            {
                databaseName: 'access_control_NC',
                used: '1',
                active: '0',
                idle: '1',
                idleInTransaction: '0',
                idleInAborted: '0',
                fastpathFuntion: '0',
                disabled: '0',
                blank: '0',
            },
            {
                databaseName: 'access_control_NC',
                used: '1',
                active: '0',
                idle: '1',
                idleInTransaction: '0',
                idleInAborted: '0',
                fastpathFuntion: '0',
                disabled: '0',
                blank: '0',
            },

        ],
    },

    statsBasedOnApplication: {
        paginator: {
            first: 1,
            rows: 10,
            rowsPerPageOptions: [10, 25, 50, 100],
        },

        headers: [
            {
                cols: [
                    {
                        label: 'Database Name',
                        valueField: 'databaseName',
                        classes: 'text-left',
                        selected: true,
                        filter: {
                            isFilter: true,
                            type: 'contains',
                        },
                        isSort: true,
                    },
                    {
                        label: 'Used',
                        valueField: 'used',
                        classes: 'text-left',
                        selected: true,
                        filter: {
                            isFilter: true,
                            type: 'contains',
                        },
                        isSort: true,
                    },
                    {
                        label: 'Active',
                        valueField: 'active',
                        classes: 'text-left',
                        selected: true,
                        filter: {
                            isFilter: true,
                            type: 'contains',
                        },
                        isSort: true,
                    },
                    {
                        label: 'Idle',
                        valueField: 'idle',
                        classes: 'text-left',
                        selected: true,
                        filter: {
                            isFilter: true,
                            type: 'contains',
                        },
                        isSort: true,
                    },
                    {
                        label: 'Idle in Transaction',
                        valueField: 'idleInTransaction',
                        classes: 'text-left',
                        selected: true,
                        filter: {
                            isFilter: true,
                            type: 'contains',
                        },
                        isSort: true,
                    },
                    {
                        label: 'Idle in Transaction (Aborted)',
                        valueField: 'idleInAborted',
                        classes: 'text-left',
                        selected: true,
                        filter: {
                            isFilter: true,
                            type: 'contains',
                        },
                        isSort: true,
                    },
                    {
                        label: 'Fastpath Function Call',
                        valueField: 'fastpathFuntion',
                        classes: 'text-left',
                        selected: true,
                        filter: {
                            isFilter: true,
                            type: 'contains',
                        },
                        isSort: true,
                    },
                    {
                        label: 'Disabled',
                        valueField: 'disabled',
                        classes: 'text-left',
                        selected: true,
                        filter: {
                            isFilter: true,
                            type: 'contains',
                        },
                        isSort: true,
                    },
                    {
                        label: 'Blank',
                        valueField: 'blank',
                        classes: 'text-left',
                        selected: true,
                        filter: {
                            isFilter: true,
                            type: 'contains',
                        },
                        isSort: true,
                    },
                ],
            },
        ],
        data: [
            {
                databaseName: 'access_control_NC',
                used: '1',
                active: '0',
                idle: '1',
                idleInTransaction: '0',
                idleInAborted: '0',
                fastpathFuntion: '0',
                disabled: '0',
                blank: '0',
            },
            {
                databaseName: 'test',
                used: '170',
                active: '2',
                idle: '168',
                idleInTransaction: '0',
                idleInAborted: '0',
                fastpathFuntion: '0',
                disabled: '0',
                blank: '0',
            },
            {
                databaseName: 'access_control',
                used: '3',
                active: '0',
                idle: '2',
                idleInTransaction: '1',
                idleInAborted: '0',
                fastpathFuntion: '0',
                disabled: '0',
                blank: '0',
            },
            {
                databaseName: 'access_control_Netvision',
                used: '3',
                active: '0',
                idle: '0',
                idleInTransaction: '3',
                idleInAborted: '0',
                fastpathFuntion: '0',
                disabled: '0',
                blank: '0',
            },
            {
                databaseName: 'access_control_NC',
                used: '1',
                active: '0',
                idle: '1',
                idleInTransaction: '0',
                idleInAborted: '0',
                fastpathFuntion: '0',
                disabled: '0',
                blank: '0',
            },
            {
                databaseName: 'postgress',
                used: '12',
                active: '0',
                idle: '12',
                idleInTransaction: '0',
                idleInAborted: '0',
                fastpathFuntion: '0',
                disabled: '0',
                blank: '0',
            },
            {
                databaseName: 'access_control_NC',
                used: '1',
                active: '0',
                idle: '1',
                idleInTransaction: '0',
                idleInAborted: '0',
                fastpathFuntion: '0',
                disabled: '0',
                blank: '0',
            },
            {
                databaseName: 'access_control_NC',
                used: '1',
                active: '0',
                idle: '1',
                idleInTransaction: '0',
                idleInAborted: '0',
                fastpathFuntion: '0',
                disabled: '0',
                blank: '0',
            },
            {
                databaseName: 'access_control_NC',
                used: '1',
                active: '0',
                idle: '1',
                idleInTransaction: '0',
                idleInAborted: '0',
                fastpathFuntion: '0',
                disabled: '0',
                blank: '0',
            },
            {
                databaseName: 'access_control_NC',
                used: '1',
                active: '0',
                idle: '1',
                idleInTransaction: '0',
                idleInAborted: '0',
                fastpathFuntion: '0',
                disabled: '0',
                blank: '0',
            },
            {
                databaseName: 'access_control_NC',
                used: '1',
                active: '0',
                idle: '1',
                idleInTransaction: '0',
                idleInAborted: '0',
                fastpathFuntion: '0',
                disabled: '0',
                blank: '0',
            },
            {
                databaseName: 'access_control_NC',
                used: '1',
                active: '0',
                idle: '1',
                idleInTransaction: '0',
                idleInAborted: '0',
                fastpathFuntion: '0',
                disabled: '0',
                blank: '0',
            },
            {
                databaseName: 'access_control_NC',
                used: '1',
                active: '0',
                idle: '1',
                idleInTransaction: '0',
                idleInAborted: '0',
                fastpathFuntion: '0',
                disabled: '0',
                blank: '0',
            },
            {
                databaseName: 'access_control_NC',
                used: '1',
                active: '0',
                idle: '1',
                idleInTransaction: '0',
                idleInAborted: '0',
                fastpathFuntion: '0',
                disabled: '0',
                blank: '0',
            },
            {
                databaseName: 'access_control_NC',
                used: '1',
                active: '0',
                idle: '1',
                idleInTransaction: '0',
                idleInAborted: '0',
                fastpathFuntion: '0',
                disabled: '0',
                blank: '0',
            },
            {
                databaseName: 'access_control_NC',
                used: '1',
                active: '0',
                idle: '1',
                idleInTransaction: '0',
                idleInAborted: '0',
                fastpathFuntion: '0',
                disabled: '0',
                blank: '0',
            },
            {
                databaseName: 'access_control_NC',
                used: '1',
                active: '0',
                idle: '1',
                idleInTransaction: '0',
                idleInAborted: '0',
                fastpathFuntion: '0',
                disabled: '0',
                blank: '0',
            },
            {
                databaseName: 'access_control_NC',
                used: '1',
                active: '0',
                idle: '1',
                idleInTransaction: '0',
                idleInAborted: '0',
                fastpathFuntion: '0',
                disabled: '0',
                blank: '0',
            },

        ],
    },
};


export const PANEL_DUMMY: any = {
    panels: [
        { label: '', collapsed: false },
        { label: '', collapsed: false },
    ],
};


export const VISUAL_CHART_DATA: VisualChart = 
    {
        charts: [
            {
                title: 'Postgress Stats',
                highchart: {
               
                    chart: {
                        height:'200px',
                        type: 'pie'
                    },
                    title: null,
                    tooltip: {
                        pointFormat: '{series.name}: <b>{point.percentage:.1f}%</b>',
                    },
                    plotOptions: {
                        pie: {
                            size: '100%',
                            borderWidth: 0,
                            dataLabels: {
                                enabled: false,
                                format: '<b>{point.percentage:.1f} %',
                            },
                            showInLegend: true
                        },
                    },
                    series: [
                        {
                            name: 'Stats',
                            colorByPoint: true,
                            data: [
                                {
                                    name: 'Used',
                                    y: 40,
                                },
                                {
                                    name: 'Reserved',
                                    y: 23,
                                },
                                {
                                    name: 'Available',
                                    y: 10,
                                }
                            ],
                        },
                    ] as Highcharts.SeriesOptionsType[],
                },
            
            },
        ],
    };