export const TAB_CHANGE_EVENT_ROLE = 'TABCNGEVNTR';
export const TAB_CHANGE_EVENT_USER = 'TABCNGEVNTU';
export const TAB_CHANGE_EVENT_GROUP = 'TABCNGEVNTU';
export const TAB_CHANGE_EVENT_PROJECT = 'TABCNGEVNTP';
export const FEATURE_LIST_AVAILABLE = 'FTRLSTAVLBL';
export const OPEN_ALERT = 'OPALERT'
/* Model Type Action. */
export const MODEL_TYPE_ALERT = 'MTYPEALT';
export const MODEL_ACTION_OK = 'MTACTIONOK';
export const MODEL_ACTION_CANCEL = 'MTACTIONCNL';
export const MODEL_ACTION_CONFIRM = 'MACTCONFRM'
/*CAPABILITY CONSTANTS*/
export const NEW_CAPABILITY_DATA_AVAILABLE = 'NWCPBLDATAAVLBL';
export const CAPABILITY_LIST_AVAILABLE = 'CPBLLSTAVBL';
export const CUSTOM_NEXT_LEVEL_DATA_AVAILABLE = 'CNLDAVBL';
export const CAPABILITY_DELETED_SUCESSFULLY = 'CPBLDELSCFLY';
export const CUSTOM_NEXT_LEVEL_DATA_AVAILABLE_FOR_OLD = 'CNLDAFO';
export const UPDATE_CAPABILTY_DATA_AVAILABLE = 'UPDATECPBAVLBLE';
/*Group Constant*/
export const SAVE_ALL_GROUP_DATA = 'SAVALLGRPDATA';
export const DELETE_GROUPS = 'DELGRPS';
export const GROUP_DATA_AVAILABLE = 'GDAAVLBL';
/*User Constant */
export const SAVE_ALL_USER_DATA = 'SAVALLUSRDATA';
export const DELETE_USERS = 'DELUSRS';
export const USER_DATA_AVAILABLE = 'USDAVLBL';
export const DELETION_UNSUCESSFULL ='DELUNSFL';
export const USER_SESSION_CLOSED_SUCESSFULLY ="USRSESSCLSDSUCCESS"
export const USER_SESSION_CLOSED_UNSUCESSFULLY ="USRSESSCLSDUNSUCCESS"
export const AUDIT_LOG_DATA_AVAILABLE ='AUDTLOGDATAAVLBL';
export const AUDIT_LOG_DATA_SEARCH = 'AUDITLOGDATASEARC';

export const USER_MANAGEMENT = "User Management";
export const GROUP_MANAGEMENT = "Group Management";
export const CAPABILITY_MANAGEMENT = "Capabilities";