export enum ACLErrorCodes {
    ERROR_IN_SAVING_CAPABILITY = 103,
    ERROR_IN_GETTING_CAPABILITY = 104,
    ERROR_IN_CREATING_NEW_CAPABILITY = 105,
    ERROR_IN_GETTING_CUSTOM_TABLE_DATA = 107,
    ERROR_IN_GETTING_SAVED_GROUPS_FROM_DB = 108,
    ERROR_IN_DELETEING_GROUP_FROM_DB = 109,
    ERROR_IN_SAVING_GROUP_DATA_IN_DB = 110,
    ERROR_IN_DELETING_GROUP = 111,
    ERROR_IN_DELETING_CAPABILITY = 111,
    ERROR_IN_CONNECTING_POSTGRES =115
}
