export const ACCESSCONTROLLIST_REST_API_PATH = '/DashboardServer/acl';
//export const CREATE_NEW_ROLE_DATA = '/createNewRole';
export const ADD_NEW_CAPABILITY = '/capability/new';
export const CAPABILITY_DATA_LIST = '/capability/getAll';
export const SAVE_CAPABILITY_DATA = '/capability/save';
export const DELETE_CAPABILITY = '/capability/delete';
export const FEATURE_DATA_LIST = '/getUserObjects';
export const SAVE_USER_OBJECT = '/saveUserObjects';
export const CUSTOM_NEXT_LEVEL_DATA = '/capability/custom';
export const SAVE_ALL_GROUP = '/group/save';
export const DELETE_GROUPS_FROM_DB = '/group/delete';
export const LOAD_DEFAULT_VALUES =  '/group/getAllGroups';
export const SAVE_ALL_USER = '/user/save';
export const DELETE_USERS_FROM_DB = '/user/delete';
export const LOAD_DEFAULT_VALUES_USER =  '/user/getAllUsers';
export const GET_LDAP_GROUP_OF_USER = '/ldap/getGroupsForUser';
export const GET_ALL_LDAP_GROUP = '/ldap/getAllGroupsOfLdap';
export const REMOVE_USER_SESSION = '/user/removeUserSessionOnForcedLogout'
export const LOAD_AUDIT_LOG_DATA ='/auditLog/getDefaultLogs'
export const DOWNLOAD_AUDIT_LOG_DATA ='/auditLog/downloadAuditLogs'
export const LOG_OUT_SESSION ='/user/removeUserSessionOnLogout'
export const REFRESH_CACHE ="/user/refreshDatabase"
export const GET_ALL_NODE_INFO = '/EnterPriseApp/getListOfNodeInfo'; 
