import { NodeQueryData } from './node-query.model';

export const QUERY_DATA: NodeQueryData = {
  queryData: {
    headers: [
      {
        cols: [
          {
            label: 'Indices',
            valueField: 'indices',
            classes: 'text-left',
            selected: true,
            severityColorField: true,
            filter: {
              isFilter: true,
              type: 'contains',
            },
            isSort: true,
          },
          {
            label: 'Type',
            valueField: 'type',
            classes: 'text-left',
            selected: true,
            filter: {
              isFilter: true,
              type: 'contains',
            },
            isSort: true,
          },
          {
            label: 'Score',
            valueField: 'score',
            classes: 'text-left',
            selected: true,
            filter: {
              isFilter: true,
              type: 'contains',
            },
            isSort: false,
            width:'5%'
          },
          {
            label: 'ID',
            valueField: 'id',
            classes: 'text-left',
            selected: true,
            filter: {
              isFilter: true,
              type: 'contains',
            },
            isSort: true,
            width:'15%'
          },
          {
            label: 'Httpstatuscode',
            valueField: 'httpstatuscode',
            classes: 'text-left',
            selected: true,
            filter: {
              isFilter: true,
              type: 'contains',
            },
            isSort: true,
            width:'10%'
          },
          {
            label: 'Lname',
            valueField: 'lname',
            classes: 'text-left',
            selected: true,
            filter: {
              isFilter: true,
              type: 'custom',
            },
            isSort: true,
          },
          {
            label: 'Skucount',
            valueField: 'skucount',
            classes: 'text-left',
            selected: true,
            filter: {
              isFilter: true,
              type: 'contains',
            },
            isSort: true,
          },
          {
            label: '@timestamp',
            valueField: 'timestamp',
            classes: 'text-left',
            selected: true,
            filter: {
              isFilter: true,
              type: 'contains',
            },
            isSort: true,
          },
          {
            label: 'Skus',
            valueField: 'kus',
            classes: 'text-left',
            selected: true,
            filter: {
              isFilter: true,
              type: 'contains',
            },
            isSort: true,
          },
          {
            label: 'ResTime',
            valueField: 'restime',
            classes: 'text-left',
            selected: true,
            filter: {
              isFilter: true,
              type: 'contains',
            },
            isSort: true,
          },
          {
            label: 'Sizeinbytes',
            valueField: 'sizeinbytes',
            classes: 'text-left',
            selected: true,
            filter: {
              isFilter: true,
              type: 'contains',
            },
            isSort: true,
          },
          {
            label: 'Userlogin',
            valueField: 'userlogin',
            classes: 'text-left',
            selected: true,
            filter: {
              isFilter: true,
              type: 'contains',
            },
            isSort: true,
          },
        ],
      },
    ],
    data: [
      {
        indices: 'netForest',
        type: 'dashboard',
        score: '1',
        id: 'NF-alert-dashboard',
        httpstatuscode: '',
        lname: '',
        skucount: '',
        timestamp: '',
        kus: '',
        restime: '',
        sizeinbytes: '',
        userlogin: '',
      },
      {
        indices: 'netForest_m',
        type: 'dashboard',
        score: '2',
        id: 'NF-alert-dashboard',
        httpstatuscode: '',
        lname: '',
        skucount: '',
        timestamp: '',
        kus: '',
        restime: '',
        sizeinbytes: '',
        userlogin: '',
      },
      {
        indices: 'netForest',
        type: 'dashboard',
        score: '1',
        id: 'NF-alert-dashboard',
        httpstatuscode: '',
        lname: '',
        skucount: '',
        timestamp: '',
        kus: '',
        restime: '',
        sizeinbytes: '',
        userlogin: '',
      },
      {
        indices: 'netForest_m',
        type: 'dashboard',
        score: '2',
        id: 'NF-alert-dashboard',
        httpstatuscode: '',
        lname: '',
        skucount: '',
        timestamp: '',
        kus: '',
        restime: '',
        sizeinbytes: '',
        userlogin: '',
      },
      {
        indices: 'netForest',
        type: 'dashboard',
        score: '1',
        id: 'NF-alert-dashboard',
        httpstatuscode: '',
        lname: '',
        skucount: '',
        timestamp: '',
        kus: '',
        restime: '',
        sizeinbytes: '',
        userlogin: '',
      },
      {
        indices: 'netForest_m',
        type: 'dashboard',
        score: '2',
        id: 'NF-alert-dashboard',
        httpstatuscode: '',
        lname: '',
        skucount: '',
        timestamp: '',
        kus: '',
        restime: '',
        sizeinbytes: '',
        userlogin: '',
      },
      {
        indices: 'netForest',
        type: 'dashboard',
        score: '1',
        id: 'NF-alert-dashboard',
        httpstatuscode: '',
        lname: '',
        skucount: '',
        timestamp: '',
        kus: '',
        restime: '',
        sizeinbytes: '',
        userlogin: '',
      },
      {
        indices: 'netForest_m',
        type: 'dashboard',
        score: '2',
        id: 'NF-alert-dashboard',
        httpstatuscode: '',
        lname: '',
        skucount: '',
        timestamp: '',
        kus: '',
        restime: '',
        sizeinbytes: '',
        userlogin: '',
      },
      {
        indices: 'netForest',
        type: 'dashboard',
        score: '1',
        id: 'NF-alert-dashboard',
        httpstatuscode: '',
        lname: '',
        skucount: '',
        timestamp: '',
        kus: '',
        restime: '',
        sizeinbytes: '',
        userlogin: '',
      },
      {
        indices: 'netForest_m',
        type: 'dashboard',
        score: '2',
        id: 'NF-alert-dashboard',
        httpstatuscode: '',
        lname: '',
        skucount: '',
        timestamp: '',
        kus: '',
        restime: '',
        sizeinbytes: '',
        userlogin: '',
      },
      {
        indices: 'netForest',
        type: 'dashboard',
        score: '1',
        id: 'NF-alert-dashboard',
        httpstatuscode: '',
        lname: '',
        skucount: '',
        timestamp: '',
        kus: '',
        restime: '',
        sizeinbytes: '',
        userlogin: '',
      },
      {
        indices: 'netForest_m',
        type: 'dashboard',
        score: '2',
        id: 'NF-alert-dashboard',
        httpstatuscode: '',
        lname: '',
        skucount: '',
        timestamp: '',
        kus: '',
        restime: '',
        sizeinbytes: '',
        userlogin: '',
      },
      {
        indices: 'netForest',
        type: 'dashboard',
        score: '1',
        id: 'NF-alert-dashboard',
        httpstatuscode: '',
        lname: '',
        skucount: '',
        timestamp: '',
        kus: '',
        restime: '',
        sizeinbytes: '',
        userlogin: '',
      },
      {
        indices: 'netForest_m',
        type: 'dashboard',
        score: '2',
        id: 'NF-alert-dashboard',
        httpstatuscode: '',
        lname: '',
        skucount: '',
        timestamp: '',
        kus: '',
        restime: '',
        sizeinbytes: '',
        userlogin: '',
      },
      {
        indices: 'netForest',
        type: 'dashboard',
        score: '1',
        id: 'NF-alert-dashboard',
        httpstatuscode: '',
        lname: '',
        skucount: '',
        timestamp: '',
        kus: '',
        restime: '',
        sizeinbytes: '',
        userlogin: '',
      },
      {
        indices: 'netForest_m',
        type: 'dashboard',
        score: '2',
        id: 'NF-alert-dashboard',
        httpstatuscode: '',
        lname: '',
        skucount: '',
        timestamp: '',
        kus: '',
        restime: '',
        sizeinbytes: '',
        userlogin: '',
      },
      {
        indices: 'netForest',
        type: 'dashboard',
        score: '1',
        id: 'NF-alert-dashboard',
        httpstatuscode: '',
        lname: '',
        skucount: '',
        timestamp: '',
        kus: '',
        restime: '',
        sizeinbytes: '',
        userlogin: '',
      },
      {
        indices: 'netForest_m',
        type: 'dashboard',
        score: '2',
        id: 'NF-alert-dashboard',
        httpstatuscode: '',
        lname: '',
        skucount: '',
        timestamp: '',
        kus: '',
        restime: '',
        sizeinbytes: '',
        userlogin: '',
      },
      {
        indices: 'netForest',
        type: 'dashboard',
        score: '1',
        id: 'NF-alert-dashboard',
        httpstatuscode: '',
        lname: '',
        skucount: '',
        timestamp: '',
        kus: '',
        restime: '',
        sizeinbytes: '',
        userlogin: '',
      },
      {
        indices: 'netForest_m',
        type: 'dashboard',
        score: '2',
        id: 'NF-alert-dashboard',
        httpstatuscode: '',
        lname: '',
        skucount: '',
        timestamp: '',
        kus: '',
        restime: '',
        sizeinbytes: '',
        userlogin: '',
      },
      {
        indices: 'netForest',
        type: 'dashboard',
        score: '1',
        id: 'NF-alert-dashboard',
        httpstatuscode: '',
        lname: '',
        skucount: '',
        timestamp: '',
        kus: '',
        restime: '',
        sizeinbytes: '',
        userlogin: '',
      },
      {
        indices: 'netForest_m',
        type: 'dashboard',
        score: '2',
        id: 'NF-alert-dashboard',
        httpstatuscode: '',
        lname: '',
        skucount: '',
        timestamp: '',
        kus: '',
        restime: '',
        sizeinbytes: '',
        userlogin: '',
      },
      {
        indices: 'netForest',
        type: 'dashboard',
        score: '1',
        id: 'NF-alert-dashboard',
        httpstatuscode: '',
        lname: '',
        skucount: '',
        timestamp: '',
        kus: '',
        restime: '',
        sizeinbytes: '',
        userlogin: '',
      },
      {
        indices: 'netForest_m',
        type: 'dashboard',
        score: '2',
        id: 'NF-alert-dashboard',
        httpstatuscode: '',
        lname: '',
        skucount: '',
        timestamp: '',
        kus: '',
        restime: '',
        sizeinbytes: '',
        userlogin: '',
      },
      {
        indices: 'netForest',
        type: 'dashboard',
        score: '1',
        id: 'NF-alert-dashboard',
        httpstatuscode: '',
        lname: '',
        skucount: '',
        timestamp: '',
        kus: '',
        restime: '',
        sizeinbytes: '',
        userlogin: '',
      },
      {
        indices: 'netForest_m',
        type: 'dashboard',
        score: '2',
        id: 'NF-alert-dashboard',
        httpstatuscode: '',
        lname: '',
        skucount: '',
        timestamp: '',
        kus: '',
        restime: '',
        sizeinbytes: '',
        userlogin: '',
      },
      {
        indices: 'netForest',
        type: 'dashboard',
        score: '1',
        id: 'NF-alert-dashboard',
        httpstatuscode: '',
        lname: '',
        skucount: '',
        timestamp: '',
        kus: '',
        restime: '',
        sizeinbytes: '',
        userlogin: '',
      },
      {
        indices: 'netForest_m',
        type: 'dashboard',
        score: '2',
        id: 'NF-alert-dashboard',
        httpstatuscode: '',
        lname: '',
        skucount: '',
        timestamp: '',
        kus: '',
        restime: '',
        sizeinbytes: '',
        userlogin: '',
      },
      {
        indices: 'netForest',
        type: 'dashboard',
        score: '1',
        id: 'NF-alert-dashboard',
        httpstatuscode: '',
        lname: '',
        skucount: '',
        timestamp: '',
        kus: '',
        restime: '',
        sizeinbytes: '',
        userlogin: '',
      },
      {
        indices: 'netForest_m',
        type: 'dashboard',
        score: '2',
        id: 'NF-alert-dashboard',
        httpstatuscode: '',
        lname: '',
        skucount: '',
        timestamp: '',
        kus: '',
        restime: '',
        sizeinbytes: '',
        userlogin: '',
      },
    ],
    paginator: {
      first: 0,
      rows: 10,
      rowsPerPageOptions: [10, 20, 30, 50, 100],
    },
    tableFilter: true,
  },
};
