import { AdvancedSessionTable } from './advanced-session.model';

export const ADVANCED_SESSION_TABLE: AdvancedSessionTable = {

    paginator: {
      first: 1,
      rows: 10,
      rowsPerPageOptions: [10, 20, 30, 50, 100],
    },
  
    headers: [
      {
        cols: [
          {
            label: 'No',
            valueField: 'no',
            classes: 'text-left',
            selected: true,
            filter: {
              isFilter: true,
              type: 'contains',
            },
            isSort: true,           
          },
          {
            label: 'Test Run',
            valueField: 'testRun',
            classes: 'text-left',
            selected: true,
            filter: {
              isFilter: true,
              type: 'contains',
            },
            isSort: true,
          },
          {
            label: 'Test Name',
            valueField: 'testName',
            classes: 'text-center',
            selected: true,
            filter: {
              isFilter: true,
              type: 'contains',
            },
            isSort: true ,       
          },
          {
            label: 'Scenario Name',
            valueField: 'scnrName',
            classes: 'text-center',
            selected: true,
            filter: {
              isFilter: true,
              type: 'contains',
            },
            isSort: true,
            width:'20%'  
          },
          {
            label: 'Start Time',
            valueField: 'startTime',
            classes: 'text-center',
            selected: true,
            filter: {
              isFilter: true,
              type: 'contains',
            },
            isSort: true,
          },
          {
            label: 'Run Time',
            valueField: 'runTime',
            classes: 'text-center',
            selected: true,
            filter: {
              isFilter: true,
              type: 'contains',
            },
            isSort: true,
          },
          {
            label: 'User',
            valueField: 'user',
            classes: 'text-center',
            selected: true,
            filter: {
              isFilter: true,
              type: 'contains',
            },
            isSort: true,
          },
          {
            label: 'Started By',
            valueField: 'startedBy',
            classes: 'text-center',
            selected: true,
            filter: {
              isFilter: true,
              type: 'contains',
            },
            isSort: true,
          },
          {
            label: 'Notes',
            valueField: 'notes',
            classes: 'text-center',
            selected: true,
            filter: {
              isFilter: true,
              type: 'contains',
            },
            isSort: true,
          }         
        ],
      },
    ],
    data: [
      {
        no: '1',
        testRun: '11001',
        testName: 'NDE_DashboardTesting',        
        scnrName: 'NDE_DashboardTesting',
        startTime: '23:51:24 02/03/20',
        runTime: '01:05:00',
        user: '20',
        startedBy: 'Cavisson',
        notes: 'NA',
        
      },
      {
        no: '2',
        testRun: '11001',
        testName: 'NDE_DashboardTesting',        
        scnrName: 'NDE_DashboardTesting',
        startTime: '23:51:24 02/03/20',
        runTime: '01:05:00',
        user: '20',
        startedBy: 'Cavisson',
        notes: 'NA',
        
      },
      {
        no: '3',
        testRun: '11001',
        testName: 'NDE_DashboardTesting',        
        scnrName: 'NDE_DashboardTesting',
        startTime: '23:51:24 02/03/20',
        runTime: '01:05:00',
        user: '20',
        startedBy: 'Cavisson',
        notes: 'NA',
        
      },
      {
        no: '4',
        testRun: '11001',
        testName: 'NDE_DashboardTesting',        
        scnrName: 'NDE_DashboardTesting',
        startTime: '23:51:24 02/03/20',
        runTime: '01:05:00',
        user: '20',
        startedBy: 'Cavisson',
        notes: 'NA',
        
      },
      {
        no: '5',
        testRun: '11001',
        testName: 'NDE_DashboardTesting',        
        scnrName: 'NDE_DashboardTesting',
        startTime: '23:51:24 02/03/20',
        runTime: '01:05:00',
        user: '20',
        startedBy: 'Cavisson',
        notes: 'NA',
        
      },
      {
        no: '6',
        testRun: '11001',
        testName: 'NDE_DashboardTesting',        
        scnrName: 'NDE_DashboardTesting',
        startTime: '23:51:24 02/03/20',
        runTime: '01:05:00',
        user: '20',
        startedBy: 'Cavisson',
        notes: 'NA',
        
      },
      {
        no: '7',
        testRun: '11001',
        testName: 'NDE_DashboardTesting',        
        scnrName: 'NDE_DashboardTesting',
        startTime: '23:51:24 02/03/20',
        runTime: '01:05:00',
        user: '20',
        startedBy: 'Cavisson',
        notes: 'NA',
        
      },
      {
        no: '8',
        testRun: '11001',
        testName: 'NDE_DashboardTesting',        
        scnrName: 'NDE_DashboardTesting',
        startTime: '23:51:24 02/03/20',
        runTime: '01:05:00',
        user: '20',
        startedBy: 'Cavisson',
        notes: 'NA',
        
      },
      {
        no: '9',
        testRun: '11001',
        testName: 'NDE_DashboardTesting',        
        scnrName: 'NDE_DashboardTesting',
        startTime: '23:51:24 02/03/20',
        runTime: '01:05:00',
        user: '20',
        startedBy: 'Cavisson',
        notes: 'NA',
        
      },
      {
        no: '10',
        testRun: '11001',
        testName: 'NDE_DashboardTesting',        
        scnrName: 'NDE_DashboardTesting',
        startTime: '23:51:24 02/03/20',
        runTime: '01:05:00',
        user: '20',
        startedBy: 'Cavisson',
        notes: 'NA',
        
      },
      {
        no: '11',
        testRun: '11001',
        testName: 'NDE_DashboardTesting',        
        scnrName: 'NDE_DashboardTesting',
        startTime: '23:51:24 02/03/20',
        runTime: '01:05:00',
        user: '20',
        startedBy: 'Cavisson',
        notes: 'NA',
        
      },
      {
        no: '12',
        testRun: '11001',
        testName: 'NDE_DashboardTesting',        
        scnrName: 'NDE_DashboardTesting',
        startTime: '23:51:24 02/03/20',
        runTime: '01:05:00',
        user: '20',
        startedBy: 'Cavisson',
        notes: 'NA',
        
      },
      {
        no: '13',
        testRun: '11001',
        testName: 'NDE_DashboardTesting',        
        scnrName: 'NDE_DashboardTesting',
        startTime: '23:51:24 02/03/20',
        runTime: '01:05:00',
        user: '20',
        startedBy: 'Cavisson',
        notes: 'NA',
        
      },
      {
        no: '14',
        testRun: '11001',
        testName: 'NDE_DashboardTesting',        
        scnrName: 'NDE_DashboardTesting',
        startTime: '23:51:24 02/03/20',
        runTime: '01:05:00',
        user: '20',
        startedBy: 'Cavisson',
        notes: 'NA',
        
      },
      {
        no: '15',
        testRun: '11001',
        testName: 'NDE_DashboardTesting',        
        scnrName: 'NDE_DashboardTesting',
        startTime: '23:51:24 02/03/20',
        runTime: '01:05:00',
        user: '20',
        startedBy: 'Cavisson',
        notes: 'NA',
        
      },
      {
        no: '16',
        testRun: '11001',
        testName: 'NDE_DashboardTesting',        
        scnrName: 'NDE_DashboardTesting',
        startTime: '23:51:24 02/03/20',
        runTime: '01:05:00',
        user: '20',
        startedBy: 'Cavisson',
        notes: 'NA',
        
      },
      {
        no: '17',
        testRun: '11001',
        testName: 'NDE_DashboardTesting',        
        scnrName: 'NDE_DashboardTesting',
        startTime: '23:51:24 02/03/20',
        runTime: '01:05:00',
        user: '20',
        startedBy: 'Cavisson',
        notes: 'NA',
        
      },
      {
        no: '18',
        testRun: '11001',
        testName: 'NDE_DashboardTesting',        
        scnrName: 'NDE_DashboardTesting',
        startTime: '23:51:24 02/03/20',
        runTime: '01:05:00',
        user: '20',
        startedBy: 'Cavisson',
        notes: 'NA',
        
      },
      {
        no: '19',
        testRun: '11001',
        testName: 'NDE_DashboardTesting',        
        scnrName: 'NDE_DashboardTesting',
        startTime: '23:51:24 02/03/20',
        runTime: '01:05:00',
        user: '20',
        startedBy: 'Cavisson',
        notes: 'NA',
        
      },
      {
        no: '20',
        testRun: '11001',
        testName: 'NDE_DashboardTesting',        
        scnrName: 'NDE_DashboardTesting',
        startTime: '23:51:24 02/03/20',
        runTime: '01:05:00',
        user: '20',
        startedBy: 'Cavisson',
        notes: 'NA',
        
      },
      {
        no: '21',
        testRun: '11001',
        testName: 'NDE_DashboardTesting',        
        scnrName: 'NDE_DashboardTesting',
        startTime: '23:51:24 02/03/20',
        runTime: '01:05:00',
        user: '20',
        startedBy: 'Cavisson',
        notes: 'NA',
        
      },
      {
        no: '22',
        testRun: '11001',
        testName: 'NDE_DashboardTesting',        
        scnrName: 'NDE_DashboardTesting',
        startTime: '23:51:24 02/03/20',
        runTime: '01:05:00',
        user: '20',
        startedBy: 'Cavisson',
        notes: 'NA',
        
      },
      {
        no: '23',
        testRun: '11001',
        testName: 'NDE_DashboardTesting',        
        scnrName: 'NDE_DashboardTesting',
        startTime: '23:51:24 02/03/20',
        runTime: '01:05:00',
        user: '20',
        startedBy: 'Cavisson',
        notes: 'NA',
        
      },
      {
        no: '24',
        testRun: '11001',
        testName: 'NDE_DashboardTesting',        
        scnrName: 'NDE_DashboardTesting',
        startTime: '23:51:24 02/03/20',
        runTime: '01:05:00',
        user: '20',
        startedBy: 'Cavisson',
        notes: 'NA',
        
      },
      {
        no: '25',
        testRun: '11001',
        testName: 'NDE_DashboardTesting',        
        scnrName: 'NDE_DashboardTesting',
        startTime: '23:51:24 02/03/20',
        runTime: '01:05:00',
        user: '20',
        startedBy: 'Cavisson',
        notes: 'NA',
        
      },
      {
        no: '26',
        testRun: '11001',
        testName: 'NDE_DashboardTesting',        
        scnrName: 'NDE_DashboardTesting',
        startTime: '23:51:24 02/03/20',
        runTime: '01:05:00',
        user: '20',
        startedBy: 'Cavisson',
        notes: 'NA',
        
      },
      {
        no: '27',
        testRun: '11001',
        testName: 'NDE_DashboardTesting',        
        scnrName: 'NDE_DashboardTesting',
        startTime: '23:51:24 02/03/20',
        runTime: '01:05:00',
        user: '20',
        startedBy: 'Cavisson',
        notes: 'NA',
        
      },
    ],
  
    tableFilter: true,
  };