import { Table } from "src/app/shared/table/table.model";
import { AlertsTable } from "./alert-table.model";


export const ALERT_TABLE: AlertsTable = {

    paginator: {
        first: 1,
        rows: 33,
        rowsPerPageOptions: [ 5, 10, 25, 50, 100],
    },
   
    headers: [
        {
            cols: [
                {
                    label: 'Rule Name',
                    valueField: 'rulename',
                    classes: 'text-left',
                    selected: true,
                    filter: {
                        isFilter: true,
                        type: 'contains',
                      },
                    isSort: true,
                },
                {
                    label: 'Alert Status',
                    valueField: 'alertStatus',
                    classes: 'text-center',
                    selected: true,
                    filter: {
                        isFilter: true,
                        type: 'contains',
                      },
                    isSort: true,
                    width: '10%',
                    severity: true,
                    severityColorField: true,
                },
                {
                    label: 'Ack',
                    valueField: 'iconAck',
                    iconField: true,
                    classes: 'text-left',
                    selected: true,
                    filter: {
                        isFilter: true,
                        type: 'contains',
                      },
                    isSort: true,
                    //width: '5%'
                },
                {
                    label: 'Start Time',
                    valueField: 'startTime',
                    classes: 'text-left',
                    selected: true,
                    filter: {
                        isFilter: true,
                        type: 'contains',
                      },
                    isSort: true,
                },
                {
                    label: 'Time Age',
                    valueField: 'timeAge',
                    classes: 'text-left',
                    selected: true,
                    filter: {
                        isFilter: true,
                        type: 'contains',
                      },
                    isSort: true,
                },
                {
                    label: 'Alert Message',
                    valueField: 'alertMessage',
                    classes: 'text-left',
                    selected: true,
                    filter: {
                        isFilter: true,
                        type: 'contains',
                      },
                    isSort: true,
                },
                {
                    label: 'Indices',
                    valueField: 'indices',
                    classes: 'text-left',
                    selected: true,
                    filter: {
                        isFilter: true,
                        type: 'contains',
                      },
                    isSort: true,
                },
                {
                    label: 'Alert Value',
                    valueField: 'alertValue',
                    classes: 'text-left',
                    selected: true,
                    filter: {
                        isFilter: true,
                        type: 'contains',
                      },
                    isSort: true,
                },
                {
                    label: 'Threshold',
                    valueField: 'threshold',
                    classes: 'text-left',
                    selected: true,
                    filter: {
                        isFilter: true,
                        type: 'contains',
                      },
                    isSort: true,
                },
            ],
        },
    ],
    data: [
        {
            rulename: 'Page Alert2',
            startTime: '23:51:24, 02/02/20',
            timeAge: '10 minutes ago',
            alertMessage: 'Every 15 min on alternate days',
            indices: 'Dummy text',
            alertValue: 'Performance',
            threshold: 'Threshold',
            iconAck: 'icons8 icons8-checkmark',
            alertStatus: 'Critical',
            color: '#f12929'
        },
        {
            rulename: 'Page Alert2',
            startTime: '23:51:24, 02/02/20',
            timeAge: '15 minutes ago',
            alertMessage: 'Every 15 min on alternate days',
            indices: 'Dummy text',
            alertValue: 'Performance',
            threshold: 'Threshold',
            iconAck: 'icons8 icons8-checkmark',
            alertStatus: 'Major',
            color: '#ff9898',
        },
        {
            rulename: 'Page Alert2',
            startTime: '23:51:24, 02/02/20',
            timeAge: '10 minutes ago',
            alertMessage: 'Every 15 min on alternate days',
            indices: 'Dummy text',
            alertValue: 'Performance',
            threshold: 'Threshold',
            iconAck: 'icons8 icons8-checkmark',
            alertStatus: 'Minor',
            color: '#ffc9c9',
        },
        {
            rulename: 'Page Alert2',
            startTime: '23:51:24, 02/02/20',
            timeAge: '10 minutes ago',
            alertMessage: 'Every 15 min on alternate days',
            indices: 'Dummy text',
            alertValue: 'Performance',
            threshold: 'Threshold',
            iconAck: 'icons8 icons8-checkmark',
            alertStatus: 'Major',
            color: '#ff9898',
        },
        {
            rulename: 'Page Alert2',
            startTime: '23:51:24, 02/02/20',
            timeAge: '10 minutes ago',
            alertMessage: 'Every 15 min on alternate days',
            indices: 'Dummy text',
            alertValue: 'Performance',
            threshold: 'Threshold',
            iconAck: 'icons8 icons8-checkmark',
            alertStatus: 'Critical',
            color: '#f12929'
        },
        {
            rulename: 'Page Alert2',
            startTime: '23:51:24, 02/02/20',
            timeAge: '10 minutes ago',
            alertMessage: 'Every 15 min on alternate days',
            indices: 'Dummy text',
            alertValue: 'Performance',
            threshold: 'Threshold',
            iconAck: 'icons8 icons8-checkmark',
            alertStatus: 'Major',
            color: '#ff9898',
        },
        {
            rulename: 'Page Alert2',
            startTime: '23:51:24, 02/02/20',
            timeAge: '10 minutes ago',
            alertMessage: 'Every 15 min on alternate days',
            indices: 'Dummy text',
            alertValue: 'Performance',
            threshold: 'Threshold',
            iconAck: 'icons8 icons8-checkmark',
            alertStatus: 'Minor',
            color: '#ffc9c9',
        },
        {
            rulename: 'Page Alert2',
            startTime: '23:51:24, 02/02/20',
            timeAge: '10 minutes ago',
            alertMessage: 'Every 15 min on alternate days',
            indices: 'Dummy text',
            alertValue: 'Performance',
            threshold: 'Threshold',
            iconAck: 'icons8 icons8-checkmark',
            alertStatus: 'Critical',
            color: '#f12929'
        },
        {
            rulename: 'Page Alert2',
            startTime: '23:51:24, 02/02/20',
            timeAge: '10 minutes ago',
            alertMessage: 'Every 15 min on alternate days',
            indices: 'Dummy text',
            alertValue: 'Performance',
            threshold: 'Threshold',
            iconAck: 'icons8 icons8-checkmark',
            alertStatus: 'Major',
            color: '#ff9898',
        },
        {
            rulename: 'Page Alert2',
            startTime: '23:51:24, 02/02/20',
            timeAge: '10 minutes ago',
            alertMessage: 'Every 15 min on alternate days',
            indices: 'Dummy text',
            alertValue: 'Performance',
            threshold: 'Threshold',
            iconAck: 'icons8 icons8-checkmark',
            alertStatus: 'Minor',
            color: '#ffc9c9',
            
        },
        {
            rulename: 'Page Alert2',
            startTime: '23:51:24, 02/02/20',
            timeAge: '10 minutes ago',
            alertMessage: 'Every 15 min on alternate days',
            indices: 'Dummy text',
            alertValue: 'Performance',
            threshold: 'Threshold',
            iconAck: 'icons8 icons8-checkmark',
            alertStatus: 'Major',
            color: '#ff9898',
        },
        {
            rulename: 'Page Alert2',
            startTime: '23:51:24, 02/02/20',
            timeAge: '10 minutes ago',
            alertMessage: 'Every 15 min on alternate days',
            indices: 'Dummy text',
            alertValue: 'Performance',
            threshold: 'Threshold',
            iconAck: 'icons8 icons8-checkmark',
            alertStatus: 'Critical',
            color: '#f12929'
        },
    ],
    iconsField: 'icon',
    severityCondition: 'severity',
    tableFilter: true,
};