
import { PeripheralDeviceTable } from './peripheral.model';


export const PERIPHERAL_TABLE_DATA: PeripheralDeviceTable 
  = {

    paginator: {
      first: 1,
      rows: 10,
      rowsPerPageOptions: [5, 10, 25, 50, 100],
    },
  
    headers: [
      {
        cols: [
          {
            label: '#',
            valueField: 'index',
            classes: 'text-left',
            selected: true,
            filter: {
              isFilter: true,
              type: 'contains',
            },
            isSort: true,
          },
          {
            label: 'Category',
            valueField: 'category',
            classes: 'text-left',
            selected: true,
            filter: {
              isFilter: true,
              type: 'contains',
            },
            isSort: true,
          },
         
          {
            label: 'Device Name',
            valueField: 'devicename',
            classes: 'text-center',
            selected: true,
            filter: {
              isFilter: true,
              type: 'contains',
            },
            isSort: true,
          },
          {
            label: 'Status',
            valueField: 'status',
            classes: 'text-center',
            selected: true,
            iconField: true,
            filter: {
              isFilter: true,
              type: 'contains',
            },
            isSort: true,
          },
          {
            label: 'Timestamp',
            valueField: 'timestamp',
            classes: 'text-center',
            selected: true,
            filter: {
              isFilter: true,
              type: 'contains',
            },
            isSort: true,
          },
          {
            label: 'Description',
            valueField: 'description',
            classes: 'text-center',
            selected: true,
            filter: {
              isFilter: true,
              type: 'contains',
            },
            isSort: true,
          },
         
       
       
        ],
      },
    ],
    data: [
      {
        index: '1',
        category: 'Devices',
        devicename: 'Devices>APN102KSJNDHIS',
        icon: 'icons8 icons8-checkmark',
        timestamp:'2020-04-17 01:48:46',
        description: 'Cavission',
      },
      {
        index: '1',
        category: 'Devices',
        devicename: 'Devices>APN102KSJNDHIS',
        icon: 'icons8 icons8-error',
        timestamp:'2020-04-17 01:48:46',
        description: 'Cavission',
      },
      {
        index: '1',
        category: 'Devices',
        devicename: 'Devices>APN102KSJNDHIS',
        icon: 'icons8 icons8-checkmark',
        timestamp:'2020-04-17 01:48:46',
        description: 'Cavission',
      },
      {
        index: '1',
        category: 'Devices',
        devicename: 'Devices>APN102KSJNDHIS',
        icon: 'icons8 icons8-error',
        timestamp:'2020-04-17 01:48:46',
        description: 'Cavission',
      },
      {
        index: '1',
        category: 'Devices',
        devicename: 'Devices>APN102KSJNDHIS',
        icon: 'icons8 icons8-checkmark',
        timestamp:'2020-04-17 01:48:46',
        description: 'Cavission',
      },
      {
        index: '1',
        category: 'Devices',
        devicename: 'Devices>APN102KSJNDHIS',
        icon: 'icons8 icons8-error',
        timestamp:'2020-04-17 01:48:46',
        description: 'Cavission',
      },
      {
        index: '1',
        category: 'Devices',
        devicename: 'Devices>APN102KSJNDHIS',
        icon: 'icons8 icons8-checkmark',
        timestamp:'2020-04-17 01:48:46',
        description: 'Cavission',
      },
      {
        index: '1',
        category: 'Devices',
        devicename: 'Devices>APN102KSJNDHIS',
        icon: 'icons8 icons8-error',
        timestamp:'2020-04-17 01:48:46',
        description: 'Cavission',
      },
      {
        index: '1',
        category: 'Devices',
        devicename: 'Devices>APN102KSJNDHIS',
        icon: 'icons8 icons8-checkmark',
        timestamp:'2020-04-17 01:48:46',
        description: 'Cavission',
      },
      {
        index: '1',
        category: 'Devices',
        devicename: 'Devices>APN102KSJNDHIS',
        icon: 'icons8 icons8-error',
        timestamp:'2020-04-17 01:48:46',
        description: 'Cavission',
      },
      {
        index: '1',
        category: 'Devices',
        devicename: 'Devices>APN102KSJNDHIS',
        icon: 'icons8 icons8-error',
        timestamp:'2020-04-17 01:48:46',
        description: 'Cavission',
      },
      {
        index: '1',
        category: 'Devices',
        devicename: 'Devices>APN102KSJNDHIS',
        icon: 'icons8 icons8-error',
        timestamp:'2020-04-17 01:48:46',
        description: 'Cavission',
      },
      {
        index: '1',
        category: 'Devices',
        devicename: 'Devices>APN102KSJNDHIS',
        icon: 'icons8 icons8-error',
        timestamp:'2020-04-17 01:48:46',
        description: 'Cavission',
      },
      {
        index: '1',
        category: 'Devices',
        devicename: 'Devices>APN102KSJNDHIS',
        icon: 'icons8 icons8-error',
        timestamp:'2020-04-17 01:48:46',
        description: 'Cavission',
      },
      {
        index: '1',
        category: 'Devices',
        devicename: 'Devices>APN102KSJNDHIS',
        icon: 'icons8 icons8-error',
        timestamp:'2020-04-17 01:48:46',
        description: 'Cavission',
      },
      {
        index: '1',
        category: 'Devices',
        devicename: 'Devices>APN102KSJNDHIS',
        icon: 'icons8 icons8-error',
        timestamp:'2020-04-17 01:48:46',
        description: 'Cavission',
      },
      {
        index: '1',
        category: 'Devices',
        devicename: 'Devices>APN102KSJNDHIS',
        icon: 'icons8 icons8-error',
        timestamp:'2020-04-17 01:48:46',
        description: 'Cavission',
      },
      {
        index: '1',
        category: 'Devices',
        devicename: 'Devices>APN102KSJNDHIS',
        icon: 'icons8 icons8-error',
        timestamp:'2020-04-17 01:48:46',
        description: 'Cavission',
      },
      {
        index: '1',
        category: 'Devices',
        devicename: 'Devices>APN102KSJNDHIS',
        icon: 'icons8 icons8-error',
        timestamp:'2020-04-17 01:48:46',
        description: 'Cavission',
      },
      {
        index: '1',
        category: 'Devices',
        devicename: 'Devices>APN102KSJNDHIS',
        icon: 'icons8 icons8-error',
        timestamp:'2020-04-17 01:48:46',
        description: 'Cavission',
      },
      {
        index: '1',
        category: 'Devices',
        devicename: 'Devices>APN102KSJNDHIS',
        icon: 'icons8 icons8-error',
        timestamp:'2020-04-17 01:48:46',
        description: 'Cavission',
      },
      {
        index: '1',
        category: 'Devices',
        devicename: 'Devices>APN102KSJNDHIS',
        icon: 'icons8 icons8-error',
        timestamp:'2020-04-17 01:48:46',
        description: 'Cavission',
      },
      {
        index: '1',
        category: 'Devices',
        devicename: 'Devices>APN102KSJNDHIS',
        icon: 'icons8 icons8-error',
        timestamp:'2020-04-17 01:48:46',
        description: 'Cavission',
      },
      {
        index: '1',
        category: 'Devices',
        devicename: 'Devices>APN102KSJNDHIS',
        icon: 'icons8 icons8-error',
        timestamp:'2020-04-17 01:48:46',
        description: 'Cavission',
      },
      {
        index: '1',
        category: 'Devices',
        devicename: 'Devices>APN102KSJNDHIS',
        icon: 'icons8 icons8-error',
        timestamp:'2020-04-17 01:48:46',
        description: 'Cavission',
      },
      {
        index: '1',
        category: 'Devices',
        devicename: 'Devices>APN102KSJNDHIS',
        icon: 'icons8 icons8-error',
        timestamp:'2020-04-17 01:48:46',
        description: 'Cavission',
      },
      {
        index: '1',
        category: 'Devices',
        devicename: 'Devices>APN102KSJNDHIS',
        icon: 'icons8 icons8-error',
        timestamp:'2020-04-17 01:48:46',
        description: 'Cavission',
      },
     
    
     
    ],
  
    tableFilter: false,
  };