import {
  DashboardGroupWidgetConfig,
  DashboardLoadReq,
  DashboardWidgetLoadReq,
  DashboardWidgetSettings,
} from './dashboard.model';

export const DASHBOARD_LOAD_PAYLOAD: DashboardLoadReq = {
  opType: 0,
  cctx: {
    cck: 'lrmdev3.11111.1602743897770',
    pk: 'lrmdev3:49.35.67.123:10-15-2020 02-38-17',
    u: 'lrmdev3',
    prodType: 'Netdiagnostics',
  },
  tr: 11111,
  compareCtx: null,
  multiDc: false,
  favCtx: {
    favNameCtx: {
      name: 'NDEDefault',
      path: 'system/NDEDefault',
    },
    favDetailCtx: {},
  },
};

export const DASHBOARD_WIDGET_LOAD_PAYLOAD: DashboardWidgetLoadReq = {
  globalFavCtx: {
    backToHealthWidget: false,
    enableAlertOverlay: false,
    favDesc: 'NA',
    favName: 'AdvanceFav_V2',
    favPublic: true,
    favRelPath: '',
    includeCurrentData: false,
    isShowDiscontinuedGraphs: true,
    layoutId: -1,
    parameteriazationMode: false,
    ruleType: 0,
    running: true,
    updateBy: 'cavisson',
  },
  multiDc: false,
  tsdbCtx: {
    opType: 0,
    appId: '1',
    clientId: 0,
    cctx: {
      cck: 'cavisson.334455.1595508002528',
      pk: 'cavisson:192.168.8.12:07-24-2020 00-36-08',
      u: 'cavisson',
      prodType: 'Netdiagnostics',
    },
    dataFilter: [0],
    duration: {
      st: 0,
      et: 0,
      preset: 'LIVE1',
      viewBy: 60,
    },
    tr: 11111,
    avgCount: 0,
    avgCounter: 0,
    dataCtx: {
      compare: null,
      ft: null,
      gCtx: [
        {
          baselineCtx: {
            maxValue: 0,
            minValue: 0,
            totalBucket: 0,
          },
          derivedFormula: null,
          glbMetricId: -1,
          measure: {
            metric: 'Processes Waiting For Run Time',
            metricId: 1,
            mg: 'SysStats Linux Extended',
            mgId: 10108,
            mgType: 'System Metrics',
            mgTypeId: -1,
          },
          subject: {
            tags: [
              {
                key: 'Tier',
                value: 'Cavisson',
              },
              {
                key: 'Server',
                value: 'NDAppliance',
              },
            ],
          },
        },
      ],
      selfTrend: 0,
    },
  },
  widget: {
    dataAttrName: 'avg',
    dataCtx: {
      compare: null,
      ft: null,
      gCtx: [
        {
          baselineCtx: {
            maxValue: 0,
            minValue: 0,
            totalBucket: 0,
          },
          derivedFormula: null,
          glbMetricId: -1,
          measure: {
            metric: 'Processes Waiting For Run Time',
            metricId: 1,
            mg: 'SysStats Linux Extended',
            mgId: 10108,
            mgType: 'System Metrics',
            mgTypeId: -1,
          },
          subject: {
            tags: [
              {
                key: 'Tier',
                value: 'Cavisson',
              },
              {
                key: 'Server',
                value: 'NDAppliance',
              },
            ],
          },
        },
      ],
      selfTrend: 0,
    },
    description: 'Processes Waiting For Run Time - Cavisson>NDAppliance',
    graphs: {
      widgetGraphs: [
        {
          arrPanelGraphFieldInfo: null,
          color: null,
          dataCenterName: null,
          dataSourceType: 0,
          derFormula: null,
          derGraphDesc: null,
          derGraphId: -1,
          derGraphName: null,
          derGraphNumber: -1,
          derGroupDesc: null,
          derGroupID: -1,
          derGroupName: null,
          derived: false,
          derivedArithmeticMultiDcProperty: null,
          derReportName: null,
          graphDatatype: null,
          graphFormula: null,
          graphId: 1,
          graphStatsType: 0,
          graphUniqueKeyDTO: {
            dataCenterName: null,
            dataSourceType: 0,
            derivedGraphFormulaInfo: null,
            graphDataIndex: -1,
            graphDataType: -1,
            graphFieldInfo: null,
            graphFormula: -1,
            graphId: 1,
            graphState: 1,
            graphStatsType: 0,
            graphType: -1,
            groupId: 10108,
            groupIdGraphIdVectName: '10108.1.Cavisson>NDAppliance',
            vectorName: 'Cavisson>NDAppliance',
            vectorNameIdx: 0,
          },
          groupBy: false,
          groupByMetaData: null,
          groupId: 10108,
          metaDataInfo: null,
          originalFormula: null,
          pattern: null,
          patternFormula: null,
          scaleFactor: 0,
          selected: false,
          tavgSet: null,
          vecName: 'Cavisson>NDAppliance',
          visible: true,
        },
      ],
      widgetRule: null,
    },
    icon: '',
    iconTooltip: 'Advance Settings',
    id: 'Processes Waiting For Run Time - Cavisson>NDAppliance',
    include: false,
    layout: {
      cols: 10,
      rows: 4,
      x: 0,
      y: 0,
    },
    name: 'Processes Waiting For Run Time - Cavisson>NDAppliance',
    ruleType: 0,
    scaleBySelectedGraph: null,
    scaleMode: 1,
    settings: {
      alertOverlay: false,
      alertOverlayInfo: null,
      baselineCompare: {
        critical: '0',
        enabled: false,
        major: '0',
        minor: '0',
        trendMode: '0',
      },
      blank: false,
      caption: {
        caption: 'Processes Waiting For Run Time - Cavisson>NDAppliance',
        overriden: false,
      },
      chartType: 0,
      dashboardGraphTime: {
        id: 'LIVE1',
        name: 'Last 10 Minutes',
      },
      dataSourceType: 'METRIC',
      graphFilter: null,
      graphStatsType: 'NA',
      link: null,
      monochromatic: false,
      multiDial: {
        count: 2,
        enabled: false,
      },
      panelFavName: '',
      panelFavRelativePath: '',
      parametrization: false,
      selectedFavLevel: null,
      types: {
        data: null,
        file: null,
        graph: {
          arrPct: null,
          bgColor: 'transparent',
          bold: false,
          dialMeterExp: null,
          displayWidgetFontColor: '',
          displayWidgetFontFamily: 'Select Font Family',
          geomap: {
            colorOptionForGeoMap: 0,
            extendedFilter: null,
            geoMapThreshold: '',
            highToLow: null,
            monochronicColorBandHighToLow: false,
            redToGreen: false,
          },
          gridLineWidth: 0.4,
          iconColor: 'black',
          iconSelected: true,
          italic: false,
          legendAlignmentOnWidget: '',
          pctOrSlabValue: 0,
          primaryYAxisLabel: null,
          secondaryYAxisLabel: null,
          selectedWidgetTimeDelay: -1,
          showChartValue: false,
          showLegendOnWidget: false,
          showLegends: true,
          type: 0,
          underline: false,
          xAxis: true,
          yAxis: true,
        },
        grid: null,
        image: null,
        systemHealth: null,
        table: null,
        text: null,
      },
      viewBy: {
        list: [
          {
            id: '1 Min',
            name: '1 Min',
          },
          {
            id: '4 Min',
            name: '4 Min',
          },
          {
            id: '5 Min',
            name: '5 Min',
          },
          {
            id: '10 Min',
            name: '10 Min',
          },
        ],
        selected: '60',
      },
      widgetDrillDown: false,
      widgetFilter: null,
    },
    type: 'GRAPH',
    widgetIndex: 0,
  },
};

export const DEFAULT_GRAPH_SETTINGS: DashboardWidgetSettings = {
  monochromatic: false,
  dataSourceType: 'METRIC',
  baselineCompare: {
    enabled: false,
    trendMode: '0',
    critical: '0',
    major: '0',
    minor: '0',
  },
  types: {
    graph: {
      type: 0,
      geomap: {
        redToGreen: false,
        extendedFilter: {
          enable: false,
          type: 0,
          healthType: 0,
          textPattern: '',
        },
        geoMapThreshold: '',
        monochronicColorBandHighToLow: false,
        colorOptionForGeoMap: 0,
      },
      gridLineWidth: 0.4,
      xAxis: true,
      yAxis: true,
      underline: false,
      italic: false,
      bold: false,
      iconSelected: true,
      displayWidgetFontColor: '',
      bgColor: 'transparent',
      iconColor: 'black',
      displayWidgetFontFamily: 'Select Font Family',
      showLegends: false,
      showLegendOnWidget: false,
      showChartValue: false,
      selectedWidgetTimeDelay: 0,
      legendAlignmentOnWidget: 'center',
      pctOrSlabValue: 0,
      dialMeterExp: '',
    },
  },
  caption: {
    overriden: false,
    caption: '',
  },
  graphStatsType: '0',
  graphFilter: [],
  multiDial: { enabled: false, count: 2 },
  blank: false,
  alertOverlay: false,
  widgetDrillDown: false,
  selectedFavLevel: '',
  panelFavName: 'undefined',
  panelFavRelativePath: '',
  parametrization: false,
  chartType: 0,
  dataFilter: [0, 1, 2, 3, 4, 5],
};

export const DEFAULT_DATA_SETTINGS: DashboardWidgetSettings = {
  monochromatic: false,
  dataSourceType: 'METRIC',
  baselineCompare: {
    enabled: false,
    trendMode: '0',
    critical: '0',
    major: '0',
    minor: '0',
  },
  types: {
    data: {
      dataAttrName: 'avg',
      dataDisplayName: 'Data Average',
      dataImgName: 'icons8 icons8-power-bi',
      bgColor: '#009973',
      fontColor: 'black',
      prefix: '',
      suffix: '',
      showIcon: true,
      showTitleBar: true,
      valueFontColor: '',
      textFontColor: '',
      displayFontSize: '18',
      displayFontFamily: 'Arial',
      valueFontSize: '15',
      valueFontFamily: 'Arial',
      decimalFormat: 'dec_3',
    },
  },
  caption: {
    overriden: false,
    caption: '',
  },
  graphStatsType: '0',
  graphFilter: [],
  multiDial: { enabled: false, count: 2 },
  blank: false,
  alertOverlay: false,
  widgetDrillDown: false,
  selectedFavLevel: '0',
  panelFavName: 'undefined',
  panelFavRelativePath: '',
  parametrization: false,
  chartType: 0,
  dataFilter: [0, 1, 2, 3, 4, 5],
};

export const DEFAULT_TABULAR_SETTINGS: DashboardWidgetSettings = {
  monochromatic: false,
  dataSourceType: 'METRIC',
  baselineCompare: {
    enabled: false,
    trendMode: '0',
    critical: '0',
    major: '0',
    minor: '0',
  },
  types: {
    table: {
      enableSorting: "true",
      enableColumnResizing: "true",
      enableFiltering: "false",
      enableGridMenu: "false",
      showGridFooter: "false",
      fastWatch: "false",
      rowHeight: '16',
      tableHeight: '100',
      tableType: '0',
      cols: [
        {
          field: 'measure.metric',
          width: '40%',
          minWidth: '150',
          headerCellClass: 'grid-align-center',
          type: 'number',
          displayName: 'Metric Name',
          headerTooltip: '',
          cellFilter: '',
        },
        {
          field: 'summary.avg',
          width: '20%',
          minWidth: '40',
          headerCellClass: 'grid-align-center',
          type: 'number',
          displayName: 'Average',
          headerTooltip: '',
          cellFilter: '',
        },
        {
          field: 'summary.min',
          width: '20%',
          minWidth: '40',
          headerCellClass: 'grid-align-center',
          type: 'number',
          displayName: 'Minimum',
          headerTooltip: '',
          cellFilter: '',
        },
        {
          field: 'summary.max',
          width: '20%',
          minWidth: '40',
          headerCellClass: 'grid-align-center',
          type: 'number',
          displayName: 'Maximum',
          headerTooltip: '',
          cellFilter: '',
        },
      ],
      bgColor: 'transparent',
      format: 'dec_3',
    },
  },
  caption: {
    overriden: false,
    caption: '',
  },
  graphStatsType: '0',
  graphFilter: [],
  multiDial: { enabled: false, count: 2 },
  blank: false,
  alertOverlay: false,
  widgetDrillDown: false,
  selectedFavLevel: '0',
  panelFavName: 'undefined',
  panelFavRelativePath: '',
  parametrization: false,
  chartType: 0,
  dataFilter: [0, 1, 2, 3, 4, 5],
};

export const DEFAULT_HEALTH_SETTINGS: DashboardWidgetSettings = {
  monochromatic: false,
  dataSourceType: 'METRIC',
  baselineCompare: {
    enabled: false,
    trendMode: '0',
    critical: '0',
    major: '0',
    minor: '0',
  },
  types: {
    systemHealth: {
      dataAttrName: 'avg',
      dataImgName: 'icons8 icons8-power-bi',
      bgColor: '#FFFFFF',
      fontColor: 'black',
      showIcon: true,
      showTitleBar: true,
      healthWidgetSeverityDef: {
        criticalMSRString: '>',
        criticalValue: 100.0,
        majorMSRString: '>',
        majorValue: 200.0,
      },
      healthWidgetRuleInfo: {
        criticalPct: 90.0,
        criticalSeverity: 'Major',
        criticalCondition: '||',
        criticalAnotherPct: 100.0,
        criticalAnotherSeverity: 'Critical',
        majorPct: 50.0,
        majorSeverity: 'Major',
        majorCondition: '||',
        majorAnotherPct: 80.0,
        majorAnotherSeverity: 'Critical',
        showSecdCondForCritical: true,
        showSecdCondForMajor: true,
        criticalOperator: false,
        majorOperator: false,
      },
      severity: 'Normal',
      graphNameOnTop: false,
    },
  },
  caption: {
    overriden: false,
    caption: '',
  },
  graphStatsType: '0',
  graphFilter: [],
  multiDial: { enabled: false, count: 2 },
  blank: false,
  alertOverlay: false,
  widgetDrillDown: false,
  selectedFavLevel: '0',
  panelFavName: 'undefined',
  panelFavRelativePath: '',
  parametrization: false,
  chartType: 0,
  dataFilter: [0, 1, 2, 3, 4, 5],
};

export const DEFAULT_LABEL_SETTINGS: DashboardWidgetSettings = {
  monochromatic: false,
  dataSourceType: 'METRIC',
  baselineCompare: {
    enabled: false,
    trendMode: '0',
    critical: '0',
    major: '0',
    minor: '0',
  },
  types: {
    text: {
      text: 'label Widget',
      bold: '',
      italic: '',
      underline: '',
      align: 'center',
      showTextArea: false,
      fontSize: '22',
      fontFamily: "'Noto Sans', sans-serif",
      fontColor: '#000000',
      rotate: 'rotate(0deg)',
      origin: '0% 0%',
      height: '83px',
      width: '348px',
      bgColor: '#FFFFFF',
    },
  },
  caption: {
    overriden: false,
    caption: '',
  },
  graphStatsType: '0',
  graphFilter: [],
  multiDial: { enabled: false, count: 2 },
  blank: false,
  alertOverlay: false,
  widgetDrillDown: false,
  selectedFavLevel: '0',
  panelFavName: 'undefined',
  panelFavRelativePath: '',
  parametrization: false,
  chartType: 0,
  dataFilter: [0, 1, 2, 3, 4, 5],
};

export const DEFAULT_GROUP_WIDGET: DashboardGroupWidgetConfig = {
  layout: {
    id: 'Layout_AAvaibhavhealth',
    type: 'GRID',
    configGrid: {
      cols: 6,
      row: -1,
      rowHeight: 24,
      gridType: 'Fit',
    },
    name: 'Layout_AAvaibhavhealth',
    category: 'Default',
  },
  widgets: [ 
  ],
};

export const DEFAULT_IMAGE_SETTINGS: DashboardWidgetSettings = {
  monochromatic: false,
  dataSourceType: 'METRIC',
  baselineCompare: {
    enabled: false,
    trendMode: '0',
    critical: '0',
    major: '0',
    minor: '0',
  },
  types: {
    image: {
      imgPath:
        '/sys/webdashboard/layoutFiles/images/newLayoutMap_1615458322610.PNG',
      imageTitle: 'newLayoutMap',
      editCaption: false,
      bgColor: 'transparent',
    },
  },
  caption: { overriden: false },
  graphStatsType: '0',
  multiDial: { enabled: false, count: 2 },
  blank: true,
  alertOverlay: false,
  viewBy: { selected: '600' },
  dashboardGraphTime: { id: 'LIVE5', name: 'Last 4 Hours' },
  widgetDrillDown: false,
  panelFavName: '',
  panelFavRelativePath: '',
  parametrization: false,
  chartType: 0,
  dataFilter: [0, 1, 2, 3, 4, 5],
};

export const DEFAULT_FILE_SETTINGS: DashboardWidgetSettings = {
  monochromatic: false,
  dataSourceType: 'METRIC',
  baselineCompare: {
    enabled: false,
    trendMode: '0',
    critical: '0',
    major: '0',
    minor: '0',
  },
  types: {
    file: {
      filePath: '',
      delimiter: ',',
      fileWidgetTitle: '',
      userName: 'cavisson',
      bgColor: 'transparent',
    },
  },
  caption: { overriden: false },
  graphStatsType: '0',
  multiDial: { enabled: false, count: 2 },
  blank: true,
  alertOverlay: false,
  viewBy: { selected: '600' },
  dashboardGraphTime: { id: 'LIVE5', name: 'Last 4 Hours' },
  widgetDrillDown: false,
  panelFavName: '',
  panelFavRelativePath: '',
  parametrization: false,
  chartType: 0,
  dataFilter: [0, 1, 2, 3, 4, 5],
};

export const Dashboard = {
  favNameCtx: { name: 'imagefile', path: '/' },
  favDetailCtx: {
    layout: {
      id: 'Layout_imagefile',
      type: 'GRID',
      configGrid: {
        cols: 32,
        row: -1,
        rowHeight: 48,
        gridType: 'ScrollVertical',
      },
      configGallery: { enable: false },
      name: 'Layout_imagefile',
      category: 'Default',
    },
    globalFavCtx: {
      enableAlertOverlay: false,
      favName: 'imagefile',
      favRelPath: '/',
      layoutId: -1,
      favPublic: true,
      updateBy: 'cavisson',
      favDesc: 'NA',
      backToHealthWidget: false,
      parameteriazationMode: false,
      includeCurrentData: false,
      running: true,
      isShowDiscontinuedGraphs: false,
      ruleType: 0,
    },
    widgets: [
      {
        type: 'IMAGE',
        layout: { cols: 10, rows: 4, x: 0, y: 0 },
        settings: {
          monochromatic: false,
          dataSourceType: 'METRIC',
          baselineCompare: {
            enabled: false,
            trendMode: '0',
            critical: '0',
            major: '0',
            minor: '0',
          },
          types: {
            image: {
              imgPath:
                '/sys/webdashboard/layoutFiles/images/newLayoutMap_1615458322610.PNG',
              imageTitle: 'newLayoutMap',
              editCaption: false,
              bgColor: 'transparent',
            },
          },
          caption: { overriden: false },
          graphStatsType: '0',
          multiDial: { enabled: false, count: 2 },
          blank: true,
          alertOverlay: false,
          viewBy: { selected: '600' },
          dashboardGraphTime: { id: 'LIVE5', name: 'Last 4 Hours' },
          widgetDrillDown: false,
          panelFavName: '',
          panelFavRelativePath: '',
          parametrization: false,
          chartType: 0,
          dataFilter: [0, 1, 2, 3, 4, 5],
        },
        dataCtx: { derivedFlag: -1, gCtx: [], SelfTrend: 0, limit: 0 },
        dataAttrName: 'avg',
        scaleMode: 1,
        widgetIndex: 0,
        include: false,
        icon: '',
        iconTooltip: 'Advance Settings',
        ruleType: 0,
        graphs: {},
        graphSettings: {},
      },
      {
        type: 'FILE',
        layout: { cols: 10, rows: 4, x: 20, y: 0 },
        settings: {
          monochromatic: false,
          dataSourceType: 'METRIC',
          baselineCompare: {
            enabled: false,
            trendMode: '0',
            critical: '0',
            major: '0',
            minor: '0',
          },
          types: {
            file: {
              filePath: 'Financial Sample_1615458053873.csv',
              delimiter: ',',
              fileWidgetTitle: 'Financial Sample',
              userName: 'cavisson',
              bgColor: 'transparent',
            },
          },
          caption: { overriden: false },
          graphStatsType: '0',
          multiDial: { enabled: false, count: 2 },
          blank: true,
          alertOverlay: false,
          viewBy: { selected: '600' },
          dashboardGraphTime: { id: 'LIVE5', name: 'Last 4 Hours' },
          widgetDrillDown: false,
          panelFavName: '',
          panelFavRelativePath: '',
          parametrization: false,
          chartType: 0,
          dataFilter: [0, 1, 2, 3, 4, 5],
        },
        dataCtx: { derivedFlag: -1, gCtx: [], SelfTrend: 0, limit: 0 },
        dataAttrName: 'avg',
        scaleMode: 1,
        widgetIndex: 1,
        include: false,
        icon: '',
        iconTooltip: 'Advance Settings',
        ruleType: 0,
        graphs: {},
        graphSettings: {},
      },
    ],
    dashboardGraphTime: { id: 'LIVE5', name: 'Last 4 Hours' },
    viewBy: { selected: '600' },
    status: { code: 200, msg: 'success' },
    rsTime: { tomcat: 9 },
    interval: 60000,
    selectedWidgetIndex: 0,
    gdfVersion: '2',
    activePartitionName: '2',
    paused: true,
    showDiscontinued: false,
    updatedBy: 'cavisson',
    isPublic: true,
    dashboardGraphTimeMode: true,
    isTrendCompareData: false,
    getAllSamples: false,
    settings: {
      categoryGraphInfo: {
        categoryGroupId: 102,
        catGraphThreshold: [
          {
            categoryType: 'normal',
            range: 10.0,
            categoryGraphName: 'Transactions Normal Graph',
            categoryGraphColor: 'green',
          },
          {
            categoryType: 'slow',
            range: 20.0,
            categoryGraphName: 'Transactions Slow Graph',
            categoryGraphColor: 'orange',
          },
          {
            categoryType: 'verySlow',
            range: 30.0,
            categoryGraphName: 'Transactions Very Slow Graph',
            categoryGraphColor: 'red',
          },
        ],
      },
    },
    readWriteMode: 4,
    description: 'NA',
  },
  status: { code: 0, msg: 'OK' },
};
