import { ApplicationAgentTable } from "./application-agent.model";


export const APPLICATIONAGENT_TABLE: ApplicationAgentTable = {
    paginator: {
        first: 1,
        rows: 10,
        rowsPerPageOptions: [3, 5, 10, 25, 50, 100],
    },
    headers: [
        {
            cols: [
                {
                    label: 'Pid',
                    valueField: 'pId',
                    classes: 'text-left',
                    selected: true,
                    filter: {
                        isFilter: true,
                        type: 'contains',
                    },
                    isSort: true,
                },
                {
                    label: 'Tier',
                    valueField: 'tier',
                    classes: 'text-left',
                    selected: true,
                    filter: {
                        isFilter: true,
                        type: 'contains',
                    },
                    isSort: true,
                },
                {
                    label: 'Server',
                    valueField: 'server',
                    classes: 'text-left',
                    selected: true,
                    filter: {
                        isFilter: true,
                        type: 'contains',
                    },
                    isSort: true,
                },
                {
                    label: 'Instance',
                    valueField: 'instance',
                    classes: 'text-left',
                    selected: true,
                    filter: {
                        isFilter: true,
                        type: 'contains',
                    },
                    isSort: true,
                },
                {
                    label: 'Installation Dir',
                    valueField: 'installationDir',
                    classes: 'text-left',
                    selected: true,
                    filter: {
                        isFilter: true,
                        type: 'contains',
                    },
                    isSort: true,
                },
                {
                    label: 'Agent Type',
                    valueField: 'agentType',
                    classes: 'text-left',
                    selected: true,
                    filter: {
                        isFilter: true,
                        type: 'contains',
                    },
                    isSort: true,
                },
                {
                    label: 'Agent Start Time',
                    valueField: 'startTime',
                    classes: 'text-left',
                    selected: true,
                    filter: {
                        isFilter: true,
                        type: 'contains',
                    },
                    isSort: true,
                }

            ],
        },
    ],
    data: [
        {
            pId: '231781',
            tier: 'CC-E-FL-JAK-TP',
            server: 'CC-E-FL-JAK-TP-134',
            instance: 'tomcat',
            installationDir: 'opt/cavisson/netdiagnostics',
            agentType: 'Java',
            startTime: '07/15/20 01:48:01',
        },
        {
            pId: '231781',
            tier: 'CC-E-FL-JAK-TP',
            server: 'CC-E-FL-JAK-TP-134',
            instance: 'tomcat',
            installationDir: 'opt/cavisson/netdiagnostics',
            agentType: 'Java',
            startTime: '07/15/20 01:48:01',
        },{
            pId: '231781',
            tier: 'CC-E-FL-JAK-TP',
            server: 'CC-E-FL-JAK-TP-134',
            instance: 'tomcat',
            installationDir: 'opt/cavisson/netdiagnostics',
            agentType: 'Java',
            startTime: '07/15/20 01:48:01',
        },{
            pId: '231781',
            tier: 'CC-E-FL-JAK-TP',
            server: 'CC-E-FL-JAK-TP-134',
            instance: 'tomcat',
            installationDir: 'opt/cavisson/netdiagnostics',
            agentType: 'Java',
            startTime: '07/15/20 01:48:01',
        },{
            pId: '231781',
            tier: 'CC-E-FL-JAK-TP',
            server: 'CC-E-FL-JAK-TP-134',
            instance: 'tomcat',
            installationDir: 'opt/cavisson/netdiagnostics',
            agentType: 'Java',
            startTime: '07/15/20 01:48:01',
        },{
            pId: '231781',
            tier: 'CC-E-FL-JAK-TP',
            server: 'CC-E-FL-JAK-TP-134',
            instance: 'tomcat',
            installationDir: 'opt/cavisson/netdiagnostics',
            agentType: 'Java',
            startTime: '07/15/20 01:48:01',
        },{
            pId: '231781',
            tier: 'CC-E-FL-JAK-TP',
            server: 'CC-E-FL-JAK-TP-134',
            instance: 'tomcat',
            installationDir: 'opt/cavisson/netdiagnostics',
            agentType: 'Java',
            startTime: '07/15/20 01:48:01',
        },{
            pId: '231781',
            tier: 'CC-E-FL-JAK-TP',
            server: 'CC-E-FL-JAK-TP-134',
            instance: 'tomcat',
            installationDir: 'opt/cavisson/netdiagnostics',
            agentType: 'Java',
            startTime: '07/15/20 01:48:01',
        },{
            pId: '231781',
            tier: 'CC-E-FL-JAK-TP',
            server: 'CC-E-FL-JAK-TP-134',
            instance: 'tomcat',
            installationDir: 'opt/cavisson/netdiagnostics',
            agentType: 'Java',
            startTime: '07/15/20 01:48:01',
        },{
            pId: '231781',
            tier: 'CC-E-FL-JAK-TP',
            server: 'CC-E-FL-JAK-TP-134',
            instance: 'tomcat',
            installationDir: 'opt/cavisson/netdiagnostics',
            agentType: 'Java',
            startTime: '07/15/20 01:48:01',
        },{
            pId: '231781',
            tier: 'CC-E-FL-JAK-TP',
            server: 'CC-E-FL-JAK-TP-134',
            instance: 'tomcat',
            installationDir: 'opt/cavisson/netdiagnostics',
            agentType: 'Java',
            startTime: '07/15/20 01:48:01',
        },{
            pId: '231781',
            tier: 'CC-E-FL-JAK-TP',
            server: 'CC-E-FL-JAK-TP-134',
            instance: 'tomcat',
            installationDir: 'opt/cavisson/netdiagnostics',
            agentType: 'Java',
            startTime: '07/15/20 01:48:01',
        },{
            pId: '231781',
            tier: 'CC-E-FL-JAK-TP',
            server: 'CC-E-FL-JAK-TP-134',
            instance: 'tomcat',
            installationDir: 'opt/cavisson/netdiagnostics',
            agentType: 'Java',
            startTime: '07/15/20 01:48:01',
        },{
            pId: '231781',
            tier: 'CC-E-FL-JAK-TP',
            server: 'CC-E-FL-JAK-TP-134',
            instance: 'tomcat',
            installationDir: 'opt/cavisson/netdiagnostics',
            agentType: 'Java',
            startTime: '07/15/20 01:48:01',
        },{
            pId: '231781',
            tier: 'CC-E-FL-JAK-TP',
            server: 'CC-E-FL-JAK-TP-134',
            instance: 'tomcat',
            installationDir: 'opt/cavisson/netdiagnostics',
            agentType: 'Java',
            startTime: '07/15/20 01:48:01',
        },{
            pId: '231781',
            tier: 'CC-E-FL-JAK-TP',
            server: 'CC-E-FL-JAK-TP-134',
            instance: 'tomcat',
            installationDir: 'opt/cavisson/netdiagnostics',
            agentType: 'Java',
            startTime: '07/15/20 01:48:01',
        },{
            pId: '231781',
            tier: 'CC-E-FL-JAK-TP',
            server: 'CC-E-FL-JAK-TP-134',
            instance: 'tomcat',
            installationDir: 'opt/cavisson/netdiagnostics',
            agentType: 'Java',
            startTime: '07/15/20 01:48:01',
        },{
            pId: '231781',
            tier: 'CC-E-FL-JAK-TP',
            server: 'CC-E-FL-JAK-TP-134',
            instance: 'tomcat',
            installationDir: 'opt/cavisson/netdiagnostics',
            agentType: 'Java',
            startTime: '07/15/20 01:48:01',
        },{
            pId: '231781',
            tier: 'CC-E-FL-JAK-TP',
            server: 'CC-E-FL-JAK-TP-134',
            instance: 'tomcat',
            installationDir: 'opt/cavisson/netdiagnostics',
            agentType: 'Java',
            startTime: '07/15/20 01:48:01',
        },{
            pId: '231781',
            tier: 'CC-E-FL-JAK-TP',
            server: 'CC-E-FL-JAK-TP-134',
            instance: 'tomcat',
            installationDir: 'opt/cavisson/netdiagnostics',
            agentType: 'Java',
            startTime: '07/15/20 01:48:01',
        },{
            pId: '231781',
            tier: 'CC-E-FL-JAK-TP',
            server: 'CC-E-FL-JAK-TP-134',
            instance: 'tomcat',
            installationDir: 'opt/cavisson/netdiagnostics',
            agentType: 'Java',
            startTime: '07/15/20 01:48:01',
        },{
            pId: '231781',
            tier: 'CC-E-FL-JAK-TP',
            server: 'CC-E-FL-JAK-TP-134',
            instance: 'tomcat',
            installationDir: 'opt/cavisson/netdiagnostics',
            agentType: 'Java',
            startTime: '07/15/20 01:48:01',
        },{
            pId: '231781',
            tier: 'CC-E-FL-JAK-TP',
            server: 'CC-E-FL-JAK-TP-134',
            instance: 'tomcat',
            installationDir: 'opt/cavisson/netdiagnostics',
            agentType: 'Java',
            startTime: '07/15/20 01:48:01',
        },{
            pId: '231781',
            tier: 'CC-E-FL-JAK-TP',
            server: 'CC-E-FL-JAK-TP-134',
            instance: 'tomcat',
            installationDir: 'opt/cavisson/netdiagnostics',
            agentType: 'Java',
            startTime: '07/15/20 01:48:01',
        },{
            pId: '231781',
            tier: 'CC-E-FL-JAK-TP',
            server: 'CC-E-FL-JAK-TP-134',
            instance: 'tomcat',
            installationDir: 'opt/cavisson/netdiagnostics',
            agentType: 'Java',
            startTime: '07/15/20 01:48:01',
        },{
            pId: '231781',
            tier: 'CC-E-FL-JAK-TP',
            server: 'CC-E-FL-JAK-TP-134',
            instance: 'tomcat',
            installationDir: 'opt/cavisson/netdiagnostics',
            agentType: 'Java',
            startTime: '07/15/20 01:48:01',
        },{
            pId: '231781',
            tier: 'CC-E-FL-JAK-TP',
            server: 'CC-E-FL-JAK-TP-134',
            instance: 'tomcat',
            installationDir: 'opt/cavisson/netdiagnostics',
            agentType: 'Java',
            startTime: '07/15/20 01:48:01',
        },{
            pId: '231781',
            tier: 'CC-E-FL-JAK-TP',
            server: 'CC-E-FL-JAK-TP-134',
            instance: 'tomcat',
            installationDir: 'opt/cavisson/netdiagnostics',
            agentType: 'Java',
            startTime: '07/15/20 01:48:01',
        },{
            pId: '231781',
            tier: 'CC-E-FL-JAK-TP',
            server: 'CC-E-FL-JAK-TP-134',
            instance: 'tomcat',
            installationDir: 'opt/cavisson/netdiagnostics',
            agentType: 'Java',
            startTime: '07/15/20 01:48:01',
        },{
            pId: '231781',
            tier: 'CC-E-FL-JAK-TP',
            server: 'CC-E-FL-JAK-TP-134',
            instance: 'tomcat',
            installationDir: 'opt/cavisson/netdiagnostics',
            agentType: 'Java',
            startTime: '07/15/20 01:48:01',
        },{
            pId: '231781',
            tier: 'CC-E-FL-JAK-TP',
            server: 'CC-E-FL-JAK-TP-134',
            instance: 'tomcat',
            installationDir: 'opt/cavisson/netdiagnostics',
            agentType: 'Java',
            startTime: '07/15/20 01:48:01',
        },{
            pId: '231781',
            tier: 'CC-E-FL-JAK-TP',
            server: 'CC-E-FL-JAK-TP-134',
            instance: 'tomcat',
            installationDir: 'opt/cavisson/netdiagnostics',
            agentType: 'Java',
            startTime: '07/15/20 01:48:01',
        },{
            pId: '231781',
            tier: 'CC-E-FL-JAK-TP',
            server: 'CC-E-FL-JAK-TP-134',
            instance: 'tomcat',
            installationDir: 'opt/cavisson/netdiagnostics',
            agentType: 'Java',
            startTime: '07/15/20 01:48:01',
        },{
            pId: '231781',
            tier: 'CC-E-FL-JAK-TP',
            server: 'CC-E-FL-JAK-TP-134',
            instance: 'tomcat',
            installationDir: 'opt/cavisson/netdiagnostics',
            agentType: 'Java',
            startTime: '07/15/20 01:48:01',
        },{
            pId: '231781',
            tier: 'CC-E-FL-JAK-TP',
            server: 'CC-E-FL-JAK-TP-134',
            instance: 'tomcat',
            installationDir: 'opt/cavisson/netdiagnostics',
            agentType: 'Java',
            startTime: '07/15/20 01:48:01',
        },{
            pId: '231781',
            tier: 'CC-E-FL-JAK-TP',
            server: 'CC-E-FL-JAK-TP-134',
            instance: 'tomcat',
            installationDir: 'opt/cavisson/netdiagnostics',
            agentType: 'Java',
            startTime: '07/15/20 01:48:01',
        },{
            pId: '231781',
            tier: 'CC-E-FL-JAK-TP',
            server: 'CC-E-FL-JAK-TP-134',
            instance: 'tomcat',
            installationDir: 'opt/cavisson/netdiagnostics',
            agentType: 'Java',
            startTime: '07/15/20 01:48:01',
        },{
            pId: '231781',
            tier: 'CC-E-FL-JAK-TP',
            server: 'CC-E-FL-JAK-TP-134',
            instance: 'tomcat',
            installationDir: 'opt/cavisson/netdiagnostics',
            agentType: 'Java',
            startTime: '07/15/20 01:48:01',
        },{
            pId: '231781',
            tier: 'CC-E-FL-JAK-TP',
            server: 'CC-E-FL-JAK-TP-134',
            instance: 'tomcat',
            installationDir: 'opt/cavisson/netdiagnostics',
            agentType: 'Java',
            startTime: '07/15/20 01:48:01',
        },{
            pId: '231781',
            tier: 'CC-E-FL-JAK-TP',
            server: 'CC-E-FL-JAK-TP-134',
            instance: 'tomcat',
            installationDir: 'opt/cavisson/netdiagnostics',
            agentType: 'Java',
            startTime: '07/15/20 01:48:01',
        },{
            pId: '231781',
            tier: 'CC-E-FL-JAK-TP',
            server: 'CC-E-FL-JAK-TP-134',
            instance: 'tomcat',
            installationDir: 'opt/cavisson/netdiagnostics',
            agentType: 'Java',
            startTime: '07/15/20 01:48:01',
        },{
            pId: '231781',
            tier: 'CC-E-FL-JAK-TP',
            server: 'CC-E-FL-JAK-TP-134',
            instance: 'tomcat',
            installationDir: 'opt/cavisson/netdiagnostics',
            agentType: 'Java',
            startTime: '07/15/20 01:48:01',
        },{
            pId: '231781',
            tier: 'CC-E-FL-JAK-TP',
            server: 'CC-E-FL-JAK-TP-134',
            instance: 'tomcat',
            installationDir: 'opt/cavisson/netdiagnostics',
            agentType: 'Java',
            startTime: '07/15/20 01:48:01',
        },{
            pId: '231781',
            tier: 'CC-E-FL-JAK-TP',
            server: 'CC-E-FL-JAK-TP-134',
            instance: 'tomcat',
            installationDir: 'opt/cavisson/netdiagnostics',
            agentType: 'Java',
            startTime: '07/15/20 01:48:01',
        },

    ],
    tableFilter: true,
};
