import { Table } from 'src/app/shared/table/table.model';

export const ONGOING_TEST_TABLE_DATA: Table = {

    paginator: {
      first: 1,
      rows: 33,
      rowsPerPageOptions: [5, 10, 25, 50, 100],
    },

    headers: [
      {
        cols: [
          {
            label: 'DNS Name',
            valueField: 'dnsName',
            classes: 'text-left',
            selected: true,
            filter: {
              isFilter: true,
              type: 'contains',
            },
            isSort: true,
          },
          {
            label: 'Appliance',
            valueField: 'appliance',
            classes: 'text-left',
            selected: true,
            filter: {
              isFilter: true,
              type: 'contains',
            },
            isSort: true,
          },
          {
            label: 'Controller',
            valueField: 'controller',
            classes: 'text-left',
            selected: true,
            filter: {
              isFilter: true,
              type: 'contains',
            },
            isSort: true,
          },
          {
            label: 'Test Run',
            valueField: 'testRun',
            classes: 'text-left',
            selected: true,
            filter: {
              isFilter: true,
              type: 'contains',
            },
            isSort: true,
          },
          {
            label: 'Test Name',
            valueField: 'testName',
            classes: 'text-left',
            selected: true,
            filter: {
              isFilter: true,
              type: 'contains',
            },
            isSort: true,
          },
          {
            label: 'Scenario',
            valueField: 'scenario',
            classes: 'text-left',
            selected: true,
            filter: {
              isFilter: true,
              type: 'contains',
            },
            isSort: true,
          },
          {
            label: 'Environment',
            valueField: 'environment',
            classes: 'text-left',
            selected: true,
            filter: {
              isFilter: true,
              type: 'contains',
            },
            isSort: true,
          },
          {
            label: 'Start Time',
            valueField: 'startTime',
            classes: 'text-left',
            selected: true,
            filter: {
              isFilter: true,
              type: 'contains',
            },
            isSort: true,
          },
          {
            label: 'Run Time',
            valueField: 'runTime',
            classes: 'text-left',
            selected: true,
            filter: {
              isFilter: true,
              type: 'contains',
            },
            isSort: true,
          },
          {
            label: 'Started By',
            valueField: 'startedBy',
            classes: 'text-left',
            selected: true,
            filter: {
              isFilter: true,
              type: 'contains',
            },
            isSort: true,
          },
          {
            label: 'Product Name',
            valueField: 'productName',
            classes: 'text-left',
            selected: true,
            filter: {
              isFilter: true,
              type: 'contains',
            },
            isSort: true,
          },
        ],
      },
    ],
    data: [
      {
        dnsName: 'CC-E-OH-C07',
        appliance: '84.105.52.73.8001',
        controller: 'KO_MCCM_01',
        testRun: '32223',
        testName: 'CC-E-OH-C07',
        scenario: 'CC-E-OH-C07',
        environment: 'CC-E-OH-C07',
        startTime: '1.39.45.54',
        runTime: '00:12:23:45',
        startedBy: 'Cavisson',
        productName: 'NS > NO',
      },
      {
        dnsName: 'CC-E-OH-C07',
        appliance: '84.105.52.73.8001',
        controller: 'KO_MCCM_01',
        testRun: '32223',
        testName: 'CC-E-OH-C07',
        scenario: 'CC-E-OH-C07',
        environment: 'CC-E-OH-C07',
        startTime: '1.39.45.54',
        runTime: '00:12:23:45',
        startedBy: 'Cavisson',
        productName: 'NS > NO',
      },
      {
        dnsName: 'CC-E-OH-C07',
        appliance: '84.105.52.73.8001',
        controller: 'KO_MCCM_01',
        testRun: '32223',
        testName: 'CC-E-OH-C07',
        scenario: 'CC-E-OH-C07',
        environment: 'CC-E-OH-C07',
        startTime: '1.39.45.54',
        runTime: '00:12:23:45',
        startedBy: 'Cavisson',
        productName: 'NS > NO',
      },
      {
        dnsName: 'CC-E-OH-C07',
        appliance: '84.105.52.73.8001',
        controller: 'KO_MCCM_01',
        testRun: '32223',
        testName: 'CC-E-OH-C07',
        scenario: 'CC-E-OH-C07',
        environment: 'CC-E-OH-C07',
        startTime: '1.39.45.54',
        runTime: '00:12:23:45',
        startedBy: 'Cavisson',
        productName: 'NS > NO',
      },
      {
        dnsName: 'CC-E-OH-C07',
        appliance: '84.105.52.73.8001',
        controller: 'KO_MCCM_01',
        testRun: '32223',
        testName: 'CC-E-OH-C07',
        scenario: 'CC-E-OH-C07',
        environment: 'CC-E-OH-C07',
        startTime: '1.39.45.54',
        runTime: '00:12:23:45',
        startedBy: 'Cavisson',
        productName: 'NS > NO',
      },
      {
        dnsName: 'CC-E-OH-C07',
        appliance: '84.105.52.73.8001',
        controller: 'KO_MCCM_01',
        testRun: '32223',
        testName: 'CC-E-OH-C07',
        scenario: 'CC-E-OH-C07',
        environment: 'CC-E-OH-C07',
        startTime: '1.39.45.54',
        runTime: '00:12:23:45',
        startedBy: 'Cavisson',
        productName: 'NS > NO',
      },
      {
        dnsName: 'CC-E-OH-C07',
        appliance: '84.105.52.73.8001',
        controller: 'KO_MCCM_01',
        testRun: '32223',
        testName: 'CC-E-OH-C07',
        scenario: 'CC-E-OH-C07',
        environment: 'CC-E-OH-C07',
        startTime: '1.39.45.54',
        runTime: '00:12:23:45',
        startedBy: 'Cavisson',
        productName: 'NS > NO',
      },
      {
        dnsName: 'CC-E-OH-C07',
        appliance: '84.105.52.73.8001',
        controller: 'KO_MCCM_01',
        testRun: '32223',
        testName: 'CC-E-OH-C07',
        scenario: 'CC-E-OH-C07',
        environment: 'CC-E-OH-C07',
        startTime: '1.39.45.54',
        runTime: '00:12:23:45',
        startedBy: 'Cavisson',
        productName: 'NS > NO',
      },
      {
        dnsName: 'CC-E-OH-C07',
        appliance: '84.105.52.73.8001',
        controller: 'KO_MCCM_01',
        testRun: '32223',
        testName: 'CC-E-OH-C07',
        scenario: 'CC-E-OH-C07',
        environment: 'CC-E-OH-C07',
        startTime: '1.39.45.54',
        runTime: '00:12:23:45',
        startedBy: 'Cavisson',
        productName: 'NS > NO',
      },
      {
        dnsName: 'CC-E-OH-C07',
        appliance: '84.105.52.73.8001',
        controller: 'KO_MCCM_01',
        testRun: '32223',
        testName: 'CC-E-OH-C07',
        scenario: 'CC-E-OH-C07',
        environment: 'CC-E-OH-C07',
        startTime: '1.39.45.54',
        runTime: '00:12:23:45',
        startedBy: 'Cavisson',
        productName: 'NS > NO',
      },
      {
        dnsName: 'CC-E-OH-C07',
        appliance: '84.105.52.73.8001',
        controller: 'KO_MCCM_01',
        testRun: '32223',
        testName: 'CC-E-OH-C07',
        scenario: 'CC-E-OH-C07',
        environment: 'CC-E-OH-C07',
        startTime: '1.39.45.54',
        runTime: '00:12:23:45',
        startedBy: 'Cavisson',
        productName: 'NS > NO',
      },
      {
        dnsName: 'CC-E-OH-C07',
        appliance: '84.105.52.73.8001',
        controller: 'KO_MCCM_01',
        testRun: '32223',
        testName: 'CC-E-OH-C07',
        scenario: 'CC-E-OH-C07',
        environment: 'CC-E-OH-C07',
        startTime: '1.39.45.54',
        runTime: '00:12:23:45',
        startedBy: 'Cavisson',
        productName: 'NS > NO',
      },
      {
        dnsName: 'CC-E-OH-C07',
        appliance: '84.105.52.73.8001',
        controller: 'KO_MCCM_01',
        testRun: '32223',
        testName: 'CC-E-OH-C07',
        scenario: 'CC-E-OH-C07',
        environment: 'CC-E-OH-C07',
        startTime: '1.39.45.54',
        runTime: '00:12:23:45',
        startedBy: 'Cavisson',
        productName: 'NS > NO',
      },
      {
        dnsName: 'CC-E-OH-C07',
        appliance: '84.105.52.73.8001',
        controller: 'KO_MCCM_01',
        testRun: '32223',
        testName: 'CC-E-OH-C07',
        scenario: 'CC-E-OH-C07',
        environment: 'CC-E-OH-C07',
        startTime: '1.39.45.54',
        runTime: '00:12:23:45',
        startedBy: 'Cavisson',
        productName: 'NS > NO',
      },
    ],
    tableFilter: false,
  };