import { MethodTimingData } from './method-timing.model';

export const METHOD_TIMING_DATA: MethodTimingData = {
  panels: [
    {
      label: 'Method Timing',
      collapsed: false,
      headers: [
        {
          cols: [
            {
              label: 'Package',
              colspan: 1,
              rowspan: 1,
              valueField: 'pN',
              classes: 'text-center',
              dataClasses: 'text-right',
              selected: true,
              filter: {
                isFilter: true,
                type: 'contain',
              },
              isSort: true,
              severityColorField: true,
            },
            {
              label: 'Method',
              colspan: 1,
              rowspan: 1,
              valueField: 'mN',
              classes: 'text-center',
              dataClasses: 'text-right',
              selected: true,
              filter: {
                isFilter: true,
                type: 'contain',
              },
              isSort: true,
              severityColorField: false,
              urlField: true,
            },
            {
              label: 'Class',
              colspan: 1,
              rowspan: 1,
              valueField: 'cN',
              classes: 'text-center',
              dataClasses: 'text-right',
              selected: true,
              filter: {
                isFilter: true,
                type: 'contain',
              },
              isSort: true,
              severityColorField: false,
            },
            {
              label: 'FunctionalGroup',
              colspan: 1,
              rowspan: 1,
              valueField: 'fG',
              classes: 'text-center',
              dataClasses: 'text-right',
              selected: true,
              filter: {
                isFilter: true,
                type: 'contain',
              },
              isSort: true,
              severityColorField: false,
            },
            {
              label: 'Fully Qualified Name With Signature',
              colspan: 1,
              rowspan: 1,
              valueField: 'eN',
              classes: 'text-center',
              dataClasses: 'text-right',
              selected: false,
              filter: {
                isFilter: true,
                type: 'contain',
              },
              isSort: true,
              severityColorField: false,
            },
            {
              label: 'Percentage',
              colspan: 1,
              rowspan: 1,
              valueField: 'percent',
              classes: 'text-center',
              dataClasses: 'text-right',
              selected: true,
              filter: {
                isFilter: true,
                type: 'contain',
              },
              isSort: true,
              severityColorField: false,
            },
            {
              label: 'Cumulative Self Time(sec)',
              colspan: 1,
              rowspan: 1,
              valueField: 'sTOrg',
              classes: 'text-center',
              dataClasses: 'text-right',
              selected: true,
              filter: {
                isFilter: true,
                type: 'contain',
              },
              isSort: true,
              severityColorField: false,
            },
            {
              label: 'Avg Self Time(sec)',
              colspan: 1,
              rowspan: 1,
              valueField: 'avgST',
              classes: 'text-center',
              dataClasses: 'text-right',
              selected: true,
              filter: {
                isFilter: true,
                type: 'contain',
              },
              isSort: true,
              severityColorField: false,
            },
            {
              label: 'CumWallTime(sec)',
              colspan: 1,
              rowspan: 1,
              valueField: 'totWT',
              classes: 'text-center',
              dataClasses: 'text-right',
              selected: true,
              filter: {
                isFilter: true,
                type: 'contain',
              },
              isSort: true,
              severityColorField: false,
            },
            {
              label: 'Cumulative CPU Self Time(sec)',
              colspan: 1,
              rowspan: 1,
              valueField: 'cumCPUST',
              classes: 'text-center',
              dataClasses: 'text-right',
              selected: true,
              filter: {
                isFilter: true,
                type: 'contain',
              },
              isSort: true,
              severityColorField: false,
            },
            {
              label: 'AvgCpuSelfTime(ms)',
              colspan: 1,
              rowspan: 1,
              valueField: 'avgCPUST',
              classes: 'text-center',
              dataClasses: 'text-right',
              selected: true,
              filter: {
                isFilter: true,
                type: 'contain',
              },
              isSort: true,
              severityColorField: false,
            },
            {
              label: 'Avg Wall Time(sec)',
              colspan: 1,
              rowspan: 1,
              valueField: 'avgWT',
              classes: 'text-center',
              dataClasses: 'text-right',
              selected: true,
              filter: {
                isFilter: true,
                type: 'contain',
              },
              isSort: true,
              severityColorField: false,
            },
            {
              label: 'Executing Count',
              colspan: 1,
              rowspan: 1,
              valueField: 'eC',
              classes: 'text-center',
              dataClasses: 'text-right',
              selected: true,
              filter: {
                isFilter: true,
                type: 'contain',
              },
              isSort: true,
              severityColorField: false,
            },
            {
              label: 'Variance',
              colspan: 1,
              rowspan: 1,
              valueField: 'variance',
              classes: 'text-center',
              dataClasses: 'text-right',
              selected: true,
              filter: {
                isFilter: true,
                type: 'contain',
              },
              isSort: true,
              severityColorField: false,
            },
            {
              label: 'MaxSelfTime(ms)',
              colspan: 1,
              rowspan: 1,
              valueField: 'max',
              classes: 'text-center',
              dataClasses: 'text-right',
              selected: true,
              filter: {
                isFilter: true,
                type: 'contain',
              },
              isSort: true,
              severityColorField: false,
            },
            {
              label: 'MinSelfTime(ms)',
              colspan: 1,
              rowspan: 1,
              valueField: 'min',
              classes: 'text-center',
              dataClasses: 'text-right',
              selected: true,
              filter: {
                isFilter: true,
                type: 'contain',
              },
              isSort: true,
              severityColorField: false,
            },
            {
              label: 'IOTime',
              colspan: 1,
              rowspan: 1,
              valueField: 'iotime',
              classes: 'text-center',
              dataClasses: 'text-right',
              selected: true,
              filter: {
                isFilter: true,
                type: 'contain',
              },
              isSort: true,
              severityColorField: false,
            },
            {
              label: 'SuspensionTime(ms)',
              colspan: 1,
              rowspan: 1,
              valueField: 'suspensiontime',
              classes: 'text-center',
              dataClasses: 'text-right',
              selected: true,
              filter: {
                isFilter: true,
                type: 'contain',
              },
              isSort: true,
              severityColorField: false,
            },
            {
              label: 'SyncTime(ms)',
              colspan: 1,
              rowspan: 1,
              valueField: 'syncTime',
              classes: 'text-center',
              dataClasses: 'text-right',
              selected: true,
              filter: {
                isFilter: true,
                type: 'contain',
              },
              isSort: true,
              severityColorField: false,
            },
            {
              label: 'WaitTime(ms)',
              colspan: 1,
              rowspan: 1,
              valueField: 'waitTime',
              classes: 'text-center',
              dataClasses: 'text-right',
              selected: true,
              filter: {
                isFilter: true,
                type: 'contain',
              },
              isSort: true,
              severityColorField: false,
            },
          ],
        },
      ],
      paginator: {
        first: 0,
        rows: 33,
        rowsPerPageOptions: [3, 5, 10, 25, 50, 100],
      },
      tableFilter: true,
      severityBgColorField: 'severityColor',
      charts: [
        {
          title: 'Pie Chart',
          highchart: {
            chart: {
              type: 'pie',
            },
            tooltip: {
              pointFormat: '{series.name}: <b>{point.percentage:.1f}%</b>',
            },
            plotOptions: {
              pie: {
                size: '70%',
                borderWidth: 0,
                dataLabels: {
                  enabled: true,
                  format: '<b>{point.percentage:.1f} %',
                },
              },
            },
            series: [
              {
                name: 'Percentage Chart',
                colorByPoint: false,
                data: [
                  {
                    name: 'doFilter',
                    y: 99.986,
                  },
                  {
                    name: 'printStackTrace',
                    y: 0.01,
                  },
                  {
                    name: 'doAppend',
                    y: 0.003,
                  },
                  {
                    name: 'log',
                    y: 0,
                  },
                  {
                    name: 'invoke',
                    y: 0,
                  },
                  {
                    y: 0,
                  },
                ],
              },
            ] as Highcharts.SeriesOptionsType[],
          },
        },
        {
          title: 'Pie Chart',
          highchart: {
            chart: {
              type: 'pie',
            },
            tooltip: {
              pointFormat: '{series.name}: <b>{point.percentage:.1f}%</b>',
            },
            series: [
              {
                name: 'Count Chart',
                colorByPoint: false,
                data: [
                  {
                    name: 'doFilter',
                    y: 5,
                  },
                  {
                    name: 'printStackTrace',
                    y: 1,
                  },
                  {
                    name: 'doAppend',
                    y: 3,
                  },
                  {
                    name: 'log',
                    y: 1,
                  },
                  {
                    name: 'invoke',
                    y: 1,
                  },
                  {
                    y: 0,
                  },
                ],
              },
            ] as Highcharts.SeriesOptionsType[],
          },
        },
      ],
      data: [
        {
          eT: 0,
          eC: 5,
          eN:
            'org.apache.catalina.core.ApplicationFilterChain.doFilter(Ljavax/servlet/ServletRequest;Ljavax/servlet/ServletResponse;)V',
          fG: 'OTHER',
          cN: 'ApplicationFilterChain',
          pN: 'org.apache.catalina.core',
          mN: 'doFilter',
          sT: 85871,
          min: 0,
          max: 85871,
          variance: 0,
          ID: 20,
          percent: 99.986,
          avgST: 17174.2,
          totWT: 429415,
          avgWT: 85883,
          cT: '0.000',
          avgCPU: '0.000',
          cumCPUST: '0.000',
          avgCPUST: '0.000',
          sTOrg: '85.87',
          waitTime: '0',
          syncTime: '0',
          iotime: '0',
          suspensiontime: '0',
        },
        {
          eT: 0,
          eC: 1,
          eN: 'java.lang.Throwable.printStackTrace()V',
          fG: 'OTHER',
          cN: 'Throwable',
          pN: 'java.lang',
          mN: 'service',
          sT: 9,
          min: 9,
          max: 9,
          variance: 0,
          ID: 47,
          percent: 0.01,
          avgST: 9,
          totWT: 9,
          avgWT: 9,
          cT: '0.000',
          avgCPU: '0.000',
          cumCPUST: '0.000',
          avgCPUST: '0.000',
          sTOrg: '0.01',
          waitTime: '0',
          syncTime: '0',
          iotime: '0',
          suspensiontime: '0',
        },
        {
          eT: 0,
          eC: 3,
          eN:
            'org.apache.log4j.AppenderSkeleton.doAppend(Lorg/apache/log4j/spi/LoggingEvent;)V',
          fG: 'OTHER',
          cN: 'AppenderSkeleton',
          pN: 'org.apache.log4j',
          mN: 'doAppend',
          sT: 3,
          min: 0,
          max: 2,
          variance: 0,
          ID: 13,
          percent: 0.003,
          avgST: 1,
          totWT: 3,
          avgWT: 1,
          cT: '0.000',
          avgCPU: '0.000',
          cumCPUST: '0.000',
          avgCPUST: '0.000',
          sTOrg: '0.00',
          waitTime: '0',
          syncTime: '0',
          iotime: '0',
          suspensiontime: '0',
        },
        {
          eT: 0,
          eC: 1,
          eN:
            'java.util.logging.Logger.log(Ljava/util/logging/Level;Ljava/lang/String;Ljava/lang/Throwable;)V',
          fG: 'OTHER',
          cN: 'Logger',
          pN: 'java.util.logging',
          mN: 'log',
          sT: 0,
          min: 0,
          max: 0,
          variance: 0,
          ID: 35,
          percent: 0,
          avgST: 0,
          totWT: 0,
          avgWT: 0,
          cT: '0.000',
          avgCPU: '0.000',
          cumCPUST: '0.000',
          avgCPUST: '0.000',
          sTOrg: '0.00',
          waitTime: '0',
          syncTime: '0',
          iotime: '0',
          suspensiontime: '0',
        },
        {
          eT: 0,
          eC: 1,
          eN:
            'org.apache.catalina.valves.AccessLogValve.invoke(Lorg/apache/catalina/connector/Request;Lorg/apache/catalina/connector/Response;)V',
          fG: 'OTHER',
          cN: 'AccessLogValve',
          pN: 'org.apache.catalina.valves',
          mN: 'invoke',
          sT: 0,
          min: 0,
          max: 0,
          variance: 0,
          ID: 22,
          percent: 0,
          avgST: 0,
          totWT: 85883,
          avgWT: 85883,
          cT: '0.000',
          avgCPU: '0.000',
          cumCPUST: '0.000',
          avgCPUST: '0.000',
          sTOrg: '0.00',
          waitTime: '0',
          syncTime: '0',
          iotime: '0',
          suspensiontime: '0',
        },
      ],
    },
  ],
};
