import { GeolocationData } from './geolocation.model';

export const GEOLOCATION_DATA: GeolocationData = {
  geoLocationMenu: {
    applications: [
      {
        label: 'All',
        value: 'All',
      },
      {
        label: 'App123',
        value: 'App123',
      },
    ],
    health: [
      {
        label: 'Business',
        value: 'business',
      },
      {
        label: 'Infra Structure',
        value: 'infraStructure',
      },
    ],
    search: [
      {
        label: 'None',
        value: 'none',
      },
      {
        label: 'Critical',
        value: 'critical',
      },
      {
        label: 'Major',
        value: 'major',
      },
      {
        label: 'Store Name',
        value: 'storeName',
      },
      {
        label: 'Store City',
        value: 'storeCity',
      },
      {
        label: 'State Name',
        value: 'stateName',
      },
    ],
  },
  storeViewMapData: [
    {
      cityName: 'Havertown',
      color: 'G',
      count: 126,
      critical: 0,
      eps: 11.904761904761903,
      grpCount: 1,
      lat: '39.96917',
      lon: '-75.298203',
      major: 0,
      minor: 0,
      res: 230.03930952380952,
      stateName: 'Pennsylvania',
      storeName: 'Tomcat_Work4',
      tierName: 'POCApp',
      tps: 0.29957142857142854,
      country: 'United States of America',
    },
    {
      cityName: 'Olathe',
      color: 'GRY',
      count: 0,
      critical: 0,
      eps: 0,
      grpCount: 1,
      lat: '38.883701',
      lon: '-94.773621',
      major: 0,
      minor: 0,
      res: 0,
      stateName: 'Kansas',
      storeName: 'Olathe.ins_0231',
      tierName: '',
      tps: 0,
      country: 'United States of America',
    },
    {
      cityName: "Coeur D'Alene",
      color: 'GRY',
      count: 0,
      critical: 0,
      eps: 0,
      grpCount: 1,
      lat: '47.742454',
      lon: '-116.794589',
      major: 0,
      minor: 0,
      res: 0,
      stateName: 'Idaho',
      storeName: "Coeur D'Alene.ins_1165",
      tierName: '',
      tps: 0,
      country: 'United States of America',
    },
    {
      cityName: 'Kalamazoo',
      color: 'GRY',
      count: 0,
      critical: 0,
      eps: 0,
      grpCount: 1,
      lat: '42.29623',
      lon: '-85.651314',
      major: 0,
      minor: 0,
      res: 0,
      stateName: 'Michigan',
      storeName: 'Kalamazoo.ins_0611',
      tierName: '',
      tps: 0,
      country: 'United States of America',
    },
    {
      cityName: 'Edmond',
      color: 'GRY',
      count: 0,
      critical: 0,
      eps: 0,
      grpCount: 1,
      lat: '35.667534',
      lon: '-97.512871',
      major: 0,
      minor: 0,
      res: 0,
      stateName: 'Oklahoma',
      storeName: 'Edmond.ins_0487',
      tierName: '',
      tps: 0,
      country: 'United States of America',
    },
    {
      cityName: 'Fayetteville',
      color: 'GRY',
      count: 0,
      critical: 0,
      eps: 0,
      grpCount: 1,
      lat: '35.065208',
      lon: '-78.962112',
      major: 0,
      minor: 0,
      res: 0,
      stateName: 'NorthCarolina',
      storeName: 'Fayetteville.ins_0183',
      tierName: '',
      tps: 0,
      country: 'United States of America',
    },
    {
      cityName: 'Houston',
      color: 'GRY',
      count: 0,
      critical: 0,
      eps: 0,
      grpCount: 1,
      lat: '29.923088',
      lon: '-95.602165',
      major: 0,
      minor: 0,
      res: 0,
      stateName: 'Texas',
      storeName: 'Houston.ins_0545',
      tierName: '',
      tps: 0,
      country: 'United States of America',
    },
    {
      cityName: 'Deer Park',
      color: 'GRY',
      count: 0,
      critical: 0,
      eps: 0,
      grpCount: 1,
      lat: '40.761761',
      lon: '-73.312729',
      major: 0,
      minor: 0,
      res: 0,
      stateName: 'NewYork',
      storeName: 'Deer Park.ins_0376',
      tierName: '',
      tps: 0,
      country: 'United States of America',
    },
    {
      cityName: 'Lincolnwood',
      color: 'GRY',
      count: 0,
      critical: 0,
      eps: 0,
      grpCount: 1,
      lat: '42.011799',
      lon: '-87.712402',
      major: 0,
      minor: 0,
      res: 0,
      stateName: 'Illinois',
      storeName: 'Lincolnwood.ins_0648',
      tierName: '',
      tps: 0,
      country: 'United States of America',
    },
    {
      cityName: 'Okemos',
      color: 'GRY',
      count: 0,
      critical: 0,
      eps: 0,
      grpCount: 1,
      lat: '42.722801',
      lon: '-84.410667',
      major: 0,
      minor: 0,
      res: 0,
      stateName: 'Michigan',
      storeName: 'Okemos.ins_0738',
      tierName: '',
      tps: 0,
      country: 'United States of America',
    },
    {
      cityName: 'Lexington Park',
      color: 'GRY',
      count: 0,
      critical: 0,
      eps: 0,
      grpCount: 1,
      lat: '38.283861',
      lon: '-76.480117',
      major: 0,
      minor: 0,
      res: 0,
      stateName: 'Maryland',
      storeName: 'Lexington Park.ins_1317',
      tierName: '',
      tps: 0,
      country: 'United States of America',
    },
    {
      cityName: 'Auburn',
      color: 'GRY',
      count: 0,
      critical: 0,
      eps: 0,
      grpCount: 1,
      lat: '42.927387',
      lon: '-76.613252',
      major: 0,
      minor: 0,
      res: 0,
      stateName: 'NewYork',
      storeName: 'Auburn.corp_1079',
      tierName: '',
      tps: 0,
      country: 'United States of America',
    },
    {
      cityName: 'Woodland Park',
      color: 'GRY',
      count: 0,
      critical: 0,
      eps: 0,
      grpCount: 1,
      lat: '40.887203',
      lon: '-74.216698',
      major: 0,
      minor: 0,
      res: 0,
      stateName: 'NewJersey',
      storeName: 'Woodland Park.ins_0382',
      tierName: '',
      tps: 0,
      country: 'United States of America',
    },
    {
      cityName: 'Coral Springs',
      color: 'GRY',
      count: 0,
      critical: 0,
      eps: 0,
      grpCount: 1,
      lat: '26.238448',
      lon: '-80.247322',
      major: 0,
      minor: 0,
      res: 0,
      stateName: 'Florida',
      storeName: 'Coral Springs.corp_1428',
      tierName: '',
      tps: 0,
      country: 'United States of America',
    },
    {
      cityName: 'Lansing',
      color: 'GRY',
      count: 0,
      critical: 0,
      eps: 0,
      grpCount: 1,
      lat: '42.7411',
      lon: '-84.645454',
      major: 0,
      minor: 0,
      res: 0,
      stateName: 'Michigan',
      storeName: 'Lansing.ins_0372',
      tierName: '',
      tps: 0,
      country: 'United States of America',
    },
    {
      cityName: 'Fredericksburg',
      color: 'GRY',
      count: 0,
      critical: 0,
      eps: 0,
      grpCount: 1,
      lat: '38.216045',
      lon: '-77.502612',
      major: 0,
      minor: 0,
      res: 0,
      stateName: 'Virginia',
      storeName: 'Fredericksburg.ins_1083',
      tierName: '',
      tps: 0,
      country: 'United States of America',
    },
  ],
  mapOption: {
    mapKey: ['us', 'in'],
  },
  appStats: {
    tableFilter: true,
    headers: [
      {
        cols: [
          {
            label: 'APP NAME',
            valueField: 'appName',
            classes: 'text-left',
            filter: {
              isFilter: true,
              type: 'contains',
            },
            isSort: true,
            selected: true,
            width: '26%',
          },
          {
            label: 'TPS',
            valueField: 'tps',
            classes: 'text-right',
            filter: {
              isFilter: true,
              type: 'contains',
            },
            format: 'dec_3',
            isSort: true,
            selected: true,
            width: '16%',
          },
          {
            label: 'RES (MS)',
            valueField: 'res',
            classes: 'text-right',
            filter: {
              isFilter: true,
              type: 'contains',
            },
            isSort: true,
            selected: true,
            width: '24%',
          },
          {
            label: 'ERROR (%)',
            valueField: 'error',
            classes: 'text-right',
            filter: {
              isFilter: true,
              type: 'contains',
            },
            isSort: true,
            selected: true,
            width: '27%',
          },
        ],
      },
    ],
    data: [
      {
        appName: 'App 123',
        tps: '24.311535',
        res: '10',
        error: '1',
      },
      {
        appName: 'App 1234',
        tps: '4',
        res: '50',
        error: '0',
      },
      {
        appName: 'App 123',
        tps: '2',
        res: '10',
        error: '1',
      },
      {
        appName: 'App 1234',
        tps: '4',
        res: '50',
        error: '0',
      },
    ],
  },
  charts: {
    title: 'All (Business Health)',
    highchart: {
      chart: {
        type: 'pie',
        height: 200,
      },
      title: null,
      tooltip: {
        pointFormat: '{series.name}: <b>{point.percentage:.1f}</b>',
      },
      credits: {
        enabled: false,
      },
      legend: {
        enabled: true,
        align: 'left',
        verticalAlign: 'top',
        layout: 'vertical',
        x: 10,
        y: 40,
        symbolPadding: 10,
        symbolHeight: 12,
        symbolWidth: 12,
        symbolRadius: 0,
        itemMarginTop: 5,
        itemMarginBottom: 5,
        itemStyle: {
          fontWeight: 'bold',
          textOverflow: 'ellipsis',
        },
        labelFormat: '{name}' + ': ' + '{y}',
        backgroundColor: '#F4F8FB',
        itemCheckboxStyle: {
          width: 12,
          height: 12,
          textAlign: 'left',
          cursor: 'pointer',
        },
      },
      plotOptions: {
        pie: {
          size: '100%',
          dataLabels: {
            enabled: false,
          },
          showInLegend: true,
          showCheckbox: true,
          borderWidth: 1,
          borderColor: '#707070',
        },
      },
      series: [
        {
          name: 'Business Health',
          data: [
            {
              name: 'Critical',
              y: 23,
              marker: {
                fillColor: '#F04943',
                symbol: 'square',
              },
              color: '#F04943',
            },
            {
              name: 'Major',
              y: 15,
              marker: {
                fillColor: '#F6B4B4',
                symbol: 'square',
              },
              color: '#F6B4B4',
            },
            {
              name: 'Normal',
              y: 10,
              marker: {
                fillColor: '#707070',
                symbol: 'square',
              },
              color: '#707070',
            },
            {
              name: 'Inactive',
              y: 15,
              marker: {
                fillColor: '#FDFDFD',
                symbol: 'square',
                lineWidth: 2,
                lineColor: null,
              },
              color: '#FDFDFD',
            },
          ],
        },
      ] as Highcharts.SeriesOptionsType[],
    },
  },
};
