import { Table } from 'src/app/shared/table/table.model';

export const CHANNEL_TABLE: Table = {
  paginator: {
    first: 1,
    rows: 10,
    rowsPerPageOptions: [3, 5, 10, 25, 50, 100],
  },

  headers: [
    {
      cols: [
        {
          label: 'Name',
          valueField: 'name',
          classes: 'text-left',
          selected: true,
          isSort: true,
          filter: {
            isFilter: true,
            type: 'contains',
          },
        },
        {
          label: 'Rule',
          valueField: 'rule',
          classes: 'text-left',
          selected: true,
          isSort: true,
          filter: {
            isFilter: true,
            type: 'contains',
          },
        },
        {
          label: 'Rule Name',
          valueField: 'ruleName',
          classes: 'text-left',
          selected: true,
          isSort: true,
          filter: {
            isFilter: true,
            type: 'contains',
          },
        },
        {
          label: 'Rule Value',
          valueField: 'ruleValue',
          classes: 'text-left',
          selected: true,
          isSort: true,
          filter: {
            isFilter: true,
            type: 'contains',
          },
        },
        {
          label: 'Type',
          valueField: 'type',
          classes: 'text-left',
          selected: true,
          isSort: true,
          filter: {
            isFilter: true,
            type: 'contains',
          },
        },
      ],
    },
  ],
  data: [
    {
      name: 'Mobile',
      rule: 'Cookie1',
      ruleName: 'Mobile',
      ruleValue: 'Mobile',
      type: 'Application1',
    },
    {
      name: 'Mobile2',
      rule: 'Cookie',
      ruleName: 'Mobile',
      ruleValue: 'Mobile',
      type: 'Application',
    },
    {
      name: 'Mobile',
      rule: 'Cookie',
      ruleName: 'Mobile',
      ruleValue: 'Mobile',
      type: 'Application',
    },
    {
      name: 'Mobile',
      rule: 'Cookie',
      ruleName: 'Mobile',
      ruleValue: 'Mobile',
      type: 'Application',
    },
    {
      name: 'Mobile',
      rule: 'Cookie',
      ruleName: 'Mobile',
      ruleValue: 'Mobile',
      type: 'Application',
    },
    {
      name: 'Mobile',
      rule: 'Cookie',
      ruleName: 'Mobile',
      ruleValue: 'Mobile',
      type: 'Application',
    },
    {
      name: 'Mobile',
      rule: 'Cookie',
      ruleName: 'Mobile',
      ruleValue: 'Mobile',
      type: 'Application',
    },
    {
      name: 'Mobile',
      rule: 'Cookie',
      ruleName: 'Mobile',
      ruleValue: 'Mobile',
      type: 'Application',
    },
    {
      name: 'Mobile',
      rule: 'Cookie',
      ruleName: 'Mobile',
      ruleValue: 'Mobile',
      type: 'Application',
    },
    {
      name: 'Mobile',
      rule: 'Cookie',
      ruleName: 'Mobile',
      ruleValue: 'Mobile',
      type: 'Application',
    },
    {
      name: 'Mobile',
      rule: 'Cookie',
      ruleName: 'Mobile',
      ruleValue: 'Mobile',
      type: 'Application',
    },
    {
      name: 'Mobile',
      rule: 'Cookie',
      ruleName: 'Mobile',
      ruleValue: 'Mobile',
      type: 'Application',
    },
    {
      name: 'Mobile',
      rule: 'Cookie',
      ruleName: 'Mobile',
      ruleValue: 'Mobile',
      type: 'Application',
    },
    {
      name: 'Mobile',
      rule: 'Cookie',
      ruleName: 'Mobile',
      ruleValue: 'Mobile',
      type: 'Application',
    },
    {
      name: 'Mobile',
      rule: 'Cookie',
      ruleName: 'Mobile',
      ruleValue: 'Mobile',
      type: 'Application',
    },
    {
      name: 'Mobile',
      rule: 'Cookie',
      ruleName: 'Mobile',
      ruleValue: 'Mobile',
      type: 'Application',
    },
    {
      name: 'Mobile',
      rule: 'Cookie',
      ruleName: 'Mobile',
      ruleValue: 'Mobile',
      type: 'Application',
    },
    {
      name: 'Mobile',
      rule: 'Cookie',
      ruleName: 'Mobile',
      ruleValue: 'Mobile',
      type: 'Application',
    },
    {
      name: 'Mobile',
      rule: 'Cookie',
      ruleName: 'Mobile',
      ruleValue: 'Mobile',
      type: 'Application',
    },
    {
      name: 'Mobile',
      rule: 'Cookie',
      ruleName: 'Mobile',
      ruleValue: 'Mobile',
      type: 'Application',
    },
    {
      name: 'Mobile',
      rule: 'Cookie',
      ruleName: 'Mobile',
      ruleValue: 'Mobile',
      type: 'Application',
    },
    {
      name: 'Mobile',
      rule: 'Cookie',
      ruleName: 'Mobile',
      ruleValue: 'Mobile',
      type: 'Application',
    },
    {
      name: 'Mobile',
      rule: 'Cookie',
      ruleName: 'Mobile',
      ruleValue: 'Mobile',
      type: 'Application',
    },
    {
      name: 'Mobile',
      rule: 'Cookie',
      ruleName: 'Mobile',
      ruleValue: 'Mobile',
      type: 'Application',
    },
    {
      name: 'Mobile',
      rule: 'Cookie',
      ruleName: 'Mobile',
      ruleValue: 'Mobile',
      type: 'Application',
    },
    {
      name: 'Mobile',
      rule: 'Cookie',
      ruleName: 'Mobile',
      ruleValue: 'Mobile',
      type: 'Application',
    },

  ],
  tableFilter: true,
};
