import { Table } from 'src/app/shared/table/table.model';

export const CHECK_POINT_TABLE: Table = {

  paginator: {
    first: 1,
    rows: 10,
    rowsPerPageOptions: [3, 5, 10, 25, 50, 100],
  },
  headers: [
    {
      cols: [
        {
          label: 'State',
          valueField: 'state',
          classes: 'text-center',
          iconField: true,
          selected: true,
          filter: {
            isFilter: true,
            type: 'contains',
          },
          isSort: true,
          width: '6%',
        },
        {
          label: 'Event Name',
          valueField: 'eventName',
          classes: 'text-left',
          selected: true,
          filter: {
            isFilter: true,
            type: 'contains',
          },
          isSort: true,
        },
        {
          label: 'Checkpoint Name',
          valueField: 'checkpointName',
          classes: 'text-left',
          selected: true,
          filter: {
            isFilter: true,
            type: 'contains',
          },
          isSort: true,
        },
        {
          label: 'Criteria',
          valueField: 'criteria',
          classes: 'text-left',
          selected: true,
          filter: {
            isFilter: true,
            type: 'contains',
          },
          isSort: true,
        },
        {
          label: 'Value/Prefix Text',
          valueField: 'prefixText',
          classes: 'text-left',
          selected: true,
          filter: {
            isFilter: true,
            type: 'contains',
          },
          isSort: true,
        },
        {
          label: 'Suffix Text',
          valueField: 'suffixText',
          classes: 'text-left',
          selected: true,
          filter: {
            isFilter: true,
            type: 'contains',
          },
          isSort: true,
        },
        {
          label: 'Pages',
          valueField: 'pages',
          classes: 'text-left',
          selected: true,
          filter: {
            isFilter: true,
            type: 'contains',
          },
          isSort: true,
        },
        {
          label: 'Scope',
          valueField: 'scope',
          classes: 'text-left',
          selected: true,
          filter: {
            isFilter: true,
            type: 'contains',
          },
          isSort: true,
        },
        {
          label: 'Selector',
          valueField: 'selector',
          classes: 'text-left',
          selected: true,
          filter: {
            isFilter: true,
            type: 'contains',
          },
          isSort: true,
        },
        
      ],
    },
  ],
  data: [
    {
      icon: 'icons8 icons8-checkmark',
      eventName: 'PromoCodeError',
      checkpointName: 'PromoCodeError',
      criteria: 'Specific Text',
      prefixText: 'This%20promo%20',
      suffixText: '-',
      pages: 'Shopping Bag',
      scope: "Don't Change",
      selector: 'Perror Text',
    },
    {
      icon: 'icons8 icons8-checkmark',
      eventName: 'PromoCodeError',
      checkpointName: 'PromoCodeError',
      criteria: 'Specific Text',
      prefixText: 'This%20promo%20',
      suffixText: '-',
      pages: 'Shopping Bag',
      scope: "Don't Change",
      selector: 'Perror Text',
    },
    {
      icon: 'icons8 icons8-checkmark',
      eventName: 'PromoCodeError',
      checkpointName: 'PromoCodeError',
      criteria: 'Specific Text',
      prefixText: 'This%20promo%20',
      suffixText: '-',
      pages: 'Shopping Bag',
      scope: "Don't Change",
      selector: 'Perror Text',
    },
    {
      icon: 'icons8 icons8-checkmark',
      eventName: 'PromoCodeError',
      checkpointName: 'PromoCodeError',
      criteria: 'Specific Text',
      prefixText: 'This%20promo%20',
      suffixText: '-',
      pages: 'Shopping Bag',
      scope: "Don't Change",
      selector: 'Perror Text',
    },
    {
      icon: 'icons8 icons8-checkmark',
      eventName: 'PromoCodeError',
      checkpointName: 'PromoCodeError',
      criteria: 'Specific Text',
      prefixText: 'This%20promo%20',
      suffixText: '-',
      pages: 'Shopping Bag',
      scope: "Don't Change",
      selector: 'Perror Text',
    },
    {
      icon: 'icons8 icons8-checkmark',
      eventName: 'PromoCodeError',
      checkpointName: 'PromoCodeError',
      criteria: 'Specific Text',
      prefixText: 'This%20promo%20',
      suffixText: '-',
      pages: 'Shopping Bag',
      scope: "Don't Change",
      selector: 'Perror Text',
    },
    {
      icon: 'icons8 icons8-checkmark',
      eventName: 'PromoCodeError',
      checkpointName: 'PromoCodeError',
      criteria: 'Specific Text',
      prefixText: 'This%20promo%20',
      suffixText: '-',
      pages: 'Shopping Bag',
      scope: "Don't Change",
      selector: 'Perror Text',
    },
    {
      icon: 'icons8 icons8-checkmark',
      eventName: 'PromoCodeError',
      checkpointName: 'PromoCodeError',
      criteria: 'Specific Text',
      prefixText: 'This%20promo%20',
      suffixText: '-',
      pages: 'Shopping Bag',
      scope: "Don't Change",
      selector: 'Perror Text',
    },
    {
      icon: 'icons8 icons8-checkmark',
      eventName: 'PromoCodeError',
      checkpointName: 'PromoCodeError',
      criteria: 'Specific Text',
      prefixText: 'This%20promo%20',
      suffixText: '-',
      pages: 'Shopping Bag',
      scope: "Don't Change",
      selector: 'Perror Text',
    },
    {
      icon: 'icons8 icons8-checkmark',
      eventName: 'PromoCodeError',
      checkpointName: 'PromoCodeError',
      criteria: 'Specific Text',
      prefixText: 'This%20promo%20',
      suffixText: '-',
      pages: 'Shopping Bag',
      scope: "Don't Change",
      selector: 'Perror Text',
    },
    {
      icon: 'icons8 icons8-checkmark',
      eventName: 'PromoCodeError',
      checkpointName: 'PromoCodeError',
      criteria: 'Specific Text',
      prefixText: 'This%20promo%20',
      suffixText: '-',
      pages: 'Shopping Bag',
      scope: "Don't Change",
      selector: 'Perror Text',
    },
    {
      icon: 'icons8 icons8-checkmark',
      eventName: 'PromoCodeError',
      checkpointName: 'PromoCodeError',
      criteria: 'Specific Text',
      prefixText: 'This%20promo%20',
      suffixText: '-',
      pages: 'Shopping Bag',
      scope: "Don't Change",
      selector: 'Perror Text',
    },
    {
      icon: 'icons8 icons8-checkmark',
      eventName: 'PromoCodeError',
      checkpointName: 'PromoCodeError',
      criteria: 'Specific Text',
      prefixText: 'This%20promo%20',
      suffixText: '-',
      pages: 'Shopping Bag',
      scope: "Don't Change",
      selector: 'Perror Text',
    },
    {
      icon: 'icons8 icons8-checkmark',
      eventName: 'PromoCodeError',
      checkpointName: 'PromoCodeError',
      criteria: 'Specific Text',
      prefixText: 'This%20promo%20',
      suffixText: '-',
      pages: 'Shopping Bag',
      scope: "Don't Change",
      selector: 'Perror Text',
    },
    {
      icon: 'icons8 icons8-checkmark',
      eventName: 'PromoCodeError',
      checkpointName: 'PromoCodeError',
      criteria: 'Specific Text',
      prefixText: 'This%20promo%20',
      suffixText: '-',
      pages: 'Shopping Bag',
      scope: "Don't Change",
      selector: 'Perror Text',
    },
    {
      icon: 'icons8 icons8-checkmark',
      eventName: 'PromoCodeError',
      checkpointName: 'PromoCodeError',
      criteria: 'Specific Text',
      prefixText: 'This%20promo%20',
      suffixText: '-',
      pages: 'Shopping Bag',
      scope: "Don't Change",
      selector: 'Perror Text',
    },
    {
      icon: 'icons8 icons8-checkmark',
      eventName: 'PromoCodeError',
      checkpointName: 'PromoCodeError',
      criteria: 'Specific Text',
      prefixText: 'This%20promo%20',
      suffixText: '-',
      pages: 'Shopping Bag',
      scope: "Don't Change",
      selector: 'Perror Text',
    },
    {
      icon: 'icons8 icons8-checkmark',
      eventName: 'PromoCodeError',
      checkpointName: 'PromoCodeError',
      criteria: 'Specific Text',
      prefixText: 'This%20promo%20',
      suffixText: '-',
      pages: 'Shopping Bag',
      scope: "Don't Change",
      selector: 'Perror Text',
    },
    {
      icon: 'icons8 icons8-checkmark',
      eventName: 'PromoCodeError',
      checkpointName: 'PromoCodeError',
      criteria: 'Specific Text',
      prefixText: 'This%20promo%20',
      suffixText: '-',
      pages: 'Shopping Bag',
      scope: "Don't Change",
      selector: 'Perror Text',
    },
    {
      icon: 'icons8 icons8-checkmark',
      eventName: 'PromoCodeError',
      checkpointName: 'PromoCodeError',
      criteria: 'Specific Text',
      prefixText: 'This%20promo%20',
      suffixText: '-',
      pages: 'Shopping Bag',
      scope: "Don't Change",
      selector: 'Perror Text',
    },
    {
      icon: 'icons8 icons8-checkmark',
      eventName: 'PromoCodeError',
      checkpointName: 'PromoCodeError',
      criteria: 'Specific Text',
      prefixText: 'This%20promo%20',
      suffixText: '-',
      pages: 'Shopping Bag',
      scope: "Don't Change",
      selector: 'Perror Text',
    },
    {
      icon: 'icons8 icons8-checkmark',
      eventName: 'PromoCodeError',
      checkpointName: 'PromoCodeError',
      criteria: 'Specific Text',
      prefixText: 'This%20promo%20',
      suffixText: '-',
      pages: 'Shopping Bag',
      scope: "Don't Change",
      selector: 'Perror Text',
    },
    {
      icon: 'icons8 icons8-checkmark',
      eventName: 'PromoCodeError',
      checkpointName: 'PromoCodeError',
      criteria: 'Specific Text',
      prefixText: 'This%20promo%20',
      suffixText: '-',
      pages: 'Shopping Bag',
      scope: "Don't Change",
      selector: 'Perror Text',
    },
    {
      icon: 'icons8 icons8-checkmark',
      eventName: 'PromoCodeError',
      checkpointName: 'PromoCodeError',
      criteria: 'Specific Text',
      prefixText: 'This%20promo%20',
      suffixText: '-',
      pages: 'Shopping Bag',
      scope: "Don't Change",
      selector: 'Perror Text',
    },
    {
      icon: 'icons8 icons8-checkmark',
      eventName: 'PromoCodeError',
      checkpointName: 'PromoCodeError',
      criteria: 'Specific Text',
      prefixText: 'This%20promo%20',
      suffixText: '-',
      pages: 'Shopping Bag',
      scope: "Don't Change",
      selector: 'Perror Text',
    },
    {
      icon: 'icons8 icons8-checkmark',
      eventName: 'PromoCodeError',
      checkpointName: 'PromoCodeError',
      criteria: 'Specific Text',
      prefixText: 'This%20promo%20',
      suffixText: '-',
      pages: 'Shopping Bag',
      scope: "Don't Change",
      selector: 'Perror Text',
    },
    {
      icon: 'icons8 icons8-checkmark',
      eventName: 'PromoCodeError',
      checkpointName: 'PromoCodeError',
      criteria: 'Specific Text',
      prefixText: 'This%20promo%20',
      suffixText: '-',
      pages: 'Shopping Bag',
      scope: "Don't Change",
      selector: 'Perror Text',
    },
    {
      icon: 'icons8 icons8-checkmark',
      eventName: 'PromoCodeError',
      checkpointName: 'PromoCodeError',
      criteria: 'Specific Text',
      prefixText: 'This%20promo%20',
      suffixText: '-',
      pages: 'Shopping Bag',
      scope: "Don't Change",
      selector: 'Perror Text',
    },
    {
      icon: 'icons8 icons8-checkmark',
      eventName: 'PromoCodeError',
      checkpointName: 'PromoCodeError',
      criteria: 'Specific Text',
      prefixText: 'This%20promo%20',
      suffixText: '-',
      pages: 'Shopping Bag',
      scope: "Don't Change",
      selector: 'Perror Text',
    },
    {
      icon: 'icons8 icons8-checkmark',
      eventName: 'PromoCodeError',
      checkpointName: 'PromoCodeError',
      criteria: 'Specific Text',
      prefixText: 'This%20promo%20',
      suffixText: '-',
      pages: 'Shopping Bag',
      scope: "Don't Change",
      selector: 'Perror Text',
    },
    {
      icon: 'icons8 icons8-checkmark',
      eventName: 'PromoCodeError',
      checkpointName: 'PromoCodeError',
      criteria: 'Specific Text',
      prefixText: 'This%20promo%20',
      suffixText: '-',
      pages: 'Shopping Bag',
      scope: "Don't Change",
      selector: 'Perror Text',
    },
    {
      icon: 'icons8 icons8-checkmark',
      eventName: 'PromoCodeError',
      checkpointName: 'PromoCodeError',
      criteria: 'Specific Text',
      prefixText: 'This%20promo%20',
      suffixText: '-',
      pages: 'Shopping Bag',
      scope: "Don't Change",
      selector: 'Perror Text',
    },
    {
      icon: 'icons8 icons8-checkmark',
      eventName: 'PromoCodeError',
      checkpointName: 'PromoCodeError',
      criteria: 'Specific Text',
      prefixText: 'This%20promo%20',
      suffixText: '-',
      pages: 'Shopping Bag',
      scope: "Don't Change",
      selector: 'Perror Text',
    },
    {
      icon: 'icons8 icons8-checkmark',
      eventName: 'PromoCodeError',
      checkpointName: 'PromoCodeError',
      criteria: 'Specific Text',
      prefixText: 'This%20promo%20',
      suffixText: '-',
      pages: 'Shopping Bag',
      scope: "Don't Change",
      selector: 'Perror Text',
    },
    {
      icon: 'icons8 icons8-checkmark',
      eventName: 'PromoCodeError',
      checkpointName: 'PromoCodeError',
      criteria: 'Specific Text',
      prefixText: 'This%20promo%20',
      suffixText: '-',
      pages: 'Shopping Bag',
      scope: "Don't Change",
      selector: 'Perror Text',
    },
    {
      icon: 'icons8 icons8-checkmark',
      eventName: 'PromoCodeError',
      checkpointName: 'PromoCodeError',
      criteria: 'Specific Text',
      prefixText: 'This%20promo%20',
      suffixText: '-',
      pages: 'Shopping Bag',
      scope: "Don't Change",
      selector: 'Perror Text',
    },
    {
      icon: 'icons8 icons8-checkmark',
      eventName: 'PromoCodeError',
      checkpointName: 'PromoCodeError',
      criteria: 'Specific Text',
      prefixText: 'This%20promo%20',
      suffixText: '-',
      pages: 'Shopping Bag',
      scope: "Don't Change",
      selector: 'Perror Text',
    },
    {
      icon: 'icons8 icons8-checkmark',
      eventName: 'PromoCodeError',
      checkpointName: 'PromoCodeError',
      criteria: 'Specific Text',
      prefixText: 'This%20promo%20',
      suffixText: '-',
      pages: 'Shopping Bag',
      scope: "Don't Change",
      selector: 'Perror Text',
    },
    {
      icon: 'icons8 icons8-checkmark',
      eventName: 'PromoCodeError',
      checkpointName: 'PromoCodeError',
      criteria: 'Specific Text',
      prefixText: 'This%20promo%20',
      suffixText: '-',
      pages: 'Shopping Bag',
      scope: "Don't Change",
      selector: 'Perror Text',
    },
    {
      icon: 'icons8 icons8-checkmark',
      eventName: 'PromoCodeError',
      checkpointName: 'PromoCodeError',
      criteria: 'Specific Text',
      prefixText: 'This%20promo%20',
      suffixText: '-',
      pages: 'Shopping Bag',
      scope: "Don't Change",
      selector: 'Perror Text',
    },
    {
      icon: 'icons8 icons8-checkmark',
      eventName: 'PromoCodeError',
      checkpointName: 'PromoCodeError',
      criteria: 'Specific Text',
      prefixText: 'This%20promo%20',
      suffixText: '-',
      pages: 'Shopping Bag',
      scope: "Don't Change",
      selector: 'Perror Text',
    },
    {
      icon: 'icons8 icons8-checkmark',
      eventName: 'PromoCodeError',
      checkpointName: 'PromoCodeError',
      criteria: 'Specific Text',
      prefixText: 'This%20promo%20',
      suffixText: '-',
      pages: 'Shopping Bag',
      scope: "Don't Change",
      selector: 'Perror Text',
    },
    {
      icon: 'icons8 icons8-checkmark',
      eventName: 'PromoCodeError',
      checkpointName: 'PromoCodeError',
      criteria: 'Specific Text',
      prefixText: 'This%20promo%20',
      suffixText: '-',
      pages: 'Shopping Bag',
      scope: "Don't Change",
      selector: 'Perror Text',
    },
    {
      icon: 'icons8 icons8-checkmark',
      eventName: 'PromoCodeError',
      checkpointName: 'PromoCodeError',
      criteria: 'Specific Text',
      prefixText: 'This%20promo%20',
      suffixText: '-',
      pages: 'Shopping Bag',
      scope: "Don't Change",
      selector: 'Perror Text',
    },
    {
      icon: 'icons8 icons8-checkmark',
      eventName: 'PromoCodeError',
      checkpointName: 'PromoCodeError',
      criteria: 'Specific Text',
      prefixText: 'This%20promo%20',
      suffixText: '-',
      pages: 'Shopping Bag',
      scope: "Don't Change",
      selector: 'Perror Text',
    },
  ],
};
