import { MissionControlTable } from './mission-control.model';

export const MISSION_CONTROL_TABLE_DATA: MissionControlTable = {

  paginator: {
    first: 1,
    rows: 10,
    rowsPerPageOptions: [5, 10, 25, 50, 100],
  },

  headers: [
    {
      cols: [
        {
          label: 'File Name',
          valueField: 'fname',
          classes: 'text-left',
          selected: true,
          filter: {
            isFilter: true,
            type: 'contains',
          },
          isSort: true,
        },
        {
          label: 'File Size',
          valueField: 'fsize',
          classes: 'text-left',
          selected: true,
          filter: {
            isFilter: true,
            type: 'contains',
          },
          isSort: true,
        },
        {
          label: 'Modification Time',
          valueField: 'modificationtime',
          classes: 'text-left',
          selected: true,
          filter: {
            isFilter: true,
            type: 'contains',
          },
          isSort: true,
        },
        {
          label: 'Download and View',
          valueField: 'downloadandview',
          selected: true,
          filter: {
            isFilter: false,
            type: 'contains',
          },
          isSort: false,
        },
      ],
    },
  ],
  data: [
    {
      fname:'abcd', 
      fsize:'20kb',
      modificationtime:'10:12:00',
      downloadandview:'',
    },
    {
      fname:'abcd', 
      fsize:'20kb',
      modificationtime:'10:12:00',
      downloadandview:'',
    },
    {
      fname:'abcd', 
      fsize:'20kb',
      modificationtime:'10:12:00',
      downloadandview:'',
    },
    {
      fname:'abcd', 
      fsize:'20kb',
      modificationtime:'10:12:00',
      downloadandview:'',
    },
    {
      fname:'abcd', 
      fsize:'20kb',
      modificationtime:'10:12:00',
      downloadandview:'',
    },
    {
      fname:'abcd', 
      fsize:'20kb',
      modificationtime:'10:12:00',
      downloadandview:'',
    },
    {
      fname:'abcd', 
      fsize:'20kb',
      modificationtime:'10:12:00',
      downloadandview:'',
    },
    {
      fname:'abcd', 
      fsize:'20kb',
      modificationtime:'10:12:00',
      downloadandview:'',
    },
    {
      fname:'abcd', 
      fsize:'20kb',
      modificationtime:'10:12:00',
      downloadandview:'',
    },
    {
      fname:'abcd', 
      fsize:'20kb',
      modificationtime:'10:12:00',
      downloadandview:'',
    },
    {
      fname:'abcd', 
      fsize:'20kb',
      modificationtime:'10:12:00',
      downloadandview:'',
    },
    {
      fname:'abcd', 
      fsize:'20kb',
      modificationtime:'10:12:00',
      downloadandview:'',
    },
    {
      fname:'abcd', 
      fsize:'20kb',
      modificationtime:'10:12:00',
      downloadandview:'',
    },
    {
      fname:'abcd', 
      fsize:'20kb',
      modificationtime:'10:12:00',
      downloadandview:'',
    },
    {
      fname:'abcd', 
      fsize:'20kb',
      modificationtime:'10:12:00',
      downloadandview:'',
    },
    {
      fname:'abcd', 
      fsize:'20kb',
      modificationtime:'10:12:00',
      downloadandview:'',
    },
    {
      fname:'abcd', 
      fsize:'20kb',
      modificationtime:'10:12:00',
      downloadandview:'',
    },
    {
      fname:'abcd', 
      fsize:'20kb',
      modificationtime:'10:12:00',
      downloadandview:'',
    },
    {
      fname:'abcd', 
      fsize:'20kb',
      modificationtime:'10:12:00',
      downloadandview:'',
    },
    {
      fname:'abcd', 
      fsize:'20kb',
      modificationtime:'10:12:00',
      downloadandview:'',
    },
    {
      fname:'abcd', 
      fsize:'20kb',
      modificationtime:'10:12:00',
      downloadandview:'',
    },
    {
      fname:'abcd', 
      fsize:'20kb',
      modificationtime:'10:12:00',
      downloadandview:'',
    },
    {
      fname:'abcd', 
      fsize:'20kb',
      modificationtime:'10:12:00',
      downloadandview:'',
    },
    {
      fname:'abcd', 
      fsize:'20kb',
      modificationtime:'10:12:00',
      downloadandview:'',
    },
    {
      fname:'abcd', 
      fsize:'20kb',
      modificationtime:'10:12:00',
      downloadandview:'',
    },
    {
      fname:'abcd', 
      fsize:'20kb',
      modificationtime:'10:12:00',
      downloadandview:'',
    },
    {
      fname:'abcd', 
      fsize:'20kb',
      modificationtime:'10:12:00',
      downloadandview:'',
    },
    {
      fname:'abcd', 
      fsize:'20kb',
      modificationtime:'10:12:00',
      downloadandview:'',
    },
    {
      fname:'abcd', 
      fsize:'20kb',
      modificationtime:'10:12:00',
      downloadandview:'',
    },
    {
      fname:'abcd', 
      fsize:'20kb',
      modificationtime:'10:12:00',
      downloadandview:'',
    },
    {
      fname:'abcd', 
      fsize:'20kb',
      modificationtime:'10:12:00',
      downloadandview:'',
    },
    {
      fname:'abcd', 
      fsize:'20kb',
      modificationtime:'10:12:00',
      downloadandview:'',
    },
    {
      fname:'abcd', 
      fsize:'20kb',
      modificationtime:'10:12:00',
      downloadandview:'',
    },
    {
      fname:'abcd', 
      fsize:'20kb',
      modificationtime:'10:12:00',
      downloadandview:'',
    },
    {
      fname:'abcd', 
      fsize:'20kb',
      modificationtime:'10:12:00',
      downloadandview:'',
    },
    {
      fname:'abcd', 
      fsize:'20kb',
      modificationtime:'10:12:00',
      downloadandview:'',
    },
    {
      fname:'abcd', 
      fsize:'20kb',
      modificationtime:'10:12:00',
      downloadandview:'',
    },
    {
      fname:'abcd', 
      fsize:'20kb',
      modificationtime:'10:12:00',
      downloadandview:'',
    },
    {
      fname:'abcd', 
      fsize:'20kb',
      modificationtime:'10:12:00',
      downloadandview:'',
    },
    {
      fname:'abcd', 
      fsize:'20kb',
      modificationtime:'10:12:00',
      downloadandview:'',
    },
    {
      fname:'abcd', 
      fsize:'20kb',
      modificationtime:'10:12:00',
      downloadandview:'',
    },
    {
      fname:'abcd', 
      fsize:'20kb',
      modificationtime:'10:12:00',
      downloadandview:'',
    },
  ],
  
  tableFilter: false,
};