export const CMD_MON_TYPE_ARG = "#monType"; // Monitor type for new Options (CMD-1/REST-2/MBEAN-3/DB-4)
export const CMD_OUTPUT_TYPE_ARG = "#respType";// Output type for new Options (string-1/keyValue-2/JSON-3/JMX-4) of configured monitor
export const CMD_RETRY_ARG = "#maxRetryCount";// Count of maximum retry to make connection
export const CMD_DELETE_VECTOR_ARG = "#vecPersistTime"; // delVecTime for new Options
export const CMD_INTERVAL_ARG = "#interval"; // intervaL for new Options
export const CMD_TIER_ARG = "#tier"; // Tier for new Options
export const CMD_SERVER_ARG = "#server"; // server for new Options
export const CMD_HOST_ARG = "#host"; //  host
export const CMD_PORT_ARG = "#port"; //  port
export const CMD_USER_ARG = "#user"; //  user
export const CMD_PWD_ARG = "#pwd"; //  password
export const CMD_REMOTE_TIER_ARG = "#remoteTierUI"; // remote Tier 
export const CMD_REMOTE_SERVER_ARG = "#remoteServerUI"; // remote server 
export const CMD_REMOTE_HOST_ARG = "#remoteHost"; // Remote host
export const CMD_REMOTE_PORT_ARG = "#remotePort"; // Remote port
export const CMD_REMOTE_USER_ARG = "#remoteUser"; // Remote user
export const CMD_REMOTE_PWD_ARG = "#remotePwd"; // Remote password
export const CMD_PRIVATE_KEY_ARG = "#privateKey"; // private key
export const CMD_PASSPHRASE_ARG = "#passphrase"; // passphrase
export const CMD_PUBLIC_KEY_ARG = "#publicKey"; // public key
export const CMD_PROXY_HOST_ARG = "#proxyHost"; // Proxy host
export const CMD_PROXY_PORT_ARG = "#proxyPort"; // Proxy port
export const CMD_PROXY_USER_ARG = "#proxyUser"; // Proxy username
export const CMD_PROXY_PWD_ARG = "#proxyPwd"; // Proxy password
export const CMD_INSTANCE_ARG = "#instance"; // Proxy password
export const JMX_IS_TWO_WAY_SSL = "#isTwoWaySSL"; // is Two Way SSL enable
export const JMX_URL_ARG = "#url"; //Jmx connection url
export const JMX_PID_ARG = "#pid"; //Process id for JMX monitor
export const JMX_PID_FILE_ARG = "#pidFile"; //Process Id file 
export const JMX_OCCURENCE_COUNT_ARG = "#index"; 
export const JMX_TRUST_STORE_FILE_ARG = "#truststoreFile"; //Trust store file path
export const JMX_TRUST_STORE_PASSWORD_ARG = "#truststorePwd" // Trust store password
export const JMX_KEY_STORE_FILE_ARG = "#keystoreFile" // Key store file path
export const JMX_KEY_STORE_PASSWORD_ARG = "#keystorePwd" //key store password
export const JMX_TRUST_STORE_FILE_TYPE_ARG = "#truststoreFileType" // Trust store file path
export const JMX_CONNECTOR_SEARCH_PATTERN_ARG = "#searchPattern"; //JMX connector search pattern
export const DB_NAME_ARG = "#dbName"; //JMX connector search pattern
export const DB_AUTH_TYPE_ARG = "#authMode"; // Auth type
export const DB_SID_ARG = "#sid"; //SID
export const DB_VECTOR_PERSIST_COUNT_ARG = "#vecPersistCount" // Vector persist count
export const DB_IS_REFRESH_ARG = "#isRefresh" // IS REFRESH 
export const DB_SERVICE_ACCOUNT_FILE_ARG = "--serviceAccFile"// Service account file 
export const DB_SERVICE_ACCOUNT_TOKEN_FILE_PATH_ARG = "--SATokenFilePath" //Service account token file path

export const SPACE_SEPARATOR = " ";
export const PASSWORD_SEPERATOR = "cav_e";
export const AGENT_TYPE = "#agent"; // Proxy password
export const IS_ENCRYPTED_PWD_ARG = "#isEncryptPwd";
export const CLASS_PATH = "#classPath"
export const JAVA_HOME = "#javaHome"