export const TIER_INFO = "tierInfo";
export const COMPONENTS_KEY = "components";
export const STANDARD_KEY = "std";
export const MON_TYPE = "monType";
export const MON_NAME = "monName";
export const LOCAL_HOST = "localhost";
export const OPTIONS_KEY = "option";
export const COMPONENT_KEY = "component";
export const DEPENDENT_COMP = "dependentComp";
export const OPTIONS = "options";
export const ENABLED = "enabled"
export const INTERNAL_MON_NAME = "inMonName";
export const TYPE = "type";
export const VALUE = "value";
export const KEY = "key";
export const ARGS = "args";
export const TEXTFIELD_TYPE = "TextField";
export const SPINNER_TYPE = "Spinner";
export const ISPROCESS = "isProcess";
export const RUN_AS_PROCESS = "run-as-process";
export const RADIOBUTTONGROUP_TYPE = "RadioButtonGroup";
export const ACCORDIAN_TYPE = "Accordion";
export const CHECKBOX_TYPE = "Checkbox";
export const DROPDOWN_TYPE = "Dropdown";
export const TABLE_TYPE = "Table";
export const TABLESINGLEARG_TYPE = "TableSingleArg";
export const FIELDSETLABEL_TYPE = "FieldSet";
export const OTHER_TYPE = "other";
export const AGENT_TYPE = "agentType";
export const AGENT_KEY = "agent-type";
export const TIER_TYPE = "tierName";
export const TIERGROUP_TYPE = "tierGroup";
export const IS_SPECIFIC_KEY = "isSpecific";
export const DEP_OPTIONS_KEY = "depOptions";
export const ENABLE_KEY = "enable";
export const UI_OPTIONS_KEY = "uiO";
export const INSTANCE = "instanceName";
export const APPNAME = "appName";
export const EXCLUDE_APP = "excludeAppName";
export const JAVAHOME = "javaHome";
export const ITEMS_KEY = "items";
export const CLASSPATH = "classPath";
export const COLUMNDATA = "columnData";
export const TABLE_DATA = "data";
export const COLUMN_SEPERATOR = "columnSeperator";
export const ROW_SEPERATOR = "rowSeperator";
export const USE_AS_OPTION = "useAsOption";
export const CMD_TYPE = "cmd";
export const DB_TYPE = "db";
export const JMX_TYPE = "jmx";
export const NEWLINE = "NewLine";
export const IS_ENCRYPTED = "isEncryptPwd";
export const MON_CATEGORY = "monCat";
export const NOTE_TAG = "Note";
export const DROP_DOWN_LIST_ITEMS = "dropDownList";
export const KEY_VALUE_SEPARATOR ="keyValueSeperator";
export const VALIDATION_OBJ="validationObj";
export const INPUT_TYPE = "inputType";
export const TYPE_PASSWORD = "password";
export const IS_QUOTE_REQUIRED = "isQuoteRequired";
export const URL_ENCODE = "uRLEncode";
export const PWD_ENCRYPT_VAL = "pwdEncrypt";
export const PASSWORD_SEPERATOR = "cav_e";
export const SPACE_SEPARATOR = " ";
export const USE_SINGLE_VAL_TYPE = "useMultipleAsSingleValue";
export const MON_GROUP = "_grp";
export const MON_GRP_GLOBAL = "global";
export const DRIVEN_KEY = "driven";
export const MON_GRP_OTHERS = "others";
export const MON_GRP_JMX = "_jmx";
export const MON_GRP_CMD = "_cmd";
export const MON_GRP_DB = "_db";
export const ANY_TIER_SERVER = "tierForAnyServer"
export const COMMA_SEPARATOR = ",";
export const COLON_SEPARATOR = ":";
export const MON_GRP_KEY_SEPARATOR = "#";
export const KEY_START = "${";
export const KEY_END = "}";
export const CUSTOM_MONITOR_KEY = "cust";
export const RESPONSE_STATUS = "status";
export const RESPONSE_MSG = "msg";
export const SUMMARY_SUCCESS = "SUCCESS";
export const SUMMARY_ERROR = "ERROR";
export const SEVERITY_SUCCESS = "success";
export const SEVERITY_ERROR = "error";

/***CHECK MON fields ****/
export const NAME = "name";
export const FROM_EVENT = "fromEvent";
export const PHASE_NAME = "phaseName";
export const FREQUENCY = "frequency";
export const PERIODICITY = "periodicity";
export const END_EVENT = "endEvent";
export const COUNT = "count";
export const END_PHASE_NAME = "endPhaseName";

export const FROM_EVENT_UI = "fromEvent_ui";
export const FREQUENCY_UI = "frequency_ui";
export const END_EVENT_UI = "endEvent_ui";

export const SIGN_TYPE = "signType";
export const CMDFILE_NAME = "commandFileName";
export const SERVER_SIGNATURE = "Server Signature";
export const CHECK_MON_PROG_NAME = "checkMonProgName";
export const CHECK_INSTANCE = 'instance'

//  added for Batch Jobs
export const BATCH_JOBS = "Batch Jobs"
export const BATCH_JOBS_TYPE = 10;
export const BATCH_SEARCH_PATTERN = "batchSearchPattern";
export const BATCH_LOG_FILE_NAME = "logFile";
export const COMMAND_NAME = "cmdName";
export const SUCCESS_CRITERIA = "successCriteria";
export const CUSTOM_INPUT_FILE = "cm_cav_snmp_";
export const SNMP_FILE_PATH = "/snmp/inp/";
export const CUSTOM_INPUT_FILE_EXT = ".inp";
export const OTHERS_KEY = "Others";
export const ALL_SERVERS_KEY = "All Servers";
export const START_TEST_MSG = "Are you sure to run test for ";
export const DELETE_SPECIFIC_CONFIGURATION = "Are you sure to delete the selected configuration(s)?"
export const TECH_HEALTH_CHECK = "healthCheck";
export const MON_DISPLAY_NAME = "mdn";
export const MON_GRP_DISPLAY_NAME = "_grpDisp";
export const GRP_DISP_NAME_GLOBAL = "Global";
export const GRP_DISP_NAME_OTHERS = "Others";
export const GRP_DISP_NAME_JMX = "JMX Based Monitors";
export const GRP_DISP_NAME_CMD = "Command Based Monitors";
export const GRP_DISP_NAME_DB = "DB Based Monitors";
export const UNDERSCORE = "_";
export const VALUE_OBJ = "valObj";      //added for multiselect type
export const DOUBLE_HYPHEN = "--";
export const HYPHEN = "-";
export const FORWARD_SLASH = "/"