import { TreeNode } from 'primeng';
import { TreeNodeMenu, TreeResult } from './custom-metrics.model';


export const GRAPH_IN_TREE: TreeNodeMenu[] = [
  {
    "label": "Derived Metrics",
    "data": "Derived Metrics 1",
    "icon": "icons8 icons8-folder",
    "expanded": false,
    "level" : 0,
    "children": [
      {}
    ]
  },
  {
    "label": "Merged Metrics",
    "data": "Merged Metrics 1",
    "icon": "icons8 icons8-folder",
    "level": 0,
    "expanded": false,
    "children": [{}]
  }
]


export const treeDropData = [{"measureTags":{"metric":"Shared Memory (MB)","metricId":-1,"mg":"Memory Stats","mgId":10007,"mgType":"NA","mgTypeId":-1,"showTogether":0},"subjectTags":[{"key":"Tier","value":"AppTier","mode":1},{"key":"Server","value":"QAServer9","mode":1}]}]

export const CUSTOM_METRICS: TreeResult[] = [
  {
    hasChildren: false,
    graphID: null,
    groupID: null,
    groupTypeVector: false,
    lastHierarchicalComponent: false,
    matched: false,
    metricsName: null,
    nodeType: 0,
    specialNode: false,
    state: 'OPENED',
    text: 'Derived Metrics',
    type: 'Derived Metrics',
  },
  {
    hasChildren: false,
    graphID: null,
    groupID: null,
    groupTypeVector: false,
    lastHierarchicalComponent: false,
    matched: false,
    metricsName: null,
    nodeType: 0,
    specialNode: false,
    state: 'OPENED',
    text: 'Merged Metrics',
    type: 'Merged Metrics',
  },
  {
    hasChildren: false,
    graphID: null,
    groupID: null,
    groupTypeVector: false,
    lastHierarchicalComponent: false,
    matched: false,
    metricsName: null,
    nodeType: 0,
    specialNode: false,
    state: 'OPENED',
    text: 'Merged Metrics',
    type: 'Merged Metrics',
  },
  {
    hasChildren: false,
    graphID: null,
    groupID: null,
    groupTypeVector: false,
    lastHierarchicalComponent: false,
    matched: false,
    metricsName: null,
    nodeType: 0,
    specialNode: false,
    state: 'OPENED',
    text: 'Merged Metrics',
    type: 'Merged Metrics',
  },
  {
    hasChildren: false,
    graphID: null,
    groupID: null,
    groupTypeVector: false,
    lastHierarchicalComponent: false,
    matched: false,
    metricsName: null,
    nodeType: 0,
    specialNode: false,
    state: 'OPENED',
    text: 'Merged Metrics',
    type: 'Merged Metrics',
  },
  {
    hasChildren: false,
    graphID: null,
    groupID: null,
    groupTypeVector: false,
    lastHierarchicalComponent: false,
    matched: false,
    metricsName: null,
    nodeType: 0,
    specialNode: false,
    state: 'OPENED',
    text: 'Merged Metrics',
    type: 'Merged Metrics',
  },
  {
    hasChildren: false,
    graphID: null,
    groupID: null,
    groupTypeVector: false,
    lastHierarchicalComponent: false,
    matched: false,
    metricsName: null,
    nodeType: 0,
    specialNode: false,
    state: 'OPENED',
    text: 'Merged Metrics',
    type: 'Merged Metrics',
  },
  {
    hasChildren: false,
    graphID: null,
    groupID: null,
    groupTypeVector: false,
    lastHierarchicalComponent: false,
    matched: false,
    metricsName: null,
    nodeType: 0,
    specialNode: false,
    state: 'OPENED',
    text: 'Merged Metrics',
    type: 'Merged Metrics',
  },
  {
    hasChildren: false,
    graphID: null,
    groupID: null,
    groupTypeVector: false,
    lastHierarchicalComponent: false,
    matched: false,
    metricsName: null,
    nodeType: 0,
    specialNode: false,
    state: 'OPENED',
    text: 'Merged Metrics',
    type: 'Merged Metrics',
  },
  {
    hasChildren: false,
    graphID: null,
    groupID: null,
    groupTypeVector: false,
    lastHierarchicalComponent: false,
    matched: false,
    metricsName: null,
    nodeType: 0,
    specialNode: false,
    state: 'OPENED',
    text: 'Merged Metrics',
    type: 'Merged Metrics',
  },
  {
    hasChildren: false,
    graphID: null,
    groupID: null,
    groupTypeVector: false,
    lastHierarchicalComponent: false,
    matched: false,
    metricsName: null,
    nodeType: 0,
    specialNode: false,
    state: 'OPENED',
    text: 'Merged Metrics',
    type: 'Merged Metrics',
  },
  {
    hasChildren: false,
    graphID: null,
    groupID: null,
    groupTypeVector: false,
    lastHierarchicalComponent: false,
    matched: false,
    metricsName: null,
    nodeType: 0,
    specialNode: false,
    state: 'OPENED',
    text: 'Merged Metrics',
    type: 'Merged Metrics',
  },
  {
    hasChildren: false,
    graphID: null,
    groupID: null,
    groupTypeVector: false,
    lastHierarchicalComponent: false,
    matched: false,
    metricsName: null,
    nodeType: 0,
    specialNode: false,
    state: 'OPENED',
    text: 'Merged Metrics',
    type: 'Merged Metrics',
  },
  {
    hasChildren: false,
    graphID: null,
    groupID: null,
    groupTypeVector: false,
    lastHierarchicalComponent: false,
    matched: false,
    metricsName: null,
    nodeType: 0,
    specialNode: false,
    state: 'OPENED',
    text: 'Merged Metrics',
    type: 'Merged Metrics',
  },
  {
    hasChildren: false,
    graphID: null,
    groupID: null,
    groupTypeVector: false,
    lastHierarchicalComponent: false,
    matched: false,
    metricsName: null,
    nodeType: 0,
    specialNode: false,
    state: 'OPENED',
    text: 'Merged Metrics',
    type: 'Merged Metrics',
  },
  {
    hasChildren: false,
    graphID: null,
    groupID: null,
    groupTypeVector: false,
    lastHierarchicalComponent: false,
    matched: false,
    metricsName: null,
    nodeType: 0,
    specialNode: false,
    state: 'OPENED',
    text: 'Merged Metrics',
    type: 'Merged Metrics',
  },
  {
    hasChildren: false,
    graphID: null,
    groupID: null,
    groupTypeVector: false,
    lastHierarchicalComponent: false,
    matched: false,
    metricsName: null,
    nodeType: 0,
    specialNode: false,
    state: 'OPENED',
    text: 'Merged Metrics',
    type: 'Merged Metrics',
  },
  {
    hasChildren: false,
    graphID: null,
    groupID: null,
    groupTypeVector: false,
    lastHierarchicalComponent: false,
    matched: false,
    metricsName: null,
    nodeType: 0,
    specialNode: false,
    state: 'OPENED',
    text: 'Merged Metrics',
    type: 'Merged Metrics',
  },
];
