import { FlowPathTable } from './flow-path.model';

export const FLOW_PATH_TABLE: FlowPathTable = {
  headers: [
    {
      cols: [
        {
          label: 'Business Transaction',
          valueField: 'businessTransaction',
          classes: 'text-left',
          selected: false,
          severityColorField: true,
          filter: {
            isFilter: true,
            type: 'contains',
          },
          isSort: true,
          width:'10%'
        },
        {
          label: 'URL',
          valueField: 'url',
          classes: 'text-left',
          selected: true,
          filter: {
            isFilter: true,
            type: 'contains',
          },
          isSort: true,
          width:'10%'
        },
        {
          label: 'Category',
          valueField: 'category',
          classes: 'text-left',
          selected: true,
          filter: {
            isFilter: true,
            type: 'contains',
          },
          isSort: false,
        },
        {
          label: 'Start Time',
          valueField: 'startTime',
          classes: 'text-left',
          selected: true,
          filter: {
            isFilter: true,
            type: 'contains',
          },
          isSort: true,
        },
        {
          label: 'Response Time',
          valueField: 'responseTime',
          classes: 'text-left',
          selected: true,
          filter: {
            isFilter: true,
            type: 'contains',
          },
          isSort: true,
        },
        {
          label: 'CPU Time(ms)',
          valueField: 'cpu',
          classes: 'text-left',
          selected: true,
          filter: {
            isFilter: true,
            type: 'custom',
          },
          isSort: true,
        },
        {
          label: 'Methods',
          valueField: 'methods',
          classes: 'text-left',
          selected: true,
          filter: {
            isFilter: true,
            type: 'contains',
          },
          isSort: true,
        },
        {
          label: 'Call Outs',
          valueField: 'callOuts',
          classes: 'text-left',
          selected: true,
          filter: {
            isFilter: false,
            type: 'contains',
          },
          isSort: true,
        },
        {
          label: 'Db Callouts',
          valueField: 'dbCallouts',
          classes: 'text-left',
          selected: true,
          filter: {
            isFilter: true,
            type: 'contains',
          },
          isSort: true,
        },
        {
          label: 'Status',
          valueField: 'status',
          classes: 'text-left',
          selected: true,
          filter: {
            isFilter: false,
            type: 'contains',
          },
          isSort: true,
        },
      ],
    },
  ],
  data: [
    {
      businessTransaction: 'Dashboard first',
      url: 'DashboardServer/RestServ',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '1,003',
      cpu: '154.904',
      methods: '20',
      callOuts: 10,
      dbCallouts: 20,
      status: 200,
      selected: false,
      severityColor: '#89b0d3',
    },
    {
      businessTransaction: 'Dashboard Service/Req sec',
      url: 'DashboardServer3',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '1,033',
      cpu: '111',
      methods: '203',
      callOuts: 63,
      dbCallouts: 80,
      status: 200,
      selected: false,
      severityColor: '#5396d1',
    },
    {
      businessTransaction: 'Dashboard dummy data',
      url: 'DashboardServer4',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '1,063',
      cpu: '154.3',
      methods: '29',
      callOuts: 68,
      dbCallouts: 50,
      status: 200,
      selected: false,
      severityColor: '#89b0d3',
    },
    {
      businessTransaction: 'Dashboard Req',
      url: 'DashboardServer/Rest',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '2306',
      cpu: '156.954',
      methods: '24',
      callOuts: 62,
      dbCallouts: 69,
      status: 200,
      selected: false,
      severityColor: '#5396d1',
    },
    {
      businessTransaction: 'Dash6',
      url: 'DashboardServer/dummy',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '1,023',
      cpu: '154.950',
      methods: '13',
      callOuts: 19,
      dbCallouts: 60,
      status: 200,
      selected: false,
      severityColor: '#89b0d3',
    },
    {
      businessTransaction: 'Dashboard60',
      url: 'Dashboard/request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '1163',
      cpu: '154.99',
      methods: '23',
      callOuts: 78,
      dbCallouts: 79,
      status: 200,
      selected: false,
      severityColor: '#5396d1',
    },
    {
      businessTransaction: 'Req',
      url: 'kpinfo/request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '1,263',
      cpu: '154.954',
      methods: '230',
      callOuts: 0,
      dbCallouts: 0,
      status: 200,
      selected: false,
      severityColor: '#89b0d3',
    },
    {
      businessTransaction: 'dummy Service/Req',
      url: 'DashboardServer/Service/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '1,639',
      cpu: '154.954',
      methods: '23',
      callOuts: 10,
      dbCallouts: 30,
      status: 200,
      selected: false,
      severityColor: '#5396d1',
    },
    {
      businessTransaction: 'Dashboard Service/Req',
      url: 'DashboardServer/RestService/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '1,063',
      cpu: '154.9',
      methods: '25',
      callOuts: 6,
      dbCallouts: 3,
      status: 200,
      selected: false,
      severityColor: '#89b0d3',
    },
    {
      businessTransaction: 'Req6',
      url: 'DashboardServer/RestService/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '1,0636',
      cpu: '154.954',
      methods: '233',
      callOuts: 0,
      dbCallouts: 0,
      status: 200,
      selected: false,
      severityColor: '#5396d1',
    },
    {
      businessTransaction: 'Req11',
      url: 'DashboardServer/RestService/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '1,069',
      cpu: '154.984',
      methods: '23',
      callOuts: 68,
      dbCallouts: 96,
      status: 200,
      selected: false,
      severityColor: '#89b0d3',
    },
    {
      businessTransaction: 'Req65',
      url: 'DashboardServer/RestService/kpinfo?request',
      category: 'Critical',
      startTime: '08:09(03/24/20)',
      responseTime: '1,063',
      cpu: '154.954',
      methods: '23',
      callOuts: 0,
      dbCallouts: 0,
      status: 400,
      selected: false,
      severityColor: '#5396d1',
    },
    {
      businessTransaction: 'Dashboard Service/Req',
      url: 'DashboardServer/RestService/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '1,063',
      cpu: '154.954',
      methods: '23',
      callOuts: 0,
      dbCallouts: 0,
      status: 200,
      selected: false,
      severityColor: '#89b0d3',
    },
    {
      businessTransaction: 'Dash',
      url: 'DashboardServer/jkl',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '1,516',
      cpu: '159',
      methods: '23',
      callOuts: 62,
      dbCallouts: 53,
      status: 200,
      selected: false,
      severityColor: '#5396d1',
    },
    {
      businessTransaction: 'Dashboard Service',
      url: 'DashboardServer',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '1,063',
      cpu: '154.954',
      methods: '23',
      callOuts: 0,
      dbCallouts: 0,
      status: 200,
      selected: false,
      severityColor: '#89b0d3',
    },
    {
      businessTransaction: 'Dashboard Service/Req',
      url: 'DashboardServer3',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '1,033',
      cpu: '111',
      methods: '203',
      callOuts: 63,
      dbCallouts: 80,
      status: 200,
      selected: false,
      severityColor: '#5396d1',
    },
    {
      businessTransaction: 'Dashboard dummy data',
      url: 'DashboardServer4',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '1,063',
      cpu: '154.3',
      methods: '29',
      callOuts: 68,
      dbCallouts: 50,
      status: 200,
      selected: false,
      severityColor: '#89b0d3',
    },
    {
      businessTransaction: 'Dashboard Req',
      url: 'DashboardServer/Rest',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '2306',
      cpu: '156.954',
      methods: '24',
      callOuts: 62,
      dbCallouts: 69,
      status: 200,
      selected: false,
      severityColor: '#5396d1',
    },
    {
      businessTransaction: 'Dash6',
      url: 'DashboardServer/dummy',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '1,023',
      cpu: '154.950',
      methods: '13',
      callOuts: 19,
      dbCallouts: 60,
      status: 200,
      selected: false,
      severityColor: '#89b0d3',
    },
    {
      businessTransaction: 'Dashboard60',
      url: 'Dashboard/request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '1163',
      cpu: '154.99',
      methods: '23',
      callOuts: 78,
      dbCallouts: 79,
      status: 200,
      selected: false,
      severityColor: '#5396d1',
    },
    {
      businessTransaction: 'Req',
      url: 'kpinfo/request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '1,263',
      cpu: '154.954',
      methods: '230',
      callOuts: 0,
      dbCallouts: 0,
      status: 200,
      selected: false,
      severityColor: '#89b0d3',
    },
    {
      businessTransaction: 'dummy Service/Req',
      url: 'DashboardServer/Service/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '1,639',
      cpu: '154.954',
      methods: '23',
      callOuts: 10,
      dbCallouts: 30,
      status: 200,
      selected: false,
      severityColor: '#5396d1',
    },
    {
      businessTransaction: 'Dashboard Service/Req',
      url: 'DashboardServer/RestService/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '1,063',
      cpu: '154.9',
      methods: '25',
      callOuts: 6,
      dbCallouts: 3,
      status: 200,
      selected: false,
      severityColor: '#89b0d3',
    },
    {
      businessTransaction: 'Req6',
      url: 'DashboardServer/RestService/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '1,0636',
      cpu: '154.954',
      methods: '233',
      callOuts: 0,
      dbCallouts: 0,
      status: 200,
      selected: false,
      severityColor: '#5396d1',
    },
    {
      businessTransaction: 'Req11',
      url: 'DashboardServer/RestService/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '1,069',
      cpu: '154.984',
      methods: '23',
      callOuts: 68,
      dbCallouts: 96,
      status: 200,
      selected: false,
      severityColor: '#89b0d3',
    },
    {
      businessTransaction: 'Req65',
      url: 'DashboardServer/RestService/kpinfo?request',
      category: 'Critical',
      startTime: '08:09(03/24/20)',
      responseTime: '1,063',
      cpu: '154.954',
      methods: '23',
      callOuts: 0,
      dbCallouts: 0,
      status: 400,
      selected: false,
      severityColor: '#5396d1',
    },
    {
      businessTransaction: 'Dashboard Service/Req',
      url: 'DashboardServer/RestService/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '1,063',
      cpu: '154.954',
      methods: '23',
      callOuts: 0,
      dbCallouts: 0,
      status: 200,
      selected: false,
      severityColor: '#89b0d3',
    },
    {
      businessTransaction: 'Dash',
      url: 'DashboardServer/jkl',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '1,516',
      cpu: '159',
      methods: '23',
      callOuts: 62,
      dbCallouts: 53,
      status: 200,
      selected: false,
      severityColor: '#5396d1',
    },
    {
      businessTransaction: 'Dashboard Service',
      url: 'DashboardServer',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '1,063',
      cpu: '154.954',
      methods: '23',
      callOuts: 0,
      dbCallouts: 0,
      status: 200,
      selected: false,
      severityColor: '#89b0d3',
    },
    {
      businessTransaction: 'Dashboard Service/Req',
      url: 'DashboardServer3',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '1,033',
      cpu: '111',
      methods: '203',
      callOuts: 63,
      dbCallouts: 80,
      status: 200,
      selected: false,
      severityColor: '#5396d1',
    },
    {
      businessTransaction: 'Dashboard dummy data',
      url: 'DashboardServer4',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '1,063',
      cpu: '154.3',
      methods: '29',
      callOuts: 68,
      dbCallouts: 50,
      status: 200,
      selected: false,
      severityColor: '#89b0d3',
    },
    {
      businessTransaction: 'Dashboard Req',
      url: 'DashboardServer/Rest',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '2306',
      cpu: '156.954',
      methods: '24',
      callOuts: 62,
      dbCallouts: 69,
      status: 200,
      selected: false,
      severityColor: '#5396d1',
    },
    {
      businessTransaction: 'Dash6',
      url: 'DashboardServer/dummy',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '1,023',
      cpu: '154.950',
      methods: '13',
      callOuts: 19,
      dbCallouts: 60,
      status: 200,
      selected: false,
      severityColor: '#89b0d3',
    },
    {
      businessTransaction: 'Dashboard60',
      url: 'Dashboard/request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '1163',
      cpu: '154.99',
      methods: '23',
      callOuts: 78,
      dbCallouts: 79,
      status: 200,
      selected: false,
      severityColor: '#5396d1',
    },
    {
      businessTransaction: 'Req',
      url: 'kpinfo/request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '1,263',
      cpu: '154.954',
      methods: '230',
      callOuts: 0,
      dbCallouts: 0,
      status: 200,
      selected: false,
      severityColor: '#89b0d3',
    },
    {
      businessTransaction: 'dummy Service/Req',
      url: 'DashboardServer/Service/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '1,639',
      cpu: '154.954',
      methods: '23',
      callOuts: 10,
      dbCallouts: 30,
      status: 200,
      selected: false,
      severityColor: '#5396d1',
    },
    {
      businessTransaction: 'Dashboard Service/Req',
      url: 'DashboardServer/RestService/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '1,063',
      cpu: '154.9',
      methods: '25',
      callOuts: 6,
      dbCallouts: 3,
      status: 200,
      selected: false,
      severityColor: '#89b0d3',
    },
    {
      businessTransaction: 'Req6',
      url: 'DashboardServer/RestService/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '1,0636',
      cpu: '154.954',
      methods: '233',
      callOuts: 0,
      dbCallouts: 0,
      status: 200,
      selected: false,
      severityColor: '#5396d1',
    },
    {
      businessTransaction: 'Req11',
      url: 'DashboardServer/RestService/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '1,069',
      cpu: '154.984',
      methods: '23',
      callOuts: 68,
      dbCallouts: 96,
      status: 200,
      selected: false,
      severityColor: '#89b0d3',
    },
    {
      businessTransaction: 'Req65',
      url: 'DashboardServer/RestService/kpinfo?request',
      category: 'Critical',
      startTime: '08:09(03/24/20)',
      responseTime: '1,063',
      cpu: '154.954',
      methods: '23',
      callOuts: 0,
      dbCallouts: 0,
      status: 400,
      selected: false,
      severityColor: '#5396d1',
    },
    {
      businessTransaction: 'Dashboard Service/Req',
      url: 'DashboardServer/RestService/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '1,063',
      cpu: '154.954',
      methods: '23',
      callOuts: 0,
      dbCallouts: 0,
      status: 200,
      selected: false,
      severityColor: '#89b0d3',
    },
    {
      businessTransaction: 'Dash',
      url: 'DashboardServer/jkl',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '1,516',
      cpu: '159',
      methods: '23',
      callOuts: 62,
      dbCallouts: 53,
      status: 200,
      selected: false,
      severityColor: '#5396d1',
    },
    {
      businessTransaction: 'Dashboard Service',
      url: 'DashboardServer',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '1,063',
      cpu: '154.954',
      methods: '23',
      callOuts: 0,
      dbCallouts: 0,
      status: 200,
      selected: false,
      severityColor: '#89b0d3',
    },
    {
      businessTransaction: 'Dashboard Service/Req',
      url: 'DashboardServer3',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '1,033',
      cpu: '111',
      methods: '203',
      callOuts: 63,
      dbCallouts: 80,
      status: 200,
      selected: false,
      severityColor: '#89b0d3',
    },
    {
      businessTransaction: 'Dashboard dummy data',
      url: 'DashboardServer4',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '1,063',
      cpu: '154.3',
      methods: '29',
      callOuts: 68,
      dbCallouts: 50,
      status: 200,
      selected: false,
      severityColor: '#89b0d3',
    },
    {
      businessTransaction: 'Dashboard Req',
      url: 'DashboardServer/Rest',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '2306',
      cpu: '156.954',
      methods: '24',
      callOuts: 62,
      dbCallouts: 69,
      status: 200,
      selected: false,
      severityColor: '#89b0d3',
    },
    {
      businessTransaction: 'Dash6',
      url: 'DashboardServer/dummy',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '1,023',
      cpu: '154.950',
      methods: '13',
      callOuts: 19,
      dbCallouts: 60,
      status: 200,
      selected: false,
      severityColor: '#89b0d3',
    },
    {
      businessTransaction: 'Dashboard60',
      url: 'Dashboard/request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '1163',
      cpu: '154.99',
      methods: '23',
      callOuts: 78,
      dbCallouts: 79,
      status: 200,
      selected: false,
      severityColor: '#89b0d3',
    },
    {
      businessTransaction: 'Req',
      url: 'kpinfo/request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '1,263',
      cpu: '154.954',
      methods: '230',
      callOuts: 0,
      dbCallouts: 0,
      status: 200,
      selected: false,
      severityColor: '#89b0d3',
    },
    {
      businessTransaction: 'dummy Service/Req',
      url: 'DashboardServer/Service/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '1,639',
      cpu: '154.954',
      methods: '23',
      callOuts: 10,
      dbCallouts: 30,
      status: 200,
      selected: false,
      severityColor: '#89b0d3',
    },
    {
      businessTransaction: 'Dashboard Service/Req',
      url: 'DashboardServer/RestService/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '1,063',
      cpu: '154.9',
      methods: '25',
      callOuts: 6,
      dbCallouts: 3,
      status: 200,
      selected: false,
      severityColor: '#89b0d3',
    },
    {
      businessTransaction: 'Req6',
      url: 'DashboardServer/RestService/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '1,0636',
      cpu: '154.954',
      methods: '233',
      callOuts: 0,
      dbCallouts: 0,
      status: 200,
      selected: false,
      severityColor: '#89b0d3',
    },
    {
      businessTransaction: 'Req11',
      url: 'DashboardServer/RestService/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '1,069',
      cpu: '154.984',
      methods: '23',
      callOuts: 68,
      dbCallouts: 96,
      status: 200,
      selected: false,
      severityColor: '#89b0d3',
    },
    {
      businessTransaction: 'Req65',
      url: 'DashboardServer/RestService/kpinfo?request',
      category: 'Critical',
      startTime: '08:09(03/24/20)',
      responseTime: '1,063',
      cpu: '154.954',
      methods: '23',
      callOuts: 0,
      dbCallouts: 0,
      status: 400,
      selected: false,
      severityColor: '#89b0d3',
    },
    {
      businessTransaction: 'Dashboard Service/Req',
      url: 'DashboardServer/RestService/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '1,063',
      cpu: '154.954',
      methods: '23',
      callOuts: 0,
      dbCallouts: 0,
      status: 200,
      selected: false,
      severityColor: '#89b0d3',
    },
    {
      businessTransaction: 'Dash',
      url: 'DashboardServer/jkl',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '1,516',
      cpu: '159',
      methods: '23',
      callOuts: 62,
      dbCallouts: 53,
      status: 200,
      selected: false,
      severityColor: '#89b0d3',
    },
    {
      businessTransaction: 'Dashboard Service',
      url: 'DashboardServer',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '1,063',
      cpu: '154.954',
      methods: '23',
      callOuts: 0,
      dbCallouts: 0,
      status: 200,
      selected: false,
      severityColor: '#89b0d3',
    },
  ],
  paginator: {
    first: 1,
    rows: 10,
    rowsPerPageOptions: [ 10, 20,30, 50, 100],
  },
  tableFilter: true,
  severityBgColorField: 'severityColor',
};

