import { NewCommand } from './new-command.model';

export const NEW_COMMAND_DATA: NewCommand = {
  dropDownOptions: {
    tireName: [
      { label: 'Tier', value: 'tier' },
      { label: 'Tier Name', value: 'tierName' },
    ],
    serverName: [
      { label: 'Server', value: 'server' },
      { label: 'Server Name', value: 'serverName' },
    ],
    groupName: [
      { label: 'Group', value: 'group' },
      { label: 'Group Name', value: 'groupName' },
    ],
    commandName: [
      { label: 'Command', value: 'command' },
      { label: 'Command Name', value: 'commandName' },
    ],
    filterOptions: [
      { label: 'Show Top', value: 'showTop' },
      { label: 'Show Bottom', value: 'showBottom' },
    ],
    viewType: [
      { label: 'text', value: 'text' },
      {
        label: 'number',
        value: 'number',
      },
    ],
  },
  commandDetails: {
    commandReportList: [
      {
        details: 'report',
      },
      {
        details: 'report',
      },
      {
        details: 'report',
      },
      {
        details: 'report',
      },
      {
        details: 'report',
      },
      {
        details: 'report',
      },
      {
        details: 'report',
      },
      {
        details: 'report',
      },
      {
        details: 'report',
      },
      {
        details: 'report',
      },
      {
        details: 'report',
      },
      {
        details: 'report',
      },
      {
        details: 'report',
      },
      {
        details: 'report',
      },
      {
        details: 'report',
      },
      {
        details: 'report',
      },
      {
        details: 'report',
      },
      {
        details: 'report',
      },
      {
        details: 'report',
      },
      {
        details: 'report',
      },
    ],
    commandData: {
      paginator: {
        first: 0,
        rows: 10,
        rowsPerPageOptions: [10, 20, 30, 50, 100],
      },
      headers: [
        {
          cols: [
            {
              label: 'Start Time',
              valueField: 'startTime',
              classes: 'text-center',
              selected: true,
              filter: {
                isFilter: true,
                type: 'contains',
              },
              isSort: true,
            },
            {
              label: 'Run Time',
              valueField: 'runTime',
              classes: 'text-center',
              selected: true,
              filter: {
                isFilter: true,
                type: 'contains',
              },
              isSort: true,
            },
            {
              label: 'User',
              valueField: 'user',
              classes: 'text-center',
              selected: true,
              filter: {
                isFilter: true,
                type: 'contains',
              },
              isSort: true,
            },
            {
              label: 'Started By',
              valueField: 'startedBy',
              classes: 'text-center',
              selected: true,
              filter: {
                isFilter: true,
                type: 'contains',
              },
              isSort: true,
            },
            {
              label: 'Notes',
              valueField: 'notes',
              classes: 'text-center',
              selected: true,
              filter: {
                isFilter: true,
                type: 'contains',
              },
              isSort: true,
            },
          ],
        },
      ],
      data: [
        {
          no: '1',
          testRun: '11001',
          testName: 'NDE_DashboardTesting',
          scnrName: 'NDE_DashboardTesting',
          startTime: '23:51:24 02/03/20',
          runTime: '01:05:00',
          user: '20',
          startedBy: 'Cavisson',
          notes: 'NA',
        },
        {
          no: '2',
          testRun: '11001',
          testName: 'NDE_DashboardTesting',
          scnrName: 'NDE_DashboardTesting',
          startTime: '23:51:24 02/03/20',
          runTime: '01:05:00',
          user: '20',
          startedBy: 'Cavisson',
          notes: 'NA',
        },
        {
          no: '3',
          testRun: '11001',
          testName: 'NDE_DashboardTesting',
          scnrName: 'NDE_DashboardTesting',
          startTime: '23:51:24 02/03/20',
          runTime: '01:05:00',
          user: '20',
          startedBy: 'Cavisson',
          notes: 'NA',
        },
        {
          no: '4',
          testRun: '11001',
          testName: 'NDE_DashboardTesting',
          scnrName: 'NDE_DashboardTesting',
          startTime: '23:51:24 02/03/20',
          runTime: '01:05:00',
          user: '20',
          startedBy: 'Cavisson',
          notes: 'NA',
        },
        {
          no: '5',
          testRun: '11001',
          testName: 'NDE_DashboardTesting',
          scnrName: 'NDE_DashboardTesting',
          startTime: '23:51:24 02/03/20',
          runTime: '01:05:00',
          user: '20',
          startedBy: 'Cavisson',
          notes: 'NA',
        },
        {
          no: '6',
          testRun: '11001',
          testName: 'NDE_DashboardTesting',
          scnrName: 'NDE_DashboardTesting',
          startTime: '23:51:24 02/03/20',
          runTime: '01:05:00',
          user: '20',
          startedBy: 'Cavisson',
          notes: 'NA',
        },
        {
          no: '7',
          testRun: '11001',
          testName: 'NDE_DashboardTesting',
          scnrName: 'NDE_DashboardTesting',
          startTime: '23:51:24 02/03/20',
          runTime: '01:05:00',
          user: '20',
          startedBy: 'Cavisson',
          notes: 'NA',
        },
        {
          no: '8',
          testRun: '11001',
          testName: 'NDE_DashboardTesting',
          scnrName: 'NDE_DashboardTesting',
          startTime: '23:51:24 02/03/20',
          runTime: '01:05:00',
          user: '20',
          startedBy: 'Cavisson',
          notes: 'NA',
        },
        {
          no: '9',
          testRun: '11001',
          testName: 'NDE_DashboardTesting',
          scnrName: 'NDE_DashboardTesting',
          startTime: '23:51:24 02/03/20',
          runTime: '01:05:00',
          user: '20',
          startedBy: 'Cavisson',
          notes: 'NA',
        },
        {
          no: '10',
          testRun: '11001',
          testName: 'NDE_DashboardTesting',
          scnrName: 'NDE_DashboardTesting',
          startTime: '23:51:24 02/03/20',
          runTime: '01:05:00',
          user: '20',
          startedBy: 'Cavisson',
          notes: 'NA',
        },
        {
          no: '11',
          testRun: '11001',
          testName: 'NDE_DashboardTesting',
          scnrName: 'NDE_DashboardTesting',
          startTime: '23:51:24 02/03/20',
          runTime: '01:05:00',
          user: '20',
          startedBy: 'Cavisson',
          notes: 'NA',
        },
        {
          no: '12',
          testRun: '11001',
          testName: 'NDE_DashboardTesting',
          scnrName: 'NDE_DashboardTesting',
          startTime: '23:51:24 02/03/20',
          runTime: '01:05:00',
          user: '20',
          startedBy: 'Cavisson',
          notes: 'NA',
        },
        {
          no: '13',
          testRun: '11001',
          testName: 'NDE_DashboardTesting',
          scnrName: 'NDE_DashboardTesting',
          startTime: '23:51:24 02/03/20',
          runTime: '01:05:00',
          user: '20',
          startedBy: 'Cavisson',
          notes: 'NA',
        },
        {
          no: '14',
          testRun: '11001',
          testName: 'NDE_DashboardTesting',
          scnrName: 'NDE_DashboardTesting',
          startTime: '23:51:24 02/03/20',
          runTime: '01:05:00',
          user: '20',
          startedBy: 'Cavisson',
          notes: 'NA',
        },
        {
          no: '15',
          testRun: '11001',
          testName: 'NDE_DashboardTesting',
          scnrName: 'NDE_DashboardTesting',
          startTime: '23:51:24 02/03/20',
          runTime: '01:05:00',
          user: '20',
          startedBy: 'Cavisson',
          notes: 'NA',
        },
        {
          no: '16',
          testRun: '11001',
          testName: 'NDE_DashboardTesting',
          scnrName: 'NDE_DashboardTesting',
          startTime: '23:51:24 02/03/20',
          runTime: '01:05:00',
          user: '20',
          startedBy: 'Cavisson',
          notes: 'NA',
        },
        {
          no: '17',
          testRun: '11001',
          testName: 'NDE_DashboardTesting',
          scnrName: 'NDE_DashboardTesting',
          startTime: '23:51:24 02/03/20',
          runTime: '01:05:00',
          user: '20',
          startedBy: 'Cavisson',
          notes: 'NA',
        },
        {
          no: '18',
          testRun: '11001',
          testName: 'NDE_DashboardTesting',
          scnrName: 'NDE_DashboardTesting',
          startTime: '23:51:24 02/03/20',
          runTime: '01:05:00',
          user: '20',
          startedBy: 'Cavisson',
          notes: 'NA',
        },
        {
          no: '19',
          testRun: '11001',
          testName: 'NDE_DashboardTesting',
          scnrName: 'NDE_DashboardTesting',
          startTime: '23:51:24 02/03/20',
          runTime: '01:05:00',
          user: '20',
          startedBy: 'Cavisson',
          notes: 'NA',
        },
        {
          no: '20',
          testRun: '11001',
          testName: 'NDE_DashboardTesting',
          scnrName: 'NDE_DashboardTesting',
          startTime: '23:51:24 02/03/20',
          runTime: '01:05:00',
          user: '20',
          startedBy: 'Cavisson',
          notes: 'NA',
        },
        {
          no: '21',
          testRun: '11001',
          testName: 'NDE_DashboardTesting',
          scnrName: 'NDE_DashboardTesting',
          startTime: '23:51:24 02/03/20',
          runTime: '01:05:00',
          user: '20',
          startedBy: 'Cavisson',
          notes: 'NA',
        },
        {
          no: '22',
          testRun: '11001',
          testName: 'NDE_DashboardTesting',
          scnrName: 'NDE_DashboardTesting',
          startTime: '23:51:24 02/03/20',
          runTime: '01:05:00',
          user: '20',
          startedBy: 'Cavisson',
          notes: 'NA',
        },
        {
          no: '23',
          testRun: '11001',
          testName: 'NDE_DashboardTesting',
          scnrName: 'NDE_DashboardTesting',
          startTime: '23:51:24 02/03/20',
          runTime: '01:05:00',
          user: '20',
          startedBy: 'Cavisson',
          notes: 'NA',
        },
        {
          no: '24',
          testRun: '11001',
          testName: 'NDE_DashboardTesting',
          scnrName: 'NDE_DashboardTesting',
          startTime: '23:51:24 02/03/20',
          runTime: '01:05:00',
          user: '20',
          startedBy: 'Cavisson',
          notes: 'NA',
        },
        {
          no: '25',
          testRun: '11001',
          testName: 'NDE_DashboardTesting',
          scnrName: 'NDE_DashboardTesting',
          startTime: '23:51:24 02/03/20',
          runTime: '01:05:00',
          user: '20',
          startedBy: 'Cavisson',
          notes: 'NA',
        },
        {
          no: '26',
          testRun: '11001',
          testName: 'NDE_DashboardTesting',
          scnrName: 'NDE_DashboardTesting',
          startTime: '23:51:24 02/03/20',
          runTime: '01:05:00',
          user: '20',
          startedBy: 'Cavisson',
          notes: 'NA',
        },
        {
          no: '27',
          testRun: '11001',
          testName: 'NDE_DashboardTesting',
          scnrName: 'NDE_DashboardTesting',
          startTime: '23:51:24 02/03/20',
          runTime: '01:05:00',
          user: '20',
          startedBy: 'Cavisson',
          notes: 'NA',
        },
      ],
      tableFilter: true,
    },
    serverName: 'Server Name',
    commandName: 'Command Name',
    serverTime: '1/02/2020 01:12:34(CST)',
  },
};
