import { ClusterMonitor } from './cluster-monitor.model';

export const CLUSTER_MONITOR_DATA: ClusterMonitor = {
  charts: [
    {
      title: 'CPU',
      highchart: {
        chart: {
          type: 'spline',
          height:'250px'
        },

        title: {
          text: null,
        },
        legend: {
          enabled: false,
        },
        xAxis: {
          allowDecimals: false,
          categories:[],
          accessibility: {
            rangeDescription: 'Range: 1940 to 2017.',
          },
        },
        yAxis: {
          title: {
            text: null,
          },
        },
        tooltip: {
          pointFormat:
            '{series.name} had stockpiled <b>{point.y:,.0f}</b><br/>warheads in {point.x}',
        },
        plotOptions: {
          spline: {
            pointStart: 1940,
            marker: {
              enabled: false,
              symbol: 'circle',
              radius: 2,
              states: {
                hover: {
                  enabled: true,
                },
              },
            },
          },
        },
        series: [
          {
            name: 'USA',
            data: [
            
            ],
          },
          // {
          //   name: 'USSR/Russia',
          //   data: [
          //     null,
          //     null,
          //     null,
          //     null,
          //     null,
          //     null,
          //     null,
          //     null,
          //     null,
          //     null,
          //     5,
          //     25,
          //     50,
          //     120,
          //     150,
          //     200,
          //     426,
          //     660,
          //     869,
          //     1060,
          //     1605,
          //     2471,
          //     3322,
          //     4238,
          //     5221,
          //     6129,
          //     7089,
          //     8339,
          //     9399,
          //     10538,
          //     11643,
          //     13092,
          //     14478,
          //     15915,
          //     17385,
          //     19055,
          //     21205,
          //     23044,
          //     25393,
          //     27935,
          //     30062,
          //     32049,
          //     33952,
          //     35804,
          //     37431,
          //     39197,
          //     45000,
          //     43000,
          //     41000,
          //     39000,
          //     37000,
          //     35000,
          //     33000,
          //     31000,
          //     29000,
          //     27000,
          //     25000,
          //     24000,
          //     23000,
          //     22000,
          //     21000,
          //     20000,
          //     19000,
          //     18000,
          //     18000,
          //     17000,
          //     16000,
          //     15537,
          //     14162,
          //     12787,
          //     12600,
          //     11400,
          //     5500,
          //     4512,
          //     4502,
          //     4502,
          //     4500,
          //     4500,
          //   ],
          // },
        ] as Highcharts.SeriesOptionsType[],
      },
    },
    {
      title: 'Memory',
      highchart: {
        chart: {
          type: 'spline',
          height:'250px'
        },

        title: {
          text: null,
        },
        legend: {
          enabled: false,
        },
        xAxis: {
          allowDecimals: false,
          accessibility: {
            rangeDescription: 'Range: 1940 to 2017.',
          },
        },
        yAxis: {
          title: {
            text: null,
          },
        },
        tooltip: {
          pointFormat:
            '{series.name} had stockpiled <b>{point.y:,.0f}</b><br/>warheads in {point.x}',
        },
        plotOptions: {
          spline: {
            pointStart: 1940,
            marker: {
              enabled: false,
              symbol: 'circle',
              radius: 2,
              states: {
                hover: {
                  enabled: true,
                },
              },
            },
          },
        },
        series: [
          {
            name: '',
            data: [
             
            ],
          },
          // {
          //   name: 'USSR/Russia',
          //   data: [
          //     null,
          //     null,
          //     null,
          //     null,
          //     null,
          //     null,
          //     null,
          //     null,
          //     null,
          //     null,
          //     5,
          //     25,
          //     50,
          //     120,
          //     150,
          //     200,
          //     426,
          //     660,
          //     869,
          //     1060,
          //     1605,
          //     2471,
          //     3322,
          //     4238,
          //     5221,
          //     6129,
          //     7089,
          //     8339,
          //     9399,
          //     10538,
          //     11643,
          //     13092,
          //     14478,
          //     15915,
          //     17385,
          //     19055,
          //     21205,
          //     23044,
          //     25393,
          //     27935,
          //     30062,
          //     32049,
          //     33952,
          //     35804,
          //     37431,
          //     39197,
          //     45000,
          //     43000,
          //     41000,
          //     39000,
          //     37000,
          //     35000,
          //     33000,
          //     31000,
          //     29000,
          //     27000,
          //     25000,
          //     24000,
          //     23000,
          //     22000,
          //     21000,
          //     20000,
          //     19000,
          //     18000,
          //     18000,
          //     17000,
          //     16000,
          //     15537,
          //     14162,
          //     12787,
          //     12600,
          //     11400,
          //     5500,
          //     4512,
          //     4502,
          //     4502,
          //     4500,
          //     4500,
          //   ],
          // },
        ] as Highcharts.SeriesOptionsType[],
      },
    },
    {
      title: 'Docs/Sec',
      highchart: {
        chart: {
          type: 'spline',
          height:'250px'
        },

        title: {
          text: null,
        },
        legend: {
          enabled: false,
        },
        xAxis: {
          allowDecimals: false,
          accessibility: {
            rangeDescription: 'Range: 1940 to 2017.',
          },
        },
        yAxis: {
          title: {
            text: null,
          },
        },
        tooltip: {
          pointFormat:
            '{series.name} had stockpiled <b>{point.y:,.0f}</b><br/>warheads in {point.x}',
        },
        plotOptions: {
          area: {
            pointStart: 1940,
            marker: {
              enabled: false,
              symbol: 'circle',
              radius: 2,
              states: {
                hover: {
                  enabled: true,
                },
              },
            },
          },
        },
        series: [
          {
            name: 'USA',
            data: [
             
            ],
          },
          // {
          //   name: 'USSR/Russia',
          //   data: [
          //     null,
          //     null,
          //     null,
          //     null,
          //     null,
          //     null,
          //     null,
          //     null,
          //     null,
          //     null,
          //     5,
          //     25,
          //     50,
          //     120,
          //     150,
          //     200,
          //     426,
          //     660,
          //     869,
          //     1060,
          //     1605,
          //     2471,
          //     3322,
          //     4238,
          //     5221,
          //     6129,
          //     7089,
          //     8339,
          //     9399,
          //     10538,
          //     11643,
          //     13092,
          //     14478,
          //     15915,
          //     17385,
          //     19055,
          //     21205,
          //     23044,
          //     25393,
          //     27935,
          //     30062,
          //     32049,
          //     33952,
          //     35804,
          //     37431,
          //     39197,
          //     45000,
          //     43000,
          //     41000,
          //     39000,
          //     37000,
          //     35000,
          //     33000,
          //     31000,
          //     29000,
          //     27000,
          //     25000,
          //     24000,
          //     23000,
          //     22000,
          //     21000,
          //     20000,
          //     19000,
          //     18000,
          //     18000,
          //     17000,
          //     16000,
          //     15537,
          //     14162,
          //     12787,
          //     12600,
          //     11400,
          //     5500,
          //     4512,
          //     4502,
          //     4502,
          //     4500,
          //     4500,
          //   ],
          // },
        ] as Highcharts.SeriesOptionsType[],
      },
    },
  ],
  clusterStats: [
    // {
    //   label: 'Nodes',
    //   value: '2',
    // },
    // {
    //   label: 'Total Shards',
    //   value: '161',
    // },
    // {
    //   label: 'Successful Shards',
    //   value: '161',
    // },
    // {
    //   label: 'Indices',
    //   value: '33',
    // },
    // {
    //   label: 'Documents',
    //   value: '11732654',
    // },
    // {
    //   label: 'Size',
    //   value: '48.0GB',
    // },
  ],
  clusterHealth: {
    headers: [
      {
        cols: [
          {
            label: 'Label',
            valueField: 'label',
            classes: 'text-center',
            filter: {
              isFilter: true,
              type: 'contains',
            },
          },
          {
            label: 'Value',
            valueField: 'value',
            classes: 'text-right',
            statusField: true,
                        filter: {
              isFilter: true,
              type: 'contains',
            },
          },
        ],
      },
    ],
    data: [
      // {
      //   label: 'Status',
      //   value: 'Normal',
      //   stats: true,
      // },
      // {
      //   label: 'Document Deleted',
      //   value: '2.0 GB',
      // },
      // {
      //   label: 'Store Size',
      //   value: '2.0 GB',
      // },
      // {
      //   label: 'Index Req Total',
      //   value: '2.0 GB',
      // },
      // {
      //   label: 'Document Deleted',
      //   value: '2.0 GB',
      // },
      // {
      //   label: 'Document Deleted',
      //   value: '2.0 GB',
      // },
      // {
      //   label: 'Document Deleted',
      //   value: '2.0 GB',
      // },
      // {
      //   label: 'Document Deleted',
      //   value: '2.0 GB',
      // },
      // {
      //   label: 'Document Deleted',
      //   value: '2.0 GB',
      // },
    ],
    statsField: 'stats',
  },
  clusterIndices: {
    headers: [
      {
        cols: [
          {
            label: 'Index',
            valueField: 'index',
            filter: {
              isFilter: true,
              type: 'contains',
            },
            isSort:true,
            width:'30%'
          },
          {
            label: 'Docs',
            valueField: 'docs',
            classes: 'text-right',
            filter: {
              isFilter: true,
              type: 'contains',
            },
            isSort:true,
          },
          {
            label: 'Docs/Sec',
            valueField: 'doc_sec',
            classes: 'text-right',
            filter: {
              isFilter: true,
              type: 'contains',
            },
            isSort:true,
          },
          {
            label: 'Primary Size',
            valueField: 'primarySize',
            classes: 'text-right',
            filter: {
              isFilter: true,
              type: 'contains',
            },
            isSort:true,
          },
          {
            label: 'Shards',
            valueField: 'shards',
            classes: 'text-right',
            filter: {
              isFilter: true,
              type: 'contains',
            },
            isSort:true,
          },
          {
            label: 'Replicas',
            valueField: 'replicas',
            classes: 'text-right',
            filter: {
              isFilter: true,
              type: 'contains',
            },
            isSort:true,
          },
          {
            label: 'Status',
            valueField: 'status',
            classes: 'text-right',
            filter: {
              isFilter: true,
              type: 'contains',
            },
            isSort:true,
          },
        ],
      },
    ],
    data: [
      {
        index: 'netForest_monitoring-2020-05-21',
        docs: '323.5KB',
        doc_sec: '0',
        primarySize: '23.5KB',
        shards: '0',
        replicas: '0',
        status: 'Open',
      },
      {
        index: 'netForest_monitoring-2020-05-22',
        docs: '333.5KB',
        doc_sec: '0',
        primarySize: '23.5KB',
        shards: '0',
        replicas: '0',
        status: 'Open',
      },
      {
        index: 'netForest_monitoring-2020-05-23',
        docs: '523.5KB',
        doc_sec: '0',
        primarySize: '23.5KB',
        shards: '0',
        replicas: '0',
        status: 'Open',
      },
      {
        index: 'netForest_monitoring-2020-05-24',
        docs: '34.5KB',
        doc_sec: '0',
        primarySize: '23.5KB',
        shards: '0',
        replicas: '0',
        status: 'Open',
      },
      {
        index: 'netForest_monitoring-2020-05-25',
        docs: '73.5KB',
        doc_sec: '0',
        primarySize: '23.5KB',
        shards: '0',
        replicas: '0',
        status: 'Open',
      },
      {
        index: 'netForest_monitoring-2020-05-26',
        docs: '345.5KB',
        doc_sec: '0',
        primarySize: '23.5KB',
        shards: '0',
        replicas: '0',
        status: 'Open',
      },
      {
        index: 'netForest_monitoring-2020-05-1',
        docs: '.45KB',
        doc_sec: '0',
        primarySize: '23.5KB',
        shards: '0',
        replicas: '0',
        status: 'Open',
      },
      {
        index: 'netForest_monitoring-2020-05-2',
        docs: '23.5KB',
        doc_sec: '0',
        primarySize: '23.5KB',
        shards: '0',
        replicas: '0',
        status: 'Open',
      },
      {
        index: 'netForest_monitoring-2020-05-3',
        docs: '33.5KB',
        doc_sec: '0',
        primarySize: '23.5KB',
        shards: '0',
        replicas: '0',
        status: 'Open',
      },
      {
        index: 'netForest_monitoring-2020-05-4',
        docs: '32.5KB',
        doc_sec: '0',
        primarySize: '23.5KB',
        shards: '0',
        replicas: '0',
        status: 'Open',
      },
    ],
  },
};
