export const spaceVal = "+";
export const singleQuotesVal = '%27';
export const commaVal = '%2C';
export const doubleQuotesVal = '%22';
export const backSlashVal ="%5C";
export const semiColonVal = '%3B';
export const dashVal = '-';
export const equalVal = '%3D' ;
export const tabVal = '%09';
