export const LONG_FORMAT_MON_TYPE_ARG = "--monType"; // Monitor type for new Options (CMD-1/REST-2/MBEAN-3/DB-4)
export const LONG_FORMAT_OUTPUT_TYPE_ARG = "--respType";// Output type for new Options (string-1/keyValue-2/JSON-3/JMX-4) of configured monitor
export const LONG_FORMAT_RETRY_ARG = "--maxRetryCount";// Count of maximum retry to make connection
export const LONG_FORMAT_DELETE_VECTOR_ARG = "--vecPersistTime"; // delVecTime for new Options
export const LONG_FORMAT_INTERVAL_ARG = "--interval"; // intervaL for new Options
export const LONG_FORMAT_TIER_ARG = "--tier"; // Tier for new Options
export const LONG_FORMAT_SERVER_ARG = "--server"; // server for new Options
export const LONG_FORMAT_HOST_ARG = "--host"; //  host
export const LONG_FORMAT_PORT_ARG = "--port"; //  port
export const LONG_FORMAT_USER_ARG = "--user"; //  user
export const LONG_FORMAT_PWD_ARG = "--pwd"; //  password
export const LONG_FORMAT_REMOTE_TIER_ARG = "--remoteTierUI"; // remote Tier 
export const LONG_FORMAT_REMOTE_SERVER_ARG = "--remoteServerUI"; // remote server 
export const LONG_FORMAT_REMOTE_HOST_ARG = "--remoteHost"; // Remote host
export const LONG_FORMAT_REMOTE_PORT_ARG = "--remotePort"; // Remote port
export const LONG_FORMAT_REMOTE_USER_ARG = "--remoteUser"; // Remote user
export const LONG_FORMAT_REMOTE_PWD_ARG = "--remotePwd"; // Remote password
export const LONG_FORMAT_PRIVATE_KEY_ARG = "--privateKey"; // private key
export const LONG_FORMAT_PASSPHRASE_ARG = "--passphrase"; // passphrase
export const LONG_FORMAT_PUBLIC_KEY_ARG = "--publicKey"; // public key
export const LONG_FORMAT_PROXY_HOST_ARG = "--proxyHost"; // Proxy host
export const LONG_FORMAT_PROXY_PORT_ARG = "--proxyPort"; // Proxy port
export const LONG_FORMAT_PROXY_USER_ARG = "--proxyUser"; // Proxy username
export const LONG_FORMAT_PROXY_PWD_ARG = "--proxyPwd"; // Proxy password
export const LONG_FORMAT_DB_NAME_ARG ="--dbName"; //DB name
export const LONG_FORMAT_AUTH_TYPE_ARG = "--authMode"; // Auth type
export const LONG_FORMAT_SID_ARG = "--sid"; //SID
export const LONG_FORMAT_TRUST_STORE_FILE_ARG = "--truststoreFile"; //Trust store file path
export const LONG_FORMAT_TRUST_STORE_PASSWORD_ARG = "--truststorePwd" // Trust store password
export const LONG_FORMAT_KEY_STORE_FILE_ARG = "--keystoreFile" // Key store file path
export const LONG_FORMAT_KEY_STORE_PASSWORD_ARG = "--keystorePwd" //key store password
export const LONG_FORMAT_TRUST_STORE_FILE_TYPE_ARG = "--truststoreFileType" // Trust store file path
export const LONG_FORMAT_VECTOR_PERSIST_COUNT_ARG = "--vecPersistCount" // Vector persist count
export const LONG_FORMAT_IS_REFRESH_ARG = "--isRefresh" // IS REFRESH 
export const LONG_FORMAT_SERVICE_ACCOUNT_FILE_ARG = "--serviceAccFile"// Service account file 
export const LONG_FORMAT_SERVICE_ACCOUNT_TOKEN_FILE_PATH_ARG = "--SATokenFilePath" //Service account token file path
export const LONG_FORMAT_CONN_PARAMS_ARG = "--connParams" //Connection params
export const LONG_FORMAT_IS_ENCRYPTED_DATA_ARG = "--isDataEncrypt"; // encrypted data
export const LONG_FORMAT_DB_QUERY_ARG = "--dbQuery"; // Db query
export const LONG_FORMAT_INSTANCE_ARG = "--instance"; //  instance
export const LONG_FORMAT_VECTOR_PREFIX = "--vecPrefix"; // vecPrefix
export const LONG_FORMAT_TWO_SSL_ENABLE_ARG = "--isTwoWaySSL"; //SSL enable
export const LONG_FORMAT_JMX_CONNECTOR_SEARCH_PATTERN_ARG = "--searchPattern"; //JMX connector search pattern
export const LONG_FORMAT_JMX_CONNECTION_URL_ARG = "--url"; //Jmx connection url
export const LONG_FORMAT_PID_ARG = "--pid"; //Process id for JMX monitor
export const LONG_FORMAT_PID_FILE_ARG = "--pidFile"; //Process Id file 
export const LONG_FORMAT_OCCURENCE_COUNT_ARG = "--index"; 
export const LONG_FORMAT_IS_PWD_ENCRYPT = "--isEncryptPwd"; // for bug 105099
