import { BusinessView } from './business-view.model';

export const BUSINESS_VIEW_TIER_COMPONENT: BusinessView = {
  businessTierComponent: {
    node: [
      {
        icon: './assets/icons8-png/icons8-database-100.png',
        nodeName: 'Database',
        from: 'crop',
        to: 'cprod-blue-cscui-prod',
        id: 'dashboard',
        type: 'actionNode',
        top: -2.98152,
        left: 218.61,
        calls: 10,
        networks: 17,
        docs: 10,
        businessHealthCriticalCircum: 120,
        businessHealthMajorCircum: 200,
        serverInfo: [
          {
            serverName: 'Server 1',
            networks: 5,
            calls: 77,
            docs: 10,
            icon: 'icons8-globe',
          },
          {
            serverName: 'Server 1',
            networks: 5,
            calls: 77,
            docs: 10,
            icon: 'icons8-indeterminate-checkbox',
          },
          {
            serverName: 'Server 1',
            networks: 5,
            calls: 77,
            docs: 10,
            icon: 'icons8-combo-chart',
          },
          {
            serverName: 'Server 1',
            networks: 5,
            calls: 77,
            docs: 10,
            icon: 'icons8-bar-chart',
          },
        ],
      },
      {
        icon: './assets/icons8-png/icons8-database-100.png',
        nodeName: 'SNB',
        from: 'crop',
        to: 'cprod-blue-cscui-prod',
        id: 'snb',
        type: 'actionNode',
        top: 39.2709,
        left: 562.317,
        calls: 10,
        networks: 17,
        docs: 10,
        businessHealthCriticalCircum: 120,
        businessHealthMajorCircum: 200,
        serverInfo: [
          {
            serverName: 'Server 1',
            networks: 5,
            calls: 77,
            docs: 10,
            icon: 'icons8-globe',
          },
          {
            serverName: 'Server 1',
            networks: 5,
            calls: 77,
            docs: 10,
            icon: 'icons8-indeterminate-checkbox',
          },
          {
            serverName: 'Server 1',
            networks: 5,
            calls: 77,
            docs: 10,
            icon: 'icons8-combo-chart',
          },
          {
            serverName: 'Server 1',
            networks: 5,
            calls: 77,
            docs: 10,
            icon: 'icons8-bar-chart',
          },
        ],
      },
      {
        icon: './assets/icons8-png/icons8-database-100.png',
        nodeName: 'SNB UI',
        from: 'crop',
        to: 'cprod-blue-cscui-prod',
        id: 'snb-ui',
        type: 'actionNode',
        top: 205.11,
        left: 802.259,
        calls: 10,
        networks: 17,
        docs: 10,
        businessHealthCriticalCircum: 120,
        businessHealthMajorCircum: 200,
        serverInfo: [
          {
            serverName: 'Server 1',
            networks: 5,
            calls: 77,
            docs: 10,
            icon: 'icons8-globe',
          },
          {
            serverName: 'Server 1',
            networks: 5,
            calls: 77,
            docs: 10,
            icon: 'icons8-indeterminate-checkbox',
          },
          {
            serverName: 'Server 1',
            networks: 5,
            calls: 77,
            docs: 10,
            icon: 'icons8-combo-chart',
          },
          {
            serverName: 'Server 1',
            networks: 5,
            calls: 77,
            docs: 10,
            icon: 'icons8-bar-chart',
          },
        ],
      },
      {
        icon: './assets/icons8-png/icons8-database-100.png',
        nodeName: 'CNC',
        from: 'crop',
        to: 'cprod-blue-cscui-prod',
        id: 'cnc',
        type: 'actionNode',
        top: -134.104,
        left: 804.814,
        calls: 10,
        networks: 17,
        docs: 10,
        businessHealthCriticalCircum: 120,
        businessHealthMajorCircum: 200,
        serverInfo: [
          {
            serverName: 'Server 1',
            networks: 5,
            calls: 77,
            docs: 10,
            icon: 'icons8-globe',
          },
          {
            serverName: 'Server 1',
            networks: 5,
            calls: 77,
            docs: 10,
            icon: 'icons8-indeterminate-checkbox',
          },
          {
            serverName: 'Server 1',
            networks: 5,
            calls: 77,
            docs: 10,
            icon: 'icons8-combo-chart',
          },
          {
            serverName: 'Server 1',
            networks: 5,
            calls: 77,
            docs: 10,
            icon: 'icons8-bar-chart',
          },
        ],
      },
      {
        icon: './assets/icons8-png/icons8-database-100.png',
        nodeName: 'CNC UI',
        from: 'crop',
        to: 'cprod-blue-cscui-prod',
        id: 'cnc-ui',
        type: 'actionNode',
        top: -209.052,
        left: 441.063,
        calls: 10,
        networks: 17,
        docs: 10,
        businessHealthCriticalCircum: 120,
        businessHealthMajorCircum: 200,
        serverInfo: [
          {
            serverName: 'Server 1',
            networks: 5,
            calls: 77,
            docs: 10,
            icon: 'icons8-globe',
          },
          {
            serverName: 'Server 1',
            networks: 5,
            calls: 77,
            docs: 10,
            icon: 'icons8-indeterminate-checkbox',
          },
          {
            serverName: 'Server 1',
            networks: 5,
            calls: 77,
            docs: 10,
            icon: 'icons8-combo-chart',
          },
          {
            serverName: 'Server 1',
            networks: 5,
            calls: 77,
            docs: 10,
            icon: 'icons8-bar-chart',
          },
        ],
      },
      {
        icon: './assets/icons8-png/icons8-database-100.png',
        nodeName: 'Solar Pref',
        id: 'output-1',
        type: 'outputNode',
        top: -161.343,
        left: 1310.45,
      },
      {
        icon: './assets/icons8-png/icons8-indeterminate-checkbox-100.png',
        nodeName: 'Solar Pref',
        id: 'output-2',
        type: 'outputNode',
        top: -104.885,
        left: 1309.25,
      },
      {
        icon: './assets/icons8-png/icons8-globe-100.png',
        nodeName: 'Solar Pref',
        id: 'output-3',
        type: 'outputNode',
        top: -47.2259,
        left: 1315.26,
      },
    ],
    edge: [
      {
        source: 'database',
        target: 'snb',
      },
      {
        source: 'snb-ui',
        target: 'cnc',
      },
      {
        source: 'cnc-ui',
        target: 'output-1',
      },
      {
        source: 'cnc-ui',
        target: 'output-2',
      },
    ],
  },
};
