import { TransactionGroupTable } from './transactions-group.model';

export const TRANSACTION_GROUP_TABLE: TransactionGroupTable = {
    headers: [
    {
      cols: [
        {
          label: 'Business Transaction',
          valueField: 'businessTransaction',
          classes: 'text-left',
          selected: false,
          filter: {
            isFilter: true,
            type: 'contains',
          },
          isSort: true,
          width:'10%'
        },
        {
          label: 'URL',
          valueField: 'url',
          classes: 'text-left',
          selected: true,
          filter: {
            isFilter: true,
            type: 'contains',
          },
          isSort: true,
          width:'10%'
        },
        {
          label: 'Category',
          valueField: 'category',
          classes: 'text-center',
          selected: true,
          filter: {
            isFilter: true,
            type: 'contains',
          },
          isSort: true,
          width:'10%'
        },
        {
          label: 'Start Time',
          valueField: 'startTime',
          classes: 'text-center',
          selected: true,
          filter: {
            isFilter: true,
            type: 'contains',
          },
          isSort: true,
          width:'10%'
        },
        {
          label: 'Response Time',
          valueField: 'responseTime',
          classes: 'text-center',
          selected: true,
          filter: {
            isFilter: true,
            type: 'contains',
          },
          isSort: true,
          width:'10%'
        },
        {
          label: 'CPU Time(ms)',
          valueField: 'cpu',
          classes: 'text-center',
          selected: true,
          filter: {
            isFilter: true,
            type: 'contains',
          },
          isSort: true,
        }
      ],
    },
  ],
  data: [
    {
      businessTransaction: 'Dashboard Service/Req',
      url: 'dshboardServer/RestService/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '1,223',
      cpu: '154.954',
      severityBgColorField: '#89b0d3',
    },
    {
      businessTransaction: 'Dashboard Service/Req',
      url: 'dshboardServer/RestService/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '1,373',
      cpu: '154.954',
      severityBgColorField: '#337ABA',
    },
    {
      businessTransaction: 'Dashboard1 Service/Req',
      url: 'dshboardServer/RestService/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '1,063',
      cpu: '122.954',
      severityBgColorField: '#89b0d3',
    },
    {
      businessTransaction: 'Dashboard Service/Req',
      url: 'dshboardServer/RestService/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '1,063',
      cpu: '104.954',
      severityBgColorField: '#337ABA',
    },
    {
      businessTransaction: 'Dashboard Service/Req',
      url: 'dshboardServer/RestService/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '2,063',
      cpu: '154.954',
      severityBgColorField: '#89b0d3',
    },
    {
      businessTransaction: 'Dashboard Service/Req',
      url: 'dshboardServer/RestService/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '1,011',
      cpu: '154.954',
      severityBgColorField: '#337ABA',
    },
    {
      businessTransaction: 'Dashboard Service/Req',
      url: 'dshboardServer/RestService/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '1,063',
      cpu: '111.954',
      severityBgColorField: '#89b0d3',
    },
    {
      businessTransaction: 'Dashboard Service/Req',
      url: 'dshboardServer/RestService/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '1,013',
      cpu: '154.954',
      severityBgColorField: '#337ABA',
    },
    {
      businessTransaction: 'Dashboard Service/Req',
      url: 'dshboardServer/RestService/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '1,953',
      cpu: '154.954',
      severityBgColorField: '#89b0d3',
    },
    {
      businessTransaction: 'Dashboard Service/Req',
      url: 'dshboardServer/RestService/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '8,063',
      cpu: '154.954',
      severityBgColorField: '#337ABA',
    },
    {
      businessTransaction: 'Dashboard Service/Req',
      url: 'dshboardServer/RestService/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '2,063',
      cpu: '154.954',
      severityBgColorField: '#337ABA',
    },
    {
      businessTransaction: 'Dashboard Service/Req',
      url: 'dshboardServer/RestService/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '3,063',
      cpu: '154.954',
      severityBgColorField: '#89b0d3',
    },
    {
      businessTransaction: 'Dashboard Service/Req',
      url: 'dshboardServer/RestService/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '1,300',
      cpu: '154.954',

    },
    {
      businessTransaction: 'Dashboard Service/Req',
      url: 'dshboardServer/RestService/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '2,063',
      cpu: '144.954',
      severityBgColorField: '#337ABA',
    },
    {
      businessTransaction: 'Dashboard Service/Req',
      url: 'dshboardServer/RestService/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '1,063',
      cpu: '132.954',
      severityBgColorField: '#89b0d3',
    },
    {
      businessTransaction: 'Dashboard Service/Req',
      url: 'dshboardServer/RestService/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '1,223',
      cpu: '154.954',
      severityBgColorField: '#337ABA',
    },
    {
      businessTransaction: 'Dashboard Service/Req',
      url: 'dshboardServer/RestService/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '1,373',
      cpu: '154.954',
      severityBgColorField: '#89b0d3',
    },
    {
      businessTransaction: 'Dashboard1 Service/Req',
      url: 'dshboardServer/RestService/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '1,063',
      cpu: '122.954',
      severityBgColorField: '#337ABA',
    },
    {
      businessTransaction: 'Dashboard Service/Req',
      url: 'dshboardServer/RestService/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '1,063',
      cpu: '104.954',
      severityBgColorField: '#89b0d3',
    },
    {
      businessTransaction: 'Dashboard Service/Req',
      url: 'dshboardServer/RestService/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '2,063',
      cpu: '154.954',
      severityBgColorField: '#337ABA',
    },
    {
      businessTransaction: 'Dashboard Service/Req',
      url: 'dshboardServer/RestService/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '1,011',
      cpu: '154.954',
      severityBgColorField: '#89b0d3',
    },
    {
      businessTransaction: 'Dashboard Service/Req',
      url: 'dshboardServer/RestService/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '1,063',
      cpu: '111.954',
      severityBgColorField: '#337ABA',
    },
    {
      businessTransaction: 'Dashboard Service/Req',
      url: 'dshboardServer/RestService/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '1,013',
      cpu: '154.954',
      severityBgColorField: '#89b0d3',
    },
    {
      businessTransaction: 'Dashboard Service/Req',
      url: 'dshboardServer/RestService/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '1,953',
      cpu: '154.954',
      severityBgColorField: '#337ABA',
    },
    {
      businessTransaction: 'Dashboard Service/Req',
      url: 'dshboardServer/RestService/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '8,063',
      cpu: '154.954',
      severityBgColorField: '#89b0d3',
    },
    {
      businessTransaction: 'Dashboard Service/Req',
      url: 'dshboardServer/RestService/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '2,063',
      cpu: '154.954',
      severityBgColorField: '#337ABA',
    },
    {
      businessTransaction: 'Dashboard Service/Req',
      url: 'dshboardServer/RestService/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '3,063',
      cpu: '154.954',
      severityBgColorField: '#89b0d3',
    },
    {
      businessTransaction: 'Dashboard Service/Req',
      url: 'dshboardServer/RestService/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '1,300',
      cpu: '154.954',
      severityBgColorField: '#89b0d3',
    },
    {
      businessTransaction: 'Dashboard Service/Req',
      url: 'dshboardServer/RestService/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '2,063',
      cpu: '144.954',
      severityBgColorField: '#89b0d3',
    },
    {
      businessTransaction: 'Dashboard Service/Req',
      url: 'dshboardServer/RestService/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '1,063',
      cpu: '132.954',
      severityBgColorField: '#89b0d3',
    },
    {
      businessTransaction: 'Dashboard Service/Req',
      url: 'dshboardServer/RestService/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '1,223',
      cpu: '154.954',
      severityBgColorField: '#89b0d3',
    },
    {
      businessTransaction: 'Dashboard Service/Req',
      url: 'dshboardServer/RestService/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '1,373',
      cpu: '154.954',
      severityBgColorField: '#89b0d3',
    },
    {
      businessTransaction: 'Dashboard1 Service/Req',
      url: 'dshboardServer/RestService/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '1,063',
      cpu: '122.954',
      severityBgColorField: '#89b0d3',
    },
    {
      businessTransaction: 'Dashboard Service/Req',
      url: 'dshboardServer/RestService/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '1,063',
      cpu: '104.954',
      severityBgColorField: '#89b0d3',
    },
    {
      businessTransaction: 'Dashboard Service/Req',
      url: 'dshboardServer/RestService/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '2,063',
      cpu: '154.954',
      severityBgColorField: '#89b0d3',
    },
    {
      businessTransaction: 'Dashboard Service/Req',
      url: 'dshboardServer/RestService/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '1,011',
      cpu: '154.954',
      severityBgColorField: '#89b0d3',
    },
    {
      businessTransaction: 'Dashboard Service/Req',
      url: 'dshboardServer/RestService/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '1,063',
      cpu: '111.954',
      severityBgColorField: '#89b0d3',
    },
    {
      businessTransaction: 'Dashboard Service/Req',
      url: 'dshboardServer/RestService/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '1,013',
      cpu: '154.954',
      severityBgColorField: '#89b0d3',

    },
    {
      businessTransaction: 'Dashboard Service/Req',
      url: 'dshboardServer/RestService/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '1,953',
      cpu: '154.954',
      severityBgColorField: '#89b0d3',

    },
    {
      businessTransaction: 'Dashboard Service/Req',
      url: 'dshboardServer/RestService/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '8,063',
      cpu: '154.954',
      severityBgColorField: '#89b0d3',

    },
    {
      businessTransaction: 'Dashboard Service/Req',
      url: 'dshboardServer/RestService/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '2,063',
      cpu: '154.954',
      severityBgColorField: '#89b0d3',

    },
    {
      businessTransaction: 'Dashboard Service/Req',
      url: 'dshboardServer/RestService/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '3,063',
      cpu: '154.954',
      severityBgColorField: '#89b0d3',

    },
    {
      businessTransaction: 'Dashboard Service/Req',
      url: 'dshboardServer/RestService/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '1,300',
      cpu: '154.954',
      severityBgColorField: '#89b0d3',

    },
    {
      businessTransaction: 'Dashboard Service/Req',
      url: 'dshboardServer/RestService/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '2,063',
      cpu: '144.954',
      severityBgColorField: '#89b0d3',
    },
    {
      businessTransaction: 'Dashboard Service/Req',
      url: 'dshboardServer/RestService/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '1,063',
      cpu: '132.954',

    },
    {
      businessTransaction: 'Dashboard Service/Req',
      url: 'dshboardServer/RestService/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '1,223',
      cpu: '154.954',

    },
    {
      businessTransaction: 'Dashboard Service/Req',
      url: 'dshboardServer/RestService/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '1,373',
      cpu: '154.954',

    },
    {
      businessTransaction: 'Dashboard1 Service/Req',
      url: 'dshboardServer/RestService/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '1,063',
      cpu: '122.954',

    },
    {
      businessTransaction: 'Dashboard Service/Req',
      url: 'dshboardServer/RestService/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '1,063',
      cpu: '104.954',

    },
    {
      businessTransaction: 'Dashboard Service/Req',
      url: 'dshboardServer/RestService/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '2,063',
      cpu: '154.954',

    },
    {
      businessTransaction: 'Dashboard Service/Req',
      url: 'dshboardServer/RestService/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '1,011',
      cpu: '154.954',

    },
    {
      businessTransaction: 'Dashboard Service/Req',
      url: 'dshboardServer/RestService/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '1,063',
      cpu: '111.954',

    },
    {
      businessTransaction: 'Dashboard Service/Req',
      url: 'dshboardServer/RestService/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '1,013',
      cpu: '154.954',

    },
    {
      businessTransaction: 'Dashboard Service/Req',
      url: 'dshboardServer/RestService/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '1,953',
      cpu: '154.954',

    },
    {
      businessTransaction: 'Dashboard Service/Req',
      url: 'dshboardServer/RestService/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '8,063',
      cpu: '154.954',

    },
    {
      businessTransaction: 'Dashboard Service/Req',
      url: 'dshboardServer/RestService/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '2,063',
      cpu: '154.954',

    },
    {
      businessTransaction: 'Dashboard Service/Req',
      url: 'dshboardServer/RestService/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '3,063',
      cpu: '154.954',

    },
    {
      businessTransaction: 'Dashboard Service/Req',
      url: 'dshboardServer/RestService/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '1,300',
      cpu: '154.954',

    },
    {
      businessTransaction: 'Dashboard Service/Req',
      url: 'dshboardServer/RestService/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '2,063',
      cpu: '144.954',

    },
    {
      businessTransaction: 'Dashboard Service/Req',
      url: 'dshboardServer/RestService/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '1,063',
      cpu: '132.954',

    },
    {
      businessTransaction: 'Dashboard Service/Req',
      url: 'dshboardServer/RestService/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '1,223',
      cpu: '154.954',

    },
    {
      businessTransaction: 'Dashboard Service/Req',
      url: 'dshboardServer/RestService/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '1,373',
      cpu: '154.954',

    },
    {
      businessTransaction: 'Dashboard1 Service/Req',
      url: 'dshboardServer/RestService/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '1,063',
      cpu: '122.954',

    },
    {
      businessTransaction: 'Dashboard Service/Req',
      url: 'dshboardServer/RestService/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '1,063',
      cpu: '104.954',

    },
    {
      businessTransaction: 'Dashboard Service/Req',
      url: 'dshboardServer/RestService/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '2,063',
      cpu: '154.954',

    },
    {
      businessTransaction: 'Dashboard Service/Req',
      url: 'dshboardServer/RestService/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '1,011',
      cpu: '154.954',

    },
    {
      businessTransaction: 'Dashboard Service/Req',
      url: 'dshboardServer/RestService/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '1,063',
      cpu: '111.954',

    },
    {
      businessTransaction: 'Dashboard Service/Req',
      url: 'dshboardServer/RestService/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '1,013',
      cpu: '154.954',

    },
    {
      businessTransaction: 'Dashboard Service/Req',
      url: 'dshboardServer/RestService/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '1,953',
      cpu: '154.954',

    },
    {
      businessTransaction: 'Dashboard Service/Req',
      url: 'dshboardServer/RestService/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '8,063',
      cpu: '154.954',

    },
    {
      businessTransaction: 'Dashboard Service/Req',
      url: 'dshboardServer/RestService/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '2,063',
      cpu: '154.954',

    },
    {
      businessTransaction: 'Dashboard Service/Req',
      url: 'dshboardServer/RestService/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '3,063',
      cpu: '154.954',

    },
    {
      businessTransaction: 'Dashboard Service/Req',
      url: 'dshboardServer/RestService/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '1,300',
      cpu: '154.954',

    },
    {
      businessTransaction: 'Dashboard Service/Req',
      url: 'dshboardServer/RestService/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '2,063',
      cpu: '144.954',

    },
    {
      businessTransaction: 'Dashboard Service/Req',
      url: 'dshboardServer/RestService/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '1,063',
      cpu: '132.954',

    },
    {
      businessTransaction: 'Dashboard Service/Req',
      url: 'dshboardServer/RestService/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '1,223',
      cpu: '154.954',

    },
    {
      businessTransaction: 'Dashboard Service/Req',
      url: 'dshboardServer/RestService/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '1,373',
      cpu: '154.954',

    },
    {
      businessTransaction: 'Dashboard1 Service/Req',
      url: 'dshboardServer/RestService/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '1,063',
      cpu: '122.954',

    },
    {
      businessTransaction: 'Dashboard Service/Req',
      url: 'dshboardServer/RestService/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '1,063',
      cpu: '104.954',

    },
    {
      businessTransaction: 'Dashboard Service/Req',
      url: 'dshboardServer/RestService/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '2,063',
      cpu: '154.954',

    },
    {
      businessTransaction: 'Dashboard Service/Req',
      url: 'dshboardServer/RestService/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '1,011',
      cpu: '154.954',

    },
    {
      businessTransaction: 'Dashboard Service/Req',
      url: 'dshboardServer/RestService/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '1,063',
      cpu: '111.954',

    },
    {
      businessTransaction: 'Dashboard Service/Req',
      url: 'dshboardServer/RestService/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '1,013',
      cpu: '154.954',

    },
    {
      businessTransaction: 'Dashboard Service/Req',
      url: 'dshboardServer/RestService/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '1,953',
      cpu: '154.954',

    },
    {
      businessTransaction: 'Dashboard Service/Req',
      url: 'dshboardServer/RestService/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '8,063',
      cpu: '154.954',

    },
    {
      businessTransaction: 'Dashboard Service/Req',
      url: 'dshboardServer/RestService/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '2,063',
      cpu: '154.954',

    },
    {
      businessTransaction: 'Dashboard Service/Req',
      url: 'dshboardServer/RestService/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '3,063',
      cpu: '154.954',

    },
    {
      businessTransaction: 'Dashboard Service/Req',
      url: 'dshboardServer/RestService/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '1,300',
      cpu: '154.954',

    },
    {
      businessTransaction: 'Dashboard Service/Req',
      url: 'dshboardServer/RestService/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '2,063',
      cpu: '144.954',

    },
    {
      businessTransaction: 'Dashboard Service/Req',
      url: 'dshboardServer/RestService/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '1,063',
      cpu: '132.954',

    },
    {
      businessTransaction: 'Dashboard Service/Req',
      url: 'dshboardServer/RestService/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '1,223',
      cpu: '154.954',

    },
    {
      businessTransaction: 'Dashboard Service/Req',
      url: 'dshboardServer/RestService/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '1,373',
      cpu: '154.954',

    },
    {
      businessTransaction: 'Dashboard1 Service/Req',
      url: 'dshboardServer/RestService/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '1,063',
      cpu: '122.954',

    },
    {
      businessTransaction: 'Dashboard Service/Req',
      url: 'dshboardServer/RestService/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '1,063',
      cpu: '104.954',

    },
    {
      businessTransaction: 'Dashboard Service/Req',
      url: 'dshboardServer/RestService/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '2,063',
      cpu: '154.954',

    },
    {
      businessTransaction: 'Dashboard Service/Req',
      url: 'dshboardServer/RestService/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '1,011',
      cpu: '154.954',

    },
    {
      businessTransaction: 'Dashboard Service/Req',
      url: 'dshboardServer/RestService/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '1,063',
      cpu: '111.954',

    },
    {
      businessTransaction: 'Dashboard Service/Req',
      url: 'dshboardServer/RestService/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '1,013',
      cpu: '154.954',

    },
    {
      businessTransaction: 'Dashboard Service/Req',
      url: 'dshboardServer/RestService/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '1,953',
      cpu: '154.954',

    },
    {
      businessTransaction: 'Dashboard Service/Req',
      url: 'dshboardServer/RestService/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '8,063',
      cpu: '154.954',

    },
    {
      businessTransaction: 'Dashboard Service/Req',
      url: 'dshboardServer/RestService/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '2,063',
      cpu: '154.954',

    },
    {
      businessTransaction: 'Dashboard Service/Req',
      url: 'dshboardServer/RestService/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '3,063',
      cpu: '154.954',

    },
    {
      businessTransaction: 'Dashboard Service/Req',
      url: 'dshboardServer/RestService/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '1,300',
      cpu: '154.954',

    },
    {
      businessTransaction: 'Dashboard Service/Req',
      url: 'dshboardServer/RestService/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '2,063',
      cpu: '144.954',

    },
    {
      businessTransaction: 'Dashboard Service/Req',
      url: 'dshboardServer/RestService/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '1,063',
      cpu: '132.954',

    },
    {
      businessTransaction: 'Dashboard Service/Req',
      url: 'dshboardServer/RestService/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '1,223',
      cpu: '154.954',

    },
    {
      businessTransaction: 'Dashboard Service/Req',
      url: 'dshboardServer/RestService/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '1,373',
      cpu: '154.954',

    },
    {
      businessTransaction: 'Dashboard1 Service/Req',
      url: 'dshboardServer/RestService/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '1,063',
      cpu: '122.954',

    },
    {
      businessTransaction: 'Dashboard Service/Req',
      url: 'dshboardServer/RestService/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '1,063',
      cpu: '104.954',

    },
    {
      businessTransaction: 'Dashboard Service/Req',
      url: 'dshboardServer/RestService/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '2,063',
      cpu: '154.954',

    },
    {
      businessTransaction: 'Dashboard Service/Req',
      url: 'dshboardServer/RestService/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '1,011',
      cpu: '154.954',

    },
    {
      businessTransaction: 'Dashboard Service/Req',
      url: 'dshboardServer/RestService/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '1,063',
      cpu: '111.954',

    },
    {
      businessTransaction: 'Dashboard Service/Req',
      url: 'dshboardServer/RestService/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '1,013',
      cpu: '154.954',

    },
    {
      businessTransaction: 'Dashboard Service/Req',
      url: 'dshboardServer/RestService/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '1,953',
      cpu: '154.954',

    },
    {
      businessTransaction: 'Dashboard Service/Req',
      url: 'dshboardServer/RestService/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '8,063',
      cpu: '154.954',

    },
    {
      businessTransaction: 'Dashboard Service/Req',
      url: 'dshboardServer/RestService/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '2,063',
      cpu: '154.954',

    },
    {
      businessTransaction: 'Dashboard Service/Req',
      url: 'dshboardServer/RestService/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '3,063',
      cpu: '154.954',

    },
    {
      businessTransaction: 'Dashboard Service/Req',
      url: 'dshboardServer/RestService/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '1,300',
      cpu: '154.954',

    },
    {
      businessTransaction: 'Dashboard Service/Req',
      url: 'dshboardServer/RestService/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '2,063',
      cpu: '144.954',

    },
    {
      businessTransaction: 'Dashboard Service/Req',
      url: 'dshboardServer/RestService/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '1,063',
      cpu: '132.954',

    },
    {
      businessTransaction: 'Dashboard Service/Req',
      url: 'dshboardServer/RestService/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '1,223',
      cpu: '154.954',

    },
    {
      businessTransaction: 'Dashboard Service/Req',
      url: 'dshboardServer/RestService/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '1,373',
      cpu: '154.954',

    },
    {
      businessTransaction: 'Dashboard1 Service/Req',
      url: 'dshboardServer/RestService/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '1,063',
      cpu: '122.954',

    },
    {
      businessTransaction: 'Dashboard Service/Req',
      url: 'dshboardServer/RestService/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '1,063',
      cpu: '104.954',

    },
    {
      businessTransaction: 'Dashboard Service/Req',
      url: 'dshboardServer/RestService/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '2,063',
      cpu: '154.954',

    },
    {
      businessTransaction: 'Dashboard Service/Req',
      url: 'dshboardServer/RestService/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '1,011',
      cpu: '154.954',

    },
    {
      businessTransaction: 'Dashboard Service/Req',
      url: 'dshboardServer/RestService/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '1,063',
      cpu: '111.954',

    },
    {
      businessTransaction: 'Dashboard Service/Req',
      url: 'dshboardServer/RestService/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '1,013',
      cpu: '154.954',

    },
    {
      businessTransaction: 'Dashboard Service/Req',
      url: 'dshboardServer/RestService/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '1,953',
      cpu: '154.954',

    },
    {
      businessTransaction: 'Dashboard Service/Req',
      url: 'dshboardServer/RestService/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '8,063',
      cpu: '154.954',

    },
    {
      businessTransaction: 'Dashboard Service/Req',
      url: 'dshboardServer/RestService/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '2,063',
      cpu: '154.954',

    },
    {
      businessTransaction: 'Dashboard Service/Req',
      url: 'dshboardServer/RestService/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '3,063',
      cpu: '154.954',

    },
    {
      businessTransaction: 'Dashboard Service/Req',
      url: 'dshboardServer/RestService/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '1,300',
      cpu: '154.954',

    },
    {
      businessTransaction: 'Dashboard Service/Req',
      url: 'dshboardServer/RestService/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '2,063',
      cpu: '144.954',

    },
    {
      businessTransaction: 'Dashboard Service/Req',
      url: 'dshboardServer/RestService/kpinfo?request',
      category: 'Normal',
      startTime: '07:09(03/24/20)',
      responseTime: '1,063',
      cpu: '132.954',

    },
  ],
  paginator: {
    first: 1,
    rows: 10,
    rowsPerPageOptions: [10, 30, 50, 100],
  },
  tableFilter: false,
};