import { ShardsData } from './shards.model';

export const SHARDS_DATA: ShardsData = {
  shardData: {
    headers: [
      {
        cols: [
          {
            label: 'Shard',
            valueField: 'shard',
            classes: 'text-left',
            selected: true,
            severityColorField: true,
            filter: {
              isFilter: true,
              type: 'contains',
            },
            isSort: true,
          },
          {
            label: '#Docs',
            valueField: 'docs',
            classes: 'text-left',
            selected: true,
            filter: {
              isFilter: true,
              type: 'contains',
            },
            isSort: true,
          },
          {
            label: 'Prime Size',
            valueField: 'primeSize',
            classes: 'text-left',
            selected: true,
            filter: {
              isFilter: true,
              type: 'contains',
            },
            isSort: false,
          },
          {
            label: '#Shards',
            valueField: 'shards',
            classes: 'text-left',
            selected: true,
            filter: {
              isFilter: true,
              type: 'contains',
            },
            isSort: true,
          },
          {
            label: '#Replicas',
            valueField: 'replicas',
            classes: 'text-left',
            selected: true,
            filter: {
              isFilter: true,
              type: 'contains',
            },
            isSort: true,
          },
          {
            label: 'Status',
            valueField: 'status',
            classes: 'text-left',
            selected: true,
            filter: {
              isFilter: true,
              type: 'custom',
            },
            isSort: true,
          },
        ],
      },
    ],
    data: [
      {
        shard: 'netForest',
        docs: 'dashboard',
        primeSize: '1',
        shards: 'NF-alert-dashboard',
        replicas: '',
        status: '',
      },
      {
        shard: 'netForest_m',
        docs: 'dashboard',
        primeSize: '2',
        shards: 'NF-alert-dashboard',
        replicas: '',
        status: '',
      },
      {
        shard: 'netForest',
        docs: 'dashboard',
        primeSize: '1',
        shards: 'NF-alert-dashboard',
        replicas: '',
        status: '',
      },
      {
        shard: 'netForest_m',
        docs: 'dashboard',
        primeSize: '2',
        shards: 'NF-alert-dashboard',
        replicas: '',
        status: '',
      },
      {
        shard: 'netForest',
        docs: 'dashboard',
        primeSize: '1',
        shards: 'NF-alert-dashboard',
        replicas: '',
        status: '',
      },
      {
        shard: 'netForest_m',
        docs: 'dashboard',
        primeSize: '2',
        shards: 'NF-alert-dashboard',
        replicas: '',
        status: '',
      },
      {
        shard: 'netForest',
        docs: 'dashboard',
        primeSize: '1',
        shards: 'NF-alert-dashboard',
        replicas: '',
        status: '',
      },
      {
        shard: 'netForest_m',
        docs: 'dashboard',
        primeSize: '2',
        shards: 'NF-alert-dashboard',
        replicas: '',
        status: '',
      },
      {
        shard: 'netForest',
        docs: 'dashboard',
        primeSize: '1',
        shards: 'NF-alert-dashboard',
        replicas: '',
        status: '',
      },
      {
        shard: 'netForest_m',
        docs: 'dashboard',
        primeSize: '2',
        shards: 'NF-alert-dashboard',
        replicas: '',
        status: '',
      },
      {
        shard: 'netForest',
        docs: 'dashboard',
        primeSize: '1',
        shards: 'NF-alert-dashboard',
        replicas: '',
        status: '',
      },
      {
        shard: 'netForest_m',
        docs: 'dashboard',
        primeSize: '2',
        shards: 'NF-alert-dashboard',
        replicas: '',
        status: '',
      },
      {
        shard: 'netForest',
        docs: 'dashboard',
        primeSize: '1',
        shards: 'NF-alert-dashboard',
        replicas: '',
        status: '',
        skucount: '',
        timestamp: '',
        kus: '',
        restime: '',
        sizeinbytes: '',
        userlogin: '',
      },
      {
        shard: 'netForest_m',
        docs: 'dashboard',
        primeSize: '2',
        shards: 'NF-alert-dashboard',
        replicas: '',
        status: '',
        skucount: '',
        timestamp: '',
        kus: '',
        restime: '',
        sizeinbytes: '',
        userlogin: '',
      },
      {
        shard: 'netForest',
        docs: 'dashboard',
        primeSize: '1',
        shards: 'NF-alert-dashboard',
        replicas: '',
        status: '',
        skucount: '',
        timestamp: '',
        kus: '',
        restime: '',
        sizeinbytes: '',
        userlogin: '',
      },
      {
        shard: 'netForest_m',
        docs: 'dashboard',
        primeSize: '2',
        shards: 'NF-alert-dashboard',
        replicas: '',
        status: '',
        skucount: '',
        timestamp: '',
        kus: '',
        restime: '',
        sizeinbytes: '',
        userlogin: '',
      },
      {
        shard: 'netForest',
        docs: 'dashboard',
        primeSize: '1',
        shards: 'NF-alert-dashboard',
        replicas: '',
        status: '',
        skucount: '',
        timestamp: '',
        kus: '',
        restime: '',
        sizeinbytes: '',
        userlogin: '',
      },
      {
        shard: 'netForest_m',
        docs: 'dashboard',
        primeSize: '2',
        shards: 'NF-alert-dashboard',
        replicas: '',
        status: '',
        skucount: '',
        timestamp: '',
        kus: '',
        restime: '',
        sizeinbytes: '',
        userlogin: '',
      },
      {
        shard: 'netForest',
        docs: 'dashboard',
        primeSize: '1',
        shards: 'NF-alert-dashboard',
        replicas: '',
        status: '',
        skucount: '',
        timestamp: '',
        kus: '',
        restime: '',
        sizeinbytes: '',
        userlogin: '',
      },
      {
        shard: 'netForest_m',
        docs: 'dashboard',
        primeSize: '2',
        shards: 'NF-alert-dashboard',
        replicas: '',
        status: '',
        skucount: '',
        timestamp: '',
        kus: '',
        restime: '',
        sizeinbytes: '',
        userlogin: '',
      },
      {
        shard: 'netForest',
        docs: 'dashboard',
        primeSize: '1',
        shards: 'NF-alert-dashboard',
        replicas: '',
        status: '',
        skucount: '',
        timestamp: '',
        kus: '',
        restime: '',
        sizeinbytes: '',
        userlogin: '',
      },
      {
        shard: 'netForest_m',
        docs: 'dashboard',
        primeSize: '2',
        shards: 'NF-alert-dashboard',
        replicas: '',
        status: '',
        skucount: '',
        timestamp: '',
        kus: '',
        restime: '',
        sizeinbytes: '',
        userlogin: '',
      },
      {
        shard: 'netForest',
        docs: 'dashboard',
        primeSize: '1',
        shards: 'NF-alert-dashboard',
        replicas: '',
        status: '',
        skucount: '',
        timestamp: '',
        kus: '',
        restime: '',
        sizeinbytes: '',
        userlogin: '',
      },
      {
        shard: 'netForest_m',
        docs: 'dashboard',
        primeSize: '2',
        shards: 'NF-alert-dashboard',
        replicas: '',
        status: '',
        skucount: '',
        timestamp: '',
        kus: '',
        restime: '',
        sizeinbytes: '',
        userlogin: '',
      },
      {
        shard: 'netForest',
        docs: 'dashboard',
        primeSize: '1',
        shards: 'NF-alert-dashboard',
        replicas: '',
        status: '',
        skucount: '',
        timestamp: '',
        kus: '',
        restime: '',
        sizeinbytes: '',
        userlogin: '',
      },
      {
        shard: 'netForest_m',
        docs: 'dashboard',
        primeSize: '2',
        shards: 'NF-alert-dashboard',
        replicas: '',
        status: '',
        skucount: '',
        timestamp: '',
        kus: '',
        restime: '',
        sizeinbytes: '',
        userlogin: '',
      },
      {
        shard: 'netForest',
        docs: 'dashboard',
        primeSize: '1',
        shards: 'NF-alert-dashboard',
        replicas: '',
        status: '',
        skucount: '',
        timestamp: '',
        kus: '',
        restime: '',
        sizeinbytes: '',
        userlogin: '',
      },
      {
        shard: 'netForest_m',
        docs: 'dashboard',
        primeSize: '2',
        shards: 'NF-alert-dashboard',
        replicas: '',
        status: '',
        skucount: '',
        timestamp: '',
        kus: '',
        restime: '',
        sizeinbytes: '',
        userlogin: '',
      },
      {
        shard: 'netForest',
        docs: 'dashboard',
        primeSize: '1',
        shards: 'NF-alert-dashboard',
        replicas: '',
        status: '',
        skucount: '',
        timestamp: '',
        kus: '',
        restime: '',
        sizeinbytes: '',
        userlogin: '',
      },
      {
        shard: 'netForest_m',
        docs: 'dashboard',
        primeSize: '2',
        shards: 'NF-alert-dashboard',
        replicas: '',
        status: '',
        skucount: '',
        timestamp: '',
        kus: '',
        restime: '',
        sizeinbytes: '',
        userlogin: '',
      },
    ],
    paginator: {
      first: 0,
      rows: 10,
      rowsPerPageOptions: [10, 20, 30, 50, 100],
    },
    tableFilter: true,
  },
};
