import { EventsTable } from "./event.model";

export const EVENTS_TABLE: EventsTable = {
    search: {
      fields: [
        'tire',
        'time',
        'alertName',
        'server',
        'alertMessage',
        'type',
        'threshold',
        'alertValue',
      ],
    },

    sort: {
      fields: ['time', 'alertName', 'server', 'threshold', 'alertValue'],
    },

    paginator: {
      rows: 13,
    },

    headers: [
      {
        cols: [
          {
            label: 'Tire',
            valueField: 'tire',
            classes: 'text-center',
            severityColorField: true,
          },
          {
            label: 'Time',
            valueField: 'time',
            classes: 'text-right',
          },
          {
            label: 'Alert Name',
            valueField: 'alertName',
            classes: 'text-center',
            blinkerField: true,
          },
          {
            label: 'Server',
            valueField: 'server',
            classes: 'text-center',
          },
          {
            label: 'Alert Message',
            valueField: 'alertMessage',
            classes: 'text-center',
          },
          {
            label: 'Type',
            valueField: 'type',
            classes: 'text-center',
          },
          {
            label: 'Threshold',
            valueField: 'threshold',
            classes: 'text-center',
          },
          {
            label: 'Alert Value',
            valueField: 'alertValue',
            classes: 'text-left',
            drillField: true,
          },
        ],
      },
    ],
    data: [
      {
        tire: 'Overall',
        time: '08/26/2020 17:05:04',
        alertName: 'Page Alert',
        server: 'Home',
        alertMessage: 'alertMessage with',
        type: 'performance',
        threshold: '6.65 to 10.45',
        alertValue: 7.5,
        bilnk: true,
        read: true,
        severityColor: '#FF8484',
        rowBgColor: '#ff848424',
      },
      {
        tire: 'critical',
        time: '08/26/2020 17:05:04',
        alertName: 'Page Alert',
        server: 'Home',
        alertMessage: 'alertMessage with',
        type: 'performance',
        threshold: '6.65 to 10.45',
        alertValue: 7.5,
        bilnk: false,
        read: true,
        severityColor: '#FFDBDB',
        rowBgColor: '#ffdbdb24',
      },
      {
        tire: 'single',
        time: '08/26/2020 17:05:04',
        alertName: 'Page Alert',
        server: 'Home',
        alertMessage: 'alertMessage with',
        type: 'performance',
        threshold: '6.65 to 10.45',
        alertValue: 7.5,
        bilnk: true,
        read: false,
        severityColor: '#FF8484',
        rowBgColor: '#ff848424',
      },
      {
        tire: 'critical',
        time: '08/26/2020 17:05:04',
        alertName: 'Page Alert',
        server: 'Home',
        alertMessage: 'alertMessage with',
        type: 'performance',
        threshold: '6.65 to 10.45',
        alertValue: 10.25,
        bilnk: false,
        read: true,
        severityColor: '#FFDBDB',
        rowBgColor: '#ffdbdb24',
      },
      {
        tire: 'single',
        time: '08/26/2020 17:05:04',
        alertName: 'Page Alert',
        server: 'Home',
        alertMessage: 'alertMessage with',
        type: 'performance',
        threshold: '6.65 to 10.45',
        alertValue: 10.25,
        bilnk: true,
        read: false,
        severityColor: '#FF8484',
        rowBgColor: '#ff848424',
      },
      {
        tire: 'critical',
        time: '08/26/2020 17:05:04',
        alertName: 'Page Alert',
        server: 'Home',
        alertMessage: 'alertMessage with',
        type: 'performance',
        threshold: '6.65 to 10.45',
        alertValue: 10.25,
        bilnk: false,
        read: true,
        severityColor: '#FFDBDB',
        rowBgColor: '#ffdbdb24',
      },
      {
        tire: 'single',
        time: '08/26/2020 17:05:04',
        alertName: 'Page Alert',
        server: 'Home',
        alertMessage: 'alertMessage with',
        type: 'performance',
        threshold: '6.65 to 10.45',
        alertValue: 10.25,
        bilnk: true,
        read: false,
        severityColor: '#FF8484',
        rowBgColor: '#ff848424',
      },
      {
        tire: 'critical',
        time: '08/26/2020 17:05:04',
        alertName: 'Page Alert',
        server: 'Home',
        alertMessage: 'alertMessage with',
        type: 'performance',
        threshold: '6.65 to 10.45',
        alertValue: 10.25,
        bilnk: false,
        read: true,
        severityColor: '#FF8484',
        rowBgColor: '#ff848424',
      },
      {
        tire: 'single',
        time: '08/26/2020 17:05:04',
        alertName: 'Page Alert',
        server: 'Home',
        alertMessage: 'alertMessage with',
        type: 'performance',
        threshold: '6.65 to 10.45',
        alertValue: 10.25,
        bilnk: true,
        read: false,
        severityColor: '#FFB5B5',
        rowBgColor: '#ffb5b524',
      },
      {
        tire: 'critical',
        time: '08/26/2020 17:05:04',
        alertName: 'Page Alert',
        server: 'Home',
        alertMessage: 'alertMessage with',
        type: 'performance',
        threshold: '6.65 to 10.45',
        alertValue: 10.25,
        bilnk: false,
        read: true,
        severityColor: '#FFDBDB',
        rowBgColor: '#ffdbdb24',
      },
      {
        tire: 'single',
        time: '08/26/2020 17:05:04',
        alertName: 'Page Alert',
        server: 'Home',
        alertMessage: 'alertMessage with',
        type: 'performance',
        threshold: '6.65 to 10.45',
        alertValue: 10.25,
        bilnk: true,
        read: false,
        severityColor: '#FFB5B5',
        rowBgColor: '#ffb5b524',
      },
      {
        tire: 'critical',
        time: '08/26/2020 17:05:04',
        alertName: 'Page Alert',
        server: 'Home',
        alertMessage: 'alertMessage with',
        type: 'performance',
        threshold: '6.65 to 10.45',
        alertValue: 10.25,
        bilnk: false,
        read: true,
        severityColor: '#FFDBDB',
        rowBgColor: '#ffdbdb24',
      },
      {
        tire: 'single',
        time: '08/26/2020 17:05:04',
        alertName: 'Page Alert',
        server: 'Home',
        alertMessage: 'alertMessage with',
        type: 'performance',
        threshold: '6.65 to 10.45',
        alertValue: 10.25,
        bilnk: true,
        read: false,
        severityColor: '#FFB5B5',
        rowBgColor: '#ffb5b524',
      },
      {
        tire: 'critical',
        time: '08/26/2020 17:05:04',
        alertName: 'Page Alert',
        server: 'Home',
        alertMessage: 'alertMessage with',
        type: 'performance',
        threshold: '6.65 to 10.45',
        alertValue: 10.25,
        bilnk: false,
        read: true,
        severityColor: '#FFDBDB',
        rowBgColor: '#ffdbdb24',
      },
      {
        tire: 'single',
        time: '08/26/2020 17:05:04',
        alertName: 'Page Alert',
        server: 'Home',
        alertMessage: 'alertMessage with',
        type: 'performance',
        threshold: '6.65 to 10.45',
        alertValue: 10.25,
        bilnk: true,
        read: false,
        severityColor: '#FFB5B5',
        rowBgColor: '#ffb5b524',
      },
    ],

    filters: [
      {
        name: 'All',
        key: 'all',
        color: '#6197c7',
        selected: true,
        showInLegend: false,
      },
      {
        name: 'Critical',
        key: 'critical',
        color: '#FF8484',
        selected: false,
        showInLegend: true,
      },
      {
        name: 'Major',
        key: 'major',
        color: '#FFB5B5',
        selected: false,
        showInLegend: true,
      },
      {
        name: 'Minor',
        key: 'minor',
        color: '#FFDBDB',
        selected: false,
        showInLegend: true,
      },
    ],

    bilnkField: 'blink',
    readField: 'read',
    severityBgColorField: 'severityColor',
    rowBgColorField: 'rowBgColor',
  };